opal/opal

- stdlib/encoding.rb
Other rubies allow both `Encoding.find('binary')` and
`Encoding.find('BINARY')`. Opal was only allowing the uppercase version.
This change permits the lowercase search string as well.
> Use case insensitive search when finding Encodings

- lib/opal/paths.rb
Just a typo I ran across while reading the source :smile:  :abc:
> Fix typo in variable name

- opal/corelib/file.rb
`File::ALT_SEPARATOR` and `File::PATH_SEPARATOR`
> Add missing constants in File class.

- opal/corelib/string.rb
- opal/corelib/string/inheritance.rb
- spec/filters/bugs/string.rb
- spec/rubyspecs
DONE:
pass "String#[] with String returns other_str if it occurs in self"
pass "String#[] with String returns nil if there is no match"
TODO:
still fails "String#[] with String doesn't call to_str on its argument"
still fails "String#[] with String returns a subclass instance when
given a subclass instance”
> Implement String#[] with a string argument

- opal/corelib/module.rb
After [Cleanup Module#define_method](https://github.com/opal/opal/commit/33c509101ec89e35f965ad700773fa1abdc0f5ad), this happens when trying to run the test suite:
```
$ rake mspec
[40, :filters]
[189, :shared]
[577, :rubyspecs]
mkdir -p tmp
RUBYOPT="-rbundler/setup -rmspec/opal/special_calls" bin/opal -Ispec -Ilib -gmspec  -smspec/helpers/tmp -smspec/helpers/environment -smspec/guards/block_device -smspec/guards/endian -rnodejs -Dwarning -A tmp/mspec_node.rb
/private/var/folders/pt/kr0lwm4d20jgc_jvpc5fyk1r0000gn/T/opal-nodejs-runner-20150225-3692-g51yt4:1989
Opal.defn(self, jsid, block);
^
ReferenceError: jsid is not defined
at OpalClass.def.$define_method.TMP_2 [as $define_method] (/private/var/folders/pt/kr0lwm4d20jgc_jvpc5fyk1r0000gn/T/opal-nodejs-runner-20150225-3692-g51yt4:1989:25) …
```
> Fix 'Cleanup Module#define_method' refucktor

- opal/corelib/string.rb
Note that it says “…without escaping” in the spec:
```ruby
describe "String#match" do
#…
it "converts string patterns to regexps without escaping" do
'hello'.match('(.)\1')[0].should == 'll'
end
end
```
> Fix issue #666

- opal/corelib/array.rb
- opal/corelib/array/inheritance.rb
- spec/filters/bugs/array.rb
Also added `def.$$is_array = true` to `Array::Wrapper` because a sub-class of an array *is* an array. Just as with `String` inheritance a few PRs ago, I believe not having `def.$$is_array = true` defined on `Array::Wrapper` must have been an error of omission.
> Array#flatten and Array#flatten! implementation fully compliant with rubyspec

- opal/corelib/string.rb
> String#scan: use MatchData captures to deal with undefined values

- CHANGELOG.md
- opal/corelib/string.rb
- spec/filters/bugs/string.rb
*"String#=== returns false if obj does not respond to to_str"* and  *"String#== returns false if obj does not respond to to_str"* actually pass, except for the one line that tests a symbol argument:
```ruby
'hello'.send(@method, :hello).should be_false
```
Same goes for *"String#eql? when given a non-String returns false"* - only the following line fails:
```ruby 
'hello'.should_not eql(:hello)
```
There is currently no way to pass these assertions because strings and symbols are identical in Opal.
I really would like to see those `fail` lines gone from filters/bugs/string.rb, and I see 3 possible courses of action (in the order from least invasive to most invasive to Opal):
1. Wrap `not_compliant_on :opal do ...` around the offending assertions in the rubyspec. 
2. Set a new additional …
> String#===, String#==, and String#eql? implementation fully compliant with rubyspec

- spec/opal/stdlib/promise/then_spec.rb
- stdlib/promise.rb
This fixes an issue where the following prints 5 instead of nil
```ruby
Promise.new.resolve(5).then { nil }.then {|v| puts v.inspect }
```
Thanks!
> Fix issue with @delayed ignoring falsy values in Promise.

- lib/opal/path_reader.rb
- tasks/testing.rake
With a little care, the same Ruby code can run on Unix and on Windows.
> Make `rake mspec_node` runnable on Windows

- opal/corelib/kernel.rb
- spec/filters/bugs/kernel.rb
The only remaining `fail` in that file cannot be made to pass until https://github.com/opal/opal/issues/729 is addressed.
> Clean up spec/filters/bugs/kernel.rb

- opal/corelib/module.rb
- opal/corelib/struct.rb
- spec/filters/bugs/module.rb
- spec/filters/bugs/struct.rb
- spec/rubyspecs
@meh, I need your help with this one - I don't know what I'm doing :) You [fixed Struct inheritance back in 2013](https://github.com/opal/opal/commit/9677ea31a2630b3690507b9722b5730f7d0ea544), and you have this guard clause in your code: `return if self == Struct`. I removed it and all tests pass, but I'm worried I'm missing something here.
Also, I'm doing `include Enumerable` in the `self.inherited` hook even though `Struct` already has `include Enumerable` at the class level. If I don't do that, `StructClasses::Car.include?(Enumerable).should == true` fails. `StructClasses::Car` is defined as follows:
```ruby
module StructClasses
Car = Struct.new(:make, :model, :year)
end
```
So, is including `Enumerable` inside `self.inherited` the right way to go, or am I brute-forcing something that …
> Pass "Struct anonymous class instance methods includes Enumerable"

- opal/corelib/boolean.rb
- opal/corelib/numeric.rb
- opal/corelib/runtime.js
- opal/corelib/string.rb
- spec/opal/core/object_id_spec.rb
Fix #729. A different approach:
For strings, object_id can be simply their string representation. For
booleans, numbers, and nil, follow the MRI scheme:
* false: 0
* true: 2
* nil: 4
* numbers: (n * 2) + 1
* heap objects: 6, 8, 10, 12, 14, 16, etc…
> Experiment 2: define object_id for strings, numbers, and booleans

- spec/filters/bugs/kernel.rb
With *"('stuff'.equal? 'stuff').should == false" cannot be supported on Opal* now [merged](https://github.com/opal/rubyspec/pull/2) into opal/rubyspec, the last remaining failing assertion for *"Kernel#equal? returns true only if obj and other are the same object”* is passing. The last remaining failure can safely be removed from filters/bugs/kernel now.
> Pass "Kernel#equal? returns true only if obj and other are the same object"

- spec/filters/bugs/string.rb
Special-casing of +(binary) and -(binary) [has been removed from Ruby](https://www.ruby-forum.com/topic/4418067).
These specs originally failed for me on Windows, but the reason turned out to have nothing to do with Windows, but rather with the version of Ruby I had installed on that Windows machine, which was `ruby 2.0.0p247 (2013-06-27) [i386-mingw32]`. After updating to `ruby 2.0.0p643 (2015-02-25) [i386-mingw32]`, the specs passed.
> String#intern and String#to_sym fully compliant with rubyspec

- spec/opal/stdlib/native/native_class_spec.rb
- stdlib/native.rb
This takes care of the initial roadblock trying to run rubyspec on IE. Next up, dealing with invalid regexp flags per https://github.com/opal/opal/issues/740#issuecomment-78251397 which is not an IE-specific issue.
> Use `["new"]` instead of `.new` because `new` is a reserved keyword on IE < 9

- spec/filters/bugs/array.rb
Pass "Array#partition returns two arrays"
Pass "Array#partition does not return subclass instances on Array subclasses"
Still fails "Array#partition returns in the left array values for which the block evaluates to true" because of a problem with integer division in Opal (see https://github.com/opal/opal/issues/748)
E.g. `[0, 1, 2, 3, 4, 5].partition { |i| i / 3 == 0 }`
Expected: `[[0, 1, 2], [3, 4, 5]]`
Actual: `[[0], [1, 2, 3, 4, 5]]`
> Clean up Array#partition bug filter

- spec/filters/bugs/string.rb
https://github.com/opal/rubyspec/pull/3 makes it possible to finally remove the failing lines for `String#===`, `String#==`, and `String#eql?`
> Update spec/corelib submodule to make String#===, String#==, and String#eql? fully compliant with rubyspec

- opal/corelib/string.rb
- spec/filters/bugs/string.rb
Not sure about this one, need your feedback.
It looks like strings that contain non-ascii characters should not be lower-cased per rubyspec.
1. Does the above statement make sense?
2. Does my code for determining that a string is ascii-only make sense?
Thanks!
> RFC: String#casecmp fully compliant with rubyspec

- opal/corelib/match_data.rb
Despite passing rubyspec, the behavior of these methods does not match MRI:
MRI:
```
$ ruby -e "'hello'.sub(/ll/, ''); p $~.pre_match, $~.post_match"
"he"
"o"
```
Opal before the fix:
```
$ bundle exec opal -e "'hello'.sub(/ll/, ''); p $~.pre_match, $~.post_match"
""
"hello"
```
Opal after the fix:
```
$ bundle exec opal -e "'hello'.sub(/ll/, ''); p $~.pre_match, $~.post_match"
"he"
"o"
```
> Fix incorrect MatchData#pre_match and #post_match behavior

- opal/corelib/kernel.rb
The original regex `/(\d)_(\d)/g` did not handle some cases correctly (it did look so cute though!)
E.g. `"10_1_0.5_5_5"` became `"101_0.55_5"` instead of the expected `"1010.555"`. This issue was not caught by any of the rubyspec code for `Kernel#Integer` and `Kernel#Float`, but surfaced when testing `Kernel#format`. Changing the regex to `/(\d)_(?=\d)/g` fixed the issue.
> Fix underscore stripping regex in Kernel#Integer and Kernel#Float

- opal/corelib/kernel.rb
This behavior is not specified in rubyspec for `Kernel#Float`, but it
is tested in `Kernel#format`.
Surprisingly, `Kernel#Float` accepts hexadecimal strings, but no other
integer notation that is accepted by `Kernel#Integer`. I.e. `0x10` is
ok, but `0b10`, `0d10`, `0o10` are not acceptable. Looks like a bug to
me. I guess this PR makes Opal’s `Kernel#Float` a bug-for-bug
implementation of MRI’s `Kernel#Float` :)
```
$ pry
[1] pry(main)> Float("010")
=> 10.0
[2] pry(main)> Float("0o10")
ArgumentError: invalid value for Float(): "0o10"
from (pry):2:in `Float'
[3] pry(main)> Float("0b10")
ArgumentError: invalid value for Float(): "0b10"
from (pry):3:in `Float'
[4] pry(main)> Float("0d10")
ArgumentError: invalid value for Float(): "0d10"
from (pry):4:in `Float'
[5] pry(main)> Float("0x10")
=> …
```
> Kernel#Float accepts hex strings as a special case

- lib/opal/builder.rb
Well, I was having a look at the latest commits and I noticed that we `gsub` gaining no effect. So let's `gsub!`.
Also, just saying, at the moment machines running OSX 10.10.3 cannot `bundle` because of [this](http://stackoverflow.com/questions/29529455/missing-c-header-debug-after-updating-osx-command-line-tools-6-3).
> Fix deletion of rb/js/opal extension in Opal::Builder

- lib/opal/compiler.rb
- lib/opal/sprockets/processor.rb
- opal/corelib/array/inheritance.rb
- opal/corelib/string/inheritance.rb
Pass failing rubyspecs for String and Array inheritance
> Enable inline_operators by default

- opal/corelib/string.rb
- spec/filters/bugs/opal.rb
- spec/filters/unsupported/regular_expressions.rb
My goal was to clean up the failures, and it turned out that modifying `String#index` implementation was not necessary to make the failures go away, but re-writing it in JS made it over 2x faster based on my very un-scientific benchmark, so I decided to keep my re-implementation of `String#index`.
Before:
```
$ bundle exec opal -e "t = Time.now; 100000.times{'hello'.index(/ll/)}; puts Time.now - t"
1.44
$ bundle exec opal -e "t = Time.now; 100000.times{'hello'.index(/ll/)}; puts Time.now - t"
1.547
$ bundle exec opal -e "t = Time.now; 100000.times{'hello'.index(/ll/)}; puts Time.now - t"
1.537
$ bundle exec opal -e "t = Time.now; 100000.times{'hello'.index(/ll/)}; puts Time.now - t"
1.416
```
After:
```
$ bundle exec opal -e "t = Time.now; 100000.times{'hello'.index(/ll/)}; puts Time.now …
```
> String#index fully compliant with rubyspec

- lib/mspec/opal/runner.rb
- stdlib/nodejs/file.rb
- tasks/testing.rake
Re https://github.com/opal/opal/issues/736
This is the first phase of the project: just getting the raw performance data.
The way it works is you run the spec suite as you normally would, but set the `BM` environment variable to the number of iterations you want MSpec to perform on each `it` block. If this environment variable is present, Opal MSpec runner will record the number of milliseconds taken for each spec (across all iterations) and, at the end of the run, dump a JSON object with spec names for keys and milliseconds for values into a time-stamped file in the `tmp` directory.
```
$ bundle exec rake mspec_node PATTERN=spec/corelib/core/string/index_spec.rb BM=100
...
Finished
2000 examples, 0 failures (time taken: 2.8919999599456787)
```
Notice the `BM=100` above, and how it …
> Enable benchmarking of rubyspecs

- lib/opal/sprockets/processor.rb
- lib/tilt/opal.rb
- spec/lib/tilt/opal_spec.rb
This adds a tilt/opal.rb file that allows you to render opal templates
via Tilt without using sprockets. It changes lib/opal/sprockets/processor.rb
to load tilt/opal.rb and augment it with sprockets specific code.
This allows you to use opal with asset engines that don't use sprockets.
I'm not sure where to add specs for this, if you could point me to the appropriate place, I'll add some specs.  Ideally, these specs would load tilt/opal without loading lib/opal/sprockets/processor, to ensure that tilt/opal works standalone.  I've tested that manually, but I think there should be automated tests for it.
> Support tilt integration without sprockets

- lib/mspec/opal/rake_task.rb
- lib/opal/config.rb
- lib/opal/sprockets/processor.rb
- lib/tilt/opal.rb
- spec/lib/sprockets/processor_spec.rb
Completes PR #829 by @jeremyevans 
- extracts global/default config from Opal::Processor to the new entry Opal::Config (but still keeps config proxies on Opal::Processor)
- stops registering Opal::Processor as a Tilt template, we now have a dedicated class
I'll merge immediately, the PR is just to give it a bit of visibility :tophat:
> Opal::Config

- spec/filters/bugs/singleton.rb
- spec/filters/unsupported/marshal.rb
> RubySpec: Moving specs for Singleton#_dump to /unsupported

- lib/opal/builder.rb
It doesn't seem to work if you require opal/builder without
opal/paths.
> Make opal/builder depend on opal/paths

- spec/rubyspecs
- stdlib/set.rb
Added support for this based on Ruby's stdlib implementation. Observed while trying to make opal-rspec work with RSpec 3.1.
> Stdlib/Set methods, add the +,| operations and union method

- lib/opal/builder.rb
If you specify a message when raising an existing exception, ruby
does not use the exception's existing backtrace.
> Don't swallow backtrace when reraising error

- lib/mspec/opal/rake_task.rb
- lib/opal/builder.rb
- lib/opal/builder_processors.rb
- lib/opal/erb.rb
- lib/opal/nodes/call.rb
- lib/opal/nodes/call_special.rb
- lib/opal/nodes/helpers.rb
- lib/opal/parser/lexer.rb
- lib/opal/regexp_anchors.rb
- lib/opal/sprockets/erb.rb
- lib/opal/sprockets/processor.rb
- lib/opal/sprockets/source_map_server.rb
Unless you specifically want to match the start and end of any line
in the string, as opposed to the start and end of the string itself,
you should avoid using ^ and $.
I'm not sure if all of these changes are correct.  Maybe in some cases
where I made changes, you do want to match start/end of any line
in the string instead of the start/end of the string itself.
> Replace ^ and $ with \A and \z in regular expressions

- lib/opal/path_reader.rb
- spec/lib/path_reader_spec.rb
This allows you do do things like:
Opal::Builder.build('/path/to/file.rb')
Opal::Builder.build('./path/to/file.rb')
Opal::Builder.build('../path/to/file.rb')
Previously, you couldn't build a file without adding a directory
containing the file to the paths to examine.  This makes Opal::Builder
operate more like ruby itself.
Note that this does not let you use absolute and ./ and ../ relative
paths in require, that requires additional changes, probably to
Builder#process_require.
> Allow PathReader to deal with absolute and ./ and ../ relative paths

- lib/opal/builder.rb
- lib/opal/cli.rb
- lib/opal/path_reader.rb
- lib/opal/paths.rb
- lib/tilt/opal.rb
- spec/lib/builder_spec.rb
- spec/lib/cli_spec.rb
- spec/lib/tilt/opal_spec.rb
If :build option is used, the Opal::Builder defaults are used.
If :builder option is used, you can pass in your own custom
builder, which could have per-build stubs, append_paths, and
use_gems to change building without modifying global state.
Using this, it's possible to build arbitrary opal projects that
require other files using tilt without sprockets.
In order to get this to work, I had to make Opal.append_path
and Opal.use_gem available per builder instance, and fix
Opal::Builder#dup to work correctly, which is what the earlier
commits are for.
The Opal::CLI commit is not necessary, but I think it's a good
idea in general to avoid mutating global state unless it is
necessary.
> Allow tilt/opal to use Opal::Builder with :build or :builder options

- .jshintrc
- opal/corelib/enumerable.rb
- opal/corelib/hash.rb
- opal/corelib/module.rb
- opal/corelib/runtime.js
- stdlib/native.rb
Fix all accidental global variables except for those that are generated because of compiler bugs #875, #876, and #877.
> Fix all accidental global variables except the compiler-generated ones

- opal/corelib/module.rb
Defining a class-level self.name should not have any effect on class.to_s
> Fix issue #816

- .travis.yml
- Gemfile
- opal.gemspec
Now that you can build complex opal projects using tilt instead of
sprockets, it doesn't make sense to require sprockets.
As sprockets 3+ doesn't require tilt, it doesn't really make sense
to keep tilt as a runtime dependency, since you should be able to
use sprockets without using tilt. However, Opal::Processor is
currently a subclass of Opal::TiltTemplate, so it doesn't matter
if you are using opal with tilt or sprockets, in either case tilt
is still required for using opal.
If Opal::Processor can be made to run without tilt, I think we
should make both tilt and sprockets development dependencies
instead of runtime dependencies.
The tilt/opal tests run fine with tilt 2, so I don't think we
should restrict people to using tilt 1.4, as then users of opal
can't use the new useful features …
> Make sprockets a development dependency instead of runtime, allow tilt 2

- lib/opal/nodes/singleton_class.rb
Fix #875 
Fix #876 
Basically the problem here is that the temporary variable is requested to be created in the parent scope while processing the body AFTER `to_vars` on the parent scope has already been called. I.e., it's too late for it to have any effect since `to_vars` has already been called. The solution is simple then: process the body first, then call `to_vars`.
> Fix issues #875 and #876 (compiler generates accidental globals compiling `class << ...`)

- lib/opal/nodes/iter.rb
Fix #877
Basically what was happening is that args to a proc inside of a method were incorrectly set as args on the parent scope. Then, since they supposedly already exist in the args array, they were excluded from being declared with `var`.
> Fix #877 (compiler generates accidental global var if proc arg used outside proc)

- .jshintrc
Now that https://github.com/opal/opal/pull/891 and https://github.com/opal/opal/pull/892 are merged in, we no longer have any accidental globals in JS, so it's time to enable JSHint's `'variable' is not defined` check for realz (FTW, for googness' sake, for the love of god, etc.)
> Enable JSHint's "'variable' is not defined" check (aka detect global leaks)

- opal/corelib/kernel.rb
@elia here's the PR as requested via #675.
I also saw @meh said "There's no concept of private or public in Opal...".  Shouldn't we add some way to track public and private methods?  There are a few ruby methods that rely on it, which would cause unexpected results if you are using the same class client/server side.
> alias public_methods methods

- lib/opal/parser.rb
Without this, there is an error formatting the exception message
(ArgumentError: negative argument), and the underlying exception
is lost.
> Handle parser errors when lexer column is 0

- spec/opal/stdlib/js_spec.rb
- stdlib/js.rb
This adds support for calling the following javascript operators:
delete, in, instanceof, new, typeof, and void.  It also supports
calling global javascript functions via call.  call is aliased
to method_missing, so that you can do JS.globalFunction() to
call global javascript functions.
> Add JS module for nicer calling of native javascript operators and global functions

- lib/opal/cli_options.rb
Trivial but caught my eye on a `bundle exec opal -h`.
> Fix typo in the description of the -D option

- .travis.yml
Was an attempt to speed up the build but seems to do more harm than good
> Remove Travis cache for Git submodules 

- spec/filters/bugs/array.rb
These specs pass already, so removing them from the filters
> Removing filters for Array#* for RubySpecs that are already passing

- Gemfile
So RubySpec runs on an expected version of MSpec.
Also, `ruby/mspec` does not depend on `fileutils` anymore.
> Use ruby/mspec for MSpec

- stdlib/rbconfig.rb
The first is needed for `ruby_exe` but I am not confident if this works yet.
The second is a standard `RUBY_` constant along VERSION, ENGINE, etc.
> Define only the necessary constants for MSpec

- CODE_OF_CONDUCT.md
Taken from standard Bundler boilerplate, sourced from:
http://contributor-covenant.org/version/1/0/0/
> Add Contributor Covenant's Code of Conduct

- CODE_OF_CONDUCT.md
My thought here is that since harassment of any form is already specifically covered, it's better to only ban -overtly- sexual language so that a single genuine misunderstanding doesn't become a casus belli.
Bear in mind that once the misunderstanding has been explained, doing it again falls neatly under the dictionary definition of harassment and as such this tweak shouldn't allow anybody who -was- being a dick to weasel out of it.
@adambeynon @sarciszewski @jaen @webmaven thoughts if you have any, please
> tweak sexual language wording

- CODE_OF_CONDUCT.md
This was originally the wording @strand and I worked out previously, which @adambeynon recently commented he thought at least the concept of was useful. It's been tweaked since though so please read the whole thread to understand where it's coming from.
I'm happy to (continue to :) bikeshed the phrasing until everybody's happy - I just think we need to draw *some* sort of explicit line here.
@adambeynon @sarciszewski @jaen @webmaven thoughts if you have any, please
> add wording to explicitly clarify which spaces the CoC applies in

- bin/opal-repl
> Improve the error message displayed when therubyracer gem is missing

- opal/corelib/string.rb
Fix #973
Handle the special case where no matches are found, regardless of the `limit` parameter, return an array containing a single element that is the original string.
> String#split returns the original string if no matches are found

- opal/corelib/kernel.rb
I'd like some advice on how to test this as the problem arises only with `require_tree '.'` used at root level.
cc @vais https://github.com/opal/opal-rails/issues/50
> Treat require_tree '.' at root as a special case

- .gitignore
- opal/corelib/hash.rb
- spec/opal/core/hash/has_value_spec.rb
Basically, [here is the link to the demo of this issue](http://opalrb.org/try/?code:h%20%3D%20%7B%20a%3A%201%20%7D%0Aputs%20h.has_key%3F(%3Aa)%0Aputs%20h.has_value%3F(1))
It seems that `Hash#[]=` populates only one of `self.smap` / `self.map` for each key/value pair, but `Hash#has_value?` previously used just a `self.map`. I've already checked other methods - all of them use both `map` and `smap`, so this is the only affected method.
> Fix Hash#has_value? when hash was created through initialize method.

- opal/corelib/method.rb
- opal/corelib/module.rb
- spec/opal/core/method/to_proc_spec.rb
Fix #1007 
Fix #972
Special thanks to @cj for submitting the original issue that broke opal-rspec, and to @Ajedi32 for [pointing me in the right direction](https://github.com/opal/opal/issues/972#issuecomment-120942281).
> Method#to_proc returns a proc that is bound to the method's receiver

- lib/opal/parser/lexer.rb
Fix #992
@adambeynon it would be nice if you could take a look and confirm when you get a chance.
> Fix lexer bug whereby `<<self` in `class <<self` is seen as a heredoc

- lib/opal/sprockets/server.rb
Opal::Server won't work without at least configuring 'main'. This small change makes that clearer.
> raise server exception for unconfigured main asset path

- opal/corelib/array.rb
- opal/corelib/hash.rb
The performance numbers below make this one a difficult sell. But... here's the background. MRI uses helper hashes to implement these `Array` methods, automatically giving them `Hash`-y semantics. In Opal, I hand-coded said `Hash` semantics into the implementation of these methods because at the time `Hash` itself was not fully compliant. Now it is, and having this duplication comes with all the usual "benefits" of code duplication, plus more. RubySpec is awesome, but it is neither perfect nor complete at any point in time. It does specify `Hash` behavior separately from these `Array` behaviors, meaning there is some overlap in spec coverage, but also meaning there can be gaps in both. Having a single code path for these behaviors means that we benefit from all the `Hash` specs and all …
> Make Array #&, #|, #-, #uniq, #uniq! use `Hash` to match MRI semantics

- opal/corelib/kernel.rb
Creating an array out of the range and then choosing a random element is elegant but, as you might imagine, not very performant for wide ranges. :-)
This patch boosts performance of `rand(1...10)` by 8.5x in Safari 9 on my machine.
> Optimize rand with a range

- opal/corelib/hash.rb
`Hash#merge`, being implemented in terms of `Hash#merge!`, doesn't need to worry about coercion or returning the duplicate because those are taken care of in `merge!`, allowing us to simplify this to a single line of code.
> Simplify Hash#merge

- opal/corelib/enumerable.rb
I ran a benchmark that sorts a shuffled array of 50k objects. That
benchmark ran in 1040-1100ms under Safari.
Using JavaScript array indexing inside the sort function instead of Ruby array indexing dropped that number down to about 500-520ms. Mapping and sorting a single additional array (down from 3) reduced the range to 460-480ms.
> Optimize Enumerable#sort_by

- spec/filters/bugs/module.rb
- spec/opal/core/language/class_spec.rb
Ruby specs were available for https://github.com/opal/opal/pull/1078 (commit 35b2a095dd6def54078f1ff57a141470ab62d566), so removing the custom specs that were added and using those
> Correct earlier duplication of RubySpec for class descendants issue

- CHANGELOG.md
- examples/rack/Gemfile.lock
- examples/sinatra/Gemfile.lock
- examples/sinatra/config.ru
- lib/opal/sprockets.rb
- lib/opal/sprockets/server.rb
The example was calling the sprockets asset without debug mode enabled.
fixes #1031
> Fix the sinatra example w/ #javascript_include_tag

- opal/corelib/array.rb
- spec/filters/bugs/array.rb
Based on [rubinius implementation](https://github.com/rubinius/rubinius/blob/master/kernel/common/array.rb#L276).
btw, two specs from rubyspec suite are failing for me locally:
```
Kernel.lambda returns from the to_int itself, not the creation site of the to_int
Module#attr_writer creates a setter for each given attribute name
```
And they were failing before. However on CI everything seems to be fine.
> Fixed recursive array comparison.

- lib/opal/nodes/def.rb
A lot of the optimizations we did before on splat args worked really well to speed things up, but I noticed some more places during profiling that said the VM couldn't optimize certain method calls because it used `Array.prototype.slice.call(arguments, n)` during arg splatting. v8's warning message for it was "bad value context for arguments value", presumably because we were calling an Array prototype function on something that's not technically an array.
This patch replaces the `slice` call with old-school iteration. Here are the benchmarks before and after the patch — they're iteration counts over 5 seconds, so larger is better:
```
Chrome 45
Before:
1 arg : 9,700,318
3 args: 7,923,521
5 args: 8,756,920
After:
1 arg : 18,278,855
3 args: 17,146,539
5 args: 16,672,049
```
```
Safari 9 …
```
> More splat args optimization

- opal/corelib/helpers.rb
- opal/corelib/struct.rb
- spec/filters/bugs/struct.rb
- stdlib/native.rb
Rubyspec says that it should be possible to override `Struct#initialize` and "try" to override attributes:
``` ruby
User = Struct.new(:name) do
def initialize(*)
self.name = 'Name'
super
end
end
User.new.name
```
To make method `user` to not raise error, variable `@data` need to be initialize before `initialize` is invoked.
That's why `Struct#@data` should be:
1. lazily initialized using method `data` (which makes impossible for `Struct` to have an attribute `data`)
2. explicitly initialized every time when we access it
Every object in MRI has some core methods, which makes impossible for `Struct` to have *any* attribute names:
``` ruby
S = Struct.new(:marshal_dump, :marshal_load)
Marshal.load(Marshal.dump(S.new))
```
Can we just rename this 'virtual' method `data` (which actually doesn't …
> Store Struct attributes in hash instead of instance variables.

- spec/filters/bugs/basicobject.rb
- spec/filters/bugs/kernel.rb
- spec/filters/bugs/language.rb
- spec/filters/bugs/module.rb
- spec/filters/unsupported/basicobject.rb
- spec/filters/unsupported/float.rb
The first spec which is related to lambdas is failing because of its dynamic name. Sometimes it's called
```
Kernel.lambda returns from the kind_of? itself, not the creation site of the kind_of?
```
sometimes method name is different. When you run only one spec file containing this test, the method name in the message appears to be blank. This PR should be merged after [this pull](https://github.com/ruby/rubyspec/pull/129) is merged. And anyway, the spec if [failing](http://opalrb.org/try/?code:%24called%20%3D%20false%0A%0Adef%20test%0A%20%20lambda%20%7B%20return%20%7D.call%0A%20%20%24called%20%3D%20true%0Aend%0A%0Atest%0Aputs%20%24called%0A%0A%23%20----%0A%0A%24called%20%3D%20false%0A%0Adef%20test%0A%20%20proc%20%7B%20return%20%7D.call%0A%20%20%24called%20%3D%20true%0Aend%0A%0Atest%0Aputs …
> Add two failing specs to /bugs.

- README.md
I saw that both on http://opalrb.org and on the README, we talk about `opal-parser.js` but there's no docs about how to use it
So I added some *very* basic  instructions on how to user opal-parser on the README just so the user can be aware of that possibility.
> [Docs] Adding instructions on how to use opal-parser.js

- stdlib/pp.rb
* Use $stdout by default, which is closer to what MRI does (they use $<, but that would require more extensive gvars changes)
* Remove the attempt at pretty printing by console.log'ing the object
Tests for this submitted as rubyspec PR https://github.com/ruby/rubyspec/pull/130
Once that makes its way into Opal's submodule, will need to add this to spec/rubyspecs
```
rubyspec/library/pp
```
> Improve PP stdlib defaults

- opal/corelib/struct.rb
- spec/filters/bugs/struct.rb
- spec/filters/unsupported/float.rb
The [spec](https://github.com/ruby/rubyspec/blob/master/core/struct/eql_spec.rb#L8) `Struct#eql? returns false if any corresponding elements are not #eql?` just cannot be implemented because of JS limitations. It automatically typecasts 1.0 to 1 (so they become eql).
> Add support for recursive Struct comparison using #== and #eql?.

- lib/opal/nodes/module.rb
Attempt to fix https://github.com/opal/opal/issues/1110
Tests for this are in https://github.com/ruby/rubyspec/pull/135
> Fix classes defined within anonymous classes

- CHANGELOG.md
- opal/corelib/struct.rb
- spec/filters/bugs/struct.rb
…ime.js so that Number#hash can stay how it is and not make a Ruby method call)
* Change kernel to hash the name, class ID, and object ID using the string hash method
* Since string's hash is not itself anymore, changed pathname to hash its path and keep its specs passing
* Rather than returning a string here, hash the overall result to be consistent with other changes
* Fix struct hash method
> Struct Hash Fixes

- tasks/testing.rake
Without this patch it's impossible to run rubyspecs with some pattern and use filters, e.g. task
```
env RUBYSPECS=true PATTERN="spec/rubyspec/core/array/initialize_spec.rb" bundle exec rake mspec_rubyspec_node
```
was invoking specs that are marked as `failed` or `unsupported`
> Load rubyspecs filters in testing tasks before loading actual specs

- CHANGELOG.md
- lib/opal/nodes/rescue.rb
- opal/corelib/kernel.rb
- opal/corelib/runtime.js
- spec/filters/unsupported/kernel.rb
- spec/rubyspecs
(moved work in https://github.com/opal/opal/pull/1105 to another branch):
This passes all of the raise/fail rubyspecs (except private methods). It comes at a cost though. In order to reset $! after every rescue like MRI does, I had to alter the compiler to make it a stack (JS array).
I realize that may be too much since it adds a try {} finally {} to **every** rescue block. I thought I'd put it out here and see though.
If this can't be done cleanly using my approach or another approach, then I think Opal should explicitly say:
* $! is not a supported global variable
* As a result, you cannot re-raise exceptions by calling 'raise' without parameters
If this **is** acceptable, then:
* I could also use some feedback on how I did the compiler tweaks. I didn't spend much time trying to do it …
> Raise/Fail Exception Rubyspec Compliance

- opal/corelib/error.rb
- spec/opal/core/exception_spec.rb
Have to go back to using @message to retain compatibility, made note and added an Opal test
Fixes problem introduced in https://github.com/opal/opal/pull/1151
> Fix important issue with native exceptions

- opal/corelib/runtime.js
- spec/opal/core/language/class_spec.rb
Issue that was breaking opal-rspec on 0.9
See https://github.com/opal/opal/issues/1154
> Restore ability to call const_set on an anonymous class w/ non object super

- opal/corelib/module.rb
Fixed both `Module#instance_methods` and `Module#to_s`
Rubyspecs that will catch this are:
* https://github.com/ruby/rubyspec/pull/148
* https://github.com/ruby/rubyspec/pull/149
> Fix remnants of is_mod->is_module rename

- opal/corelib/kernel.rb
- spec/opal/core/kernel/raise_spec.rb
If exceptions were raised with just a class name, then undefined got set as the message, which broke the exception class
Fixes issue introduced by earlier PRs.
> Fix 'raise Exception' message case

- opal/corelib/module.rb
- spec/filters/bugs/module.rb
Returns only self when it should, complies with 1 more rubyspec than before
> `Module#ancestors` now works correctly except for singleton classes

- opal/corelib/string.rb
Convert Ruby return to JS return and avoid the returner logic which adds a try {} catch around the entire method
> String#gsub optimization

- opal/corelib/unsupported.rb
Should keep code that calls this from throwing an error
> Private class method, though unsupported, now allows multiple args

- opal/corelib/helpers.rb
- opal/corelib/struct.rb
- spec/filters/bugs/struct.rb
Remove flawed method check that was preventing something? from working with struct
Methods ending in ?, !, etc. are valid but this check did not like them. In addition, it would fail silently, which isn't good. Since it was only used by the struct and was incomplete, I think removing it is the best option. it's probably better to have a built-in check inside define_method anyways
> Remove flawed method check that was causing struct issues

- CHANGELOG.md
- lib/opal/nodes/def.rb
- opal/corelib/hash.rb
- opal/corelib/helpers.rb
- opal/corelib/kernel.rb
- opal/corelib/nil.rb
- opal/corelib/runtime.js
- spec/filters/bugs/kernel.rb
- spec/opal/core/hash/internals_spec.rb
- spec/opal/core/kernel/instance_variables_spec.rb
- stdlib/json.rb
- stdlib/native.rb
Before:
``` ruby
>> nil.instance_variables
=> ["@apply", "@call", "@constructor", "@toString"]
>> {}.instance_variables
=> ["@map", "@keys", "@smap", "@constructor", "@none", "@proc", "@toString"]
>> Class.new.instance_variables
=> ["@constructor", "@toString"]
>> Module.new.instance_variables
=> ["@constructor", "@toString"]
```
After:
``` ruby
>> nil.instance_variables
=> []
>> {}.instance_variables
=> []
>> Class.new.instance_variables
=> []
>> Module.new.instance_variables
=> []
```
> Fix Kernel#instance_variables for Hash and nil

- opal/corelib/kernel.rb
- spec/opal/core/kernel/instance_variables_spec.rb
Makes https://github.com/opal/opal/pull/1186 behavior consistent
Fixes https://github.com/opal/opal/issues/1200
> Ensure cloned objects do not copy ivars that are not returned by #instance_variables

- opal/corelib/runtime.js
I noticed a deoptimization in some of my profiling due to a `try` / `finally` block, which appears to come from [aliased methods](https://github.com/opal/opal/blob/2696a38c64e6b2e84a05e9ebc100bf6e3e651b3a/opal/corelib/runtime.js#L1351-L1358), which causes a deoptimization for that function. The profiler isn't mentioning the slice on `arguments`, probably because it stopped caring why the deoptimization occurred when it saw the try/finally.
This shows up a lot when using `Enumerable` seemingly because I use `map` instead of `collect` everywhere, including some of the hot spots [within Clearwater itself](https://github.com/clearwater-rb/clearwater/blob/master/opal/clearwater/component.rb#L177). But given how many methods on `Enumerable` alone are aliased and how frequently it may be used, …
> Optimize aliasing methods

- opal/corelib/kernel.rb
- opal/corelib/number.rb
Using the class name and id aren't necessary in the hash function since the [Hash redux](https://github.com/opal/opal/pull/1035), which emulates MRI behavior with hash-function collisions.
Below is the change in performance in this PR. `Opal1` is current master. `Opal2` removes class metadata, but coerces `#hash` to a string. `Opal3` foregoes explicit string coercion because JS VMs coerce object property names to strings internally, which is faster. `Ruby1` is MRI 2.2.3p173.
```
Benchmark                                       Opal1   Opal2   Opal3  Ruby1
benchmark/bm_hash_assoc_object.rb               0.568   0.508   0.498  0.011
benchmark/bm_hash_assoc_string.rb               2.062   2.095   2.167  0.010
benchmark/bm_hash_clone_object.rb               2.208   2.151   1.647  0.659 …
```
> Optimize Kernel#hash

- lib/opal/nodes/def.rb
Currently, it's hardcoded in the compiler to use `$slice.call(arguments, 0)`. This PR just does the usual arguments->array copy via iteration while also making the JS code less terrible than I've been doing by declaring that target variable with the rest of the locals. :-)
Results from `rake bench` (from left to right: master, this PR, MRI):
```
test/cruby/benchmark/bm_vm2_zsuper.rb              13.864  1.780   0.547
```
As a bonus, I renamed the index variable for splat args and added a local variable for it. I hadn't intended to commit it but I apparently wasn't paying attention. :-) The only reason I changed it at all was because I originally used `arg_index` in both places, but `Struct.new` uses both splat args and bareword `super` so `var arg_index` in two places within the same …
> Optimize super as a bareword

- opal/corelib/struct.rb
When using methods on a struct, we don't need to check whether the struct has that as a member. If it doesn't we'll be invoking method_missing, not the subscript operator, so we can bypass all that and head straight to the good part.
Additionally, traversing the struct's members as an array is O(n), but checking whether the struct's data object has that key is O(1), so this commit speeds that up, as well.
Results from `rake bench` (from left to right: master, this PR, MRI):
```
test/cruby/benchmark/bm_vm2_struct_big_aref_hi.rb  12.814   0.796   0.261
test/cruby/benchmark/bm_vm2_struct_big_aref_lo.rb   9.565   0.794   0.266
test/cruby/benchmark/bm_vm2_struct_big_aset.rb      9.404   1.224   0.285
test/cruby/benchmark/bm_vm2_struct_small_aref.rb    5.989   0.049   0.190 …
```
> Optimize Struct access

- lib/opal/parser/lexer.rb
- spec/lib/parser/return_spec.rb
The (ludicrously convoluted) Ruby lexer has a number of states, which affect
how various constructs are lexed. There is a state called 'expr_mid', which is
entered after lexing 'return', 'rescue', and a couple of other keywords.
'expr_mid' state is very, very, very, very much like 'expr_beg' state. I still
haven't figured out exactly why it is needed. Anyways, when in expr_mid state,
we should lex %{ just like expr_beg state.
> Fix parsing of `return %{string}`

- lib/opal/nodes/literal.rb
> Fix #1230 (interpolating an empty expr into string)

- lib/opal/parser/lexer.rb
- spec/lib/parser/op_asgn_spec.rb
The correct lexer state was not entered after lexing `|=` and `>>=`. Depending
on what followed after these operators, this could cause the parser to fail.
Fixes #599 and fixes #995.
> Lexer always goes into 'expr_beg' state after lexing an operator-assignment

- lib/opal/nodes/helpers.rb
- opal/corelib/class.rb
- opal/corelib/module.rb
- opal/corelib/runtime.js
- spec/opal/core/kernel/instance_variables_spec.rb
Should improve naming for both sanity when developing and while looking at stack traces.
All constructor should now appear with an "_alloc" suffix in stack traces, although I'm not sure I covered all cases.
> runtime.js cleanup

- opal/corelib/array.rb
- opal/corelib/class.rb
- opal/corelib/module.rb
- opal/corelib/runtime.js
- opal/corelib/string.rb
_**DO NOT MERGE YET** Would like to merge this after 0.9 is out, but maybe I'll cherry-pick single commits before that._
The main idea is to cleanup module and class creation and also improve the debugging experience (e.g. using `displayName`). **`Module.new` is already implemented in terms of `.allocate` + `#initialize`,** and the runtime helper `Opal.module()` uses the same code path. `Class.new` needs more preparatory work tho.
_**Side note:** even if all the functions in the runtime are now all available they're still considered internal, I switched style just to simplify refactoring and reading._
> Deeper runtime cleanup, and beyond

- opal/corelib/runtime.js
- spec/opal/core/module/name_spec.rb
> Fix Module#name when constant was created using Opal.cdecl (constant declare) like ChildClass = Class.new(BaseClass).

- spec/opal/stdlib/native/hash_spec.rb
- stdlib/native.rb
Prior to #1249, `{ foo: MyObject.new }.to_n` returned the object value, but now it returns `nil` if `MyObject#to_n` is not defined. This occurred because of the move to `Native.try_convert` for the conversion (which just lets native JS objects pass through).
I think using that method was a great move, but I don't think `nil` as a return value for arbitrary Ruby objects makes sense. If I understand the intent correctly, the idea is to always return a native JS value. The original Ruby object may be closer to the JS object you want than `nil`. That is, I can think of a lot of ways to use the original Ruby object from JS, but if I get `nil` in JS, I probably actually wanted `null`.
> Return original value if it cannot be nativized

- lib/opal/cli.rb
- lib/opal/cli_runners.rb
- lib/opal/cli_runners/applescript.rb
- lib/opal/cli_runners/nashorn.rb
- lib/opal/cli_runners/nodejs.rb
- lib/opal/cli_runners/phantomjs.rb
- lib/opal/cli_runners/server.rb
This should allow 3rd party to define additional runners. E.g opal-chakra
could implement a runner based on Microsoft Edge JavaScript engine.
Maybe in the future a rack-like `#call` based API and a register of runners
could make sense to allow for super-easy runner definition (e.g. a `Proc`).
I'll merge if the CI is green, any code-review is appreciated though. :)
> Allow for cli-runners extensibility

- CHANGELOG.md
- lib/opal/nodes/base.rb
- lib/opal/nodes/helpers.rb
- lib/opal/nodes/literal.rb
- spec/lib/compiler_spec.rb
- spec/opal/core/runtime/truthy_spec.rb
Rather than using just an operator comparison to decide whether optimization can happen, look at the call type and only optimize operator based calls to ValueNode/NumericNode based types.
Should address https://github.com/opal/opal/issues/1274 in a way that preserves operator optimization (rg_gt, etc.) when possible.
Since no tests broke when I changed this, added compiler specs and also added a spot check at a higher level (opal mspec).
Can squash once approach is reviewed.
> Fix JS Truthy Optimization

- CHANGELOG.md
- lib/opal/nodes/base.rb
- lib/opal/nodes/helpers.rb
- lib/opal/nodes/literal.rb
- spec/lib/compiler_spec.rb
- spec/opal/core/runtime/truthy_spec.rb
Port of https://github.com/opal/opal/pull/1276 to master
Should address #1274 in a way that preserves operator optimization (rg_gt, etc.) when possible.
Rather than using just an operator comparison to decide whether optimization can happen, look at the call type and only optimize operator based calls to ValueNode/NumericNode based types.
> Fix JS Truthy Optimization in Master

- spec/opal/stdlib/promise/always_spec.rb
- spec/opal/stdlib/promise/rescue_spec.rb
- spec/opal/stdlib/promise/then_spec.rb
- spec/opal/stdlib/promise/trace_spec.rb
- stdlib/promise.rb
According to the A+ promise specification, ["`then` may be called multiple times on the same promise"](https://promisesaplus.com/#point-36). Since `fail` and `always` are just `then` with different success/failure semantics, I added the same functionality to them, as well.
@wied03, @meh, and I spoke about supporting this in the past. Last I heard, @meh was still contemplating the change. I probably should've put this in before the 0.9 release, but this PR is backwards-compatible with the current release.
> Allow promises to have multiple then/rescue/always

- CHANGELOG.md
- lib/opal/cli.rb
- lib/opal/cli_options.rb
- spec/lib/cli_spec.rb
@elia I didn't find out how to put the code of the module inside an Opal module... in Asciidoctor.js we're using `Opal::Environment` but this is now deprecated. Maybe it's better to leave as it is (no need to manually require the module) ? Wdyt ?
> Resolves #1281, do not generate source block when module option is specified

- CHANGELOG.md
- lib/opal/cli.rb
- lib/opal/cli_options.rb
- spec/lib/cli_spec.rb
See discussion here: https://github.com/opal/opal/commit/a43acd268f9c10da0e1a1c0f37f0271a5bb55815#commitcomment-15494448
> Rename `module only` option to `library only`

- opal/corelib/file.rb
I've done some tests but `pwd` method is not overridden by the Node.js implementation. I'm pretty sure I'm doing something wrong but I can't figure out what...
To reproduce this issue:
```
$ bundle exec rake dist
$ cat build/nodejs.js >> build/opal.js
$ echo "Opal.require('nodejs');\nconsole.log(Opal.get('File').\$expand_path('.'));" >> build/opal.js
$ node build/opal.js
.
```
Apart from this "issue" (or misuse) this is working as expected and I get the current directory when running Node.js and "." when running in Browser.
fixes #1296
> Resolves #1296, File.expand_path('.') should return the current directory

- lib/opal/nodes/rescue.rb
- spec/opal/core/language/rescue_spec.rb
Prepend rescue statement with js_return when it has ensure.
Fixes #1305.
> Wrap begin;rescue;end into a function when there's a method call on returning value.

- CHANGELOG.md
- opal/corelib/runtime.js
- spec/filters/bugs/module.rb
> Fixed Opal.is_a to use Opal.ancestors of passed object and object's metaclass.

- CHANGELOG.md
- opal/corelib/helpers.rb
- opal/corelib/module.rb
- opal/corelib/struct.rb
- spec/filters/bugs/module.rb
- spec/filters/bugs/struct.rb
- spec/filters/unsupported/struct.rb
There's a difference between `Struct` implementation in opal and MRI:
``` ruby
A = Struct.new(:a, :b)
puts A.new
B = Struct.new('a', :b)
puts B.new
```
For opal:
```
#<struct Struct::A a=nil, b=nil>
#<struct Struct::B a=nil, b=nil>
```
For MRI
```
#<struct A a=nil, b=nil>
test.rb:4:in `new': identifier a needs to be constant (NameError)
```
When the first argument of `Struct.new` is a String, MRI *always* tries to "convert" it to a constant name. In opal we have no difference between `String`/`Symbol`.
> Struct fixes

- CHANGELOG.md
- opal/corelib/file.rb
Hello,
`File.dirname` should return a joined path instead of an array of each directory name.
Before:
~~~~
$ opal -e 'p File.dirname("foo/bar/baz")'
["foo", "bar"]
~~~~
After:
~~~~
$ bundle exec opal -e 'p File.dirname("foo/bar/baz")'
"foo/bar"
~~~~
Thank you,
> `File.dirname` should return a String instead of Array

- CHANGELOG.md
- lib/opal/nodes/masgn.rb
Hello,
Opal fails to compile multiple assignment to constants:
~~~~
opal -e 'A, B = 1, 2'
/home/mame/local/lib/ruby/gems/2.3.0/gems/opal-0.9.2/lib/opal/nodes/masgn.rb:103:in `compile_assignment': An error occurred while compiling: -e (RuntimeError)
Bad child node in masgn LHS: (:cdecl, :A). LHS: (:array, (:cdecl, :A), (:cdecl, :B))
*snip*
~~~~
Though I'm unsure if my patch is right, it fixes this error anyway.  Could you please review it?
> `A, B = 1, 2` does not work

- spec/opal/core/runtime/rescue_spec.rb
On my machine, `bundle exec rake` fails.
~~~
1)
The rescue keyword Fix using more than two "rescue" in sequence #1269 ERROR
NoMethodError: undefined method `<<' for nil
<<: undefined method `<<' for nil
*snip*
~~~
Looks the initialization of $ScratchPad was forgotten.  (I'm unsure why this was overlooked.)
> Initialize $ScratchPad = []

- CHANGELOG.md
- opal/corelib/number.rb
Hello,
`Number#[]` returns a wrong result when it picks a high bit of negative number.
~~~~
$ opal -ve 'p (-1)[1]'
Opal v0.9.2
0
~~~~
It should return 1 because -1 is represented by an integer whose bits are all 1.  Other Ruby implementations including MRI do so.
Thank you,
> `(-1)[1]` should return 1 instead of 0

- README.md
Git submodules need to be initialized before installing dependencies because there's a dependency on mspec path: https://github.com/opal/opal/blob/master/Gemfile#L35
> Initialize submodule before installing dependencies

- CHANGELOG.md
- lib/opal/parser/lexer.rb
Allows to parse the code like:
``` ruby
module_eval(<<'...end ruby23.y/module_eval...', 'ruby23.y', 2771)
def version
23
end
def default_encoding
Encoding::UTF_8
end
...end ruby23.y/module_eval...
```
(Which is required to parse generated parser from https://github.com/whitequark/parser/blob/master/lib/parser/ruby23.y)
Also it covers all cases specified in https://github.com/ruby/spec/blob/ce8d46b35a291bca68d61e552016a03ddfe2cea8/language/string_spec.rb#L134-L177 (unfortunately, there are some other parsing issues, so we still can't include this file into the test suite)
> Fix parsing issues with complex heredoc identifiers.

- stdlib/nodejs/yaml.rb
nodejs/yaml was throwing errors upon usage as it relied on OpalNode.node_require instead of Kernel#node_require like the nodejs/file class.
> Fix nodejs/yaml

- spec/filters/unsupported/string.rb
Exclude encoding related string spec introduced in rubyspec commit ruby/spec@2e3116d41adf1e56c060e0c158a7e48831609291
> Updated ruby specs for super PR

- lib/opal/nodes/def.rb
- lib/opal/nodes/iter.rb
- lib/opal/nodes/scope.rb
- lib/opal/nodes/super.rb
- opal/corelib/module.rb
- opal/corelib/runtime.js
- spec/filters/bugs/language.rb
- spec/lib/compiler/call_spec.rb
Transition error handling to runtime (too difficult and error prone to do it on the compiler side), fix method_missing error handling , case, added missing test cases, DRY find_iter_super_dispatcher
This gets opal-rspec in the neighborhood again
> More super fixes

- lib/opal/parser/lexer.rb
- spec/filters/unsupported/string.rb
- spec/ruby_specs
Fix parsing of control characters.
Added ruby/language/string_spec to the test suite.
Closes #1320.
I don't think this PR deserves an entry in the changelog, nobody uses this syntax :smile: , it's only about extending the test suite.
> Fix parsing of 's = %=string='.

- CHANGELOG.md
- lib/opal/parser/lexer.rb
- spec/filters/unsupported/symbol.rb
- spec/ruby_specs
Added `rubyspec/language/symbol_spec` to the test suite.
Closes #1321
> Fixed parsing of %I{} lists. Fixed parsing of %{} lists when item contains same brackets.

- opal/corelib/runtime.js
With `grand_central`, handling dispatched actions generally relies on heavy usage of `case` statements, which uses `===`, and since `Class#===` depends on `is_a?` and occurs for every single `when`, calculating ancestors becomes a hot path.
Before this PR, `Opal.ancestors` was creating a new array for every tier of inheritance while checking which modules were included. While profiling one of my apps after upgrading Opal, I noticed it was the function with the highest "self" runtime. This patch sped it up by 30-35x for this particular app and reduced memory usage and GC pressure by almost 30%.
The effects of this PR are only this drastic for apps that use `grand_central` and dispatch dozens of times per second. Most apps that don't will likely only see marginal gains in performance.
> Optimize Opal.ancestors

- CHANGELOG.md
- lib/opal/parser/lexer.rb
- spec/opal/core/language/heredoc_spec.rb
Closes #1359.
(Couldn't find any related specs in `spec/ruby`, so I'm like 97% sure that this implementation is correct)
> Add support for "squiggly" heredoc.

- lib/opal/builder.rb
`gsub!` doesn't work in a JavaScript environment. To be able to generate `opal-builder.js`, we need to replace `gsub!` with `gsub`.
Related to #1292
> Replace gsub! with gsub

- CHANGELOG.md
- opal/corelib/runtime.js
- spec/filters/bugs/enumerable.rb
- spec/filters/bugs/language.rb
- spec/filters/unsupported/thread.rb
Fixes #1384. Another weird quirk of the Ruby language (if it's a weird corner, RSpec will find it). It still needs the following:
- Rubyspec built from the anon_mod.rb file *done*
- This is probably incomplete as it really needs to be something that also fixes the Rubyspec `Module#alias_method can call a method with super aliased twice` *save this for another PR*
> Super/Aliasing Fix

- lib/opal/nodes/args/normarg.rb
- spec/opal/core/language/arguments/mlhs_arg_spec.rb
My regression, caused by https://github.com/opal/opal/pull/1395.
Can be easily reproduced with:
``` ruby
[[false], [""], [0]].each { |(a)| p a }
```
> Fixed setting mlhs arg to nil when JS-falsey value is passed.

- CHANGELOG.md
- opal/corelib/array.rb
- opal/corelib/hash.rb
- opal/corelib/marshal.rb
- opal/corelib/marshal/read_buffer.rb
- opal/corelib/marshal/write_buffer.rb
- opal/corelib/module.rb
- opal/corelib/range.rb
- opal/corelib/regexp.rb
- opal/corelib/string.rb
- opal/corelib/string/inheritance.rb
- opal/corelib/struct.rb
- opal/corelib/unsupported.rb
- opal/opal.rb
- opal/opal/full.rb
- spec/filters/bugs/marshal.rb
- spec/filters/unsupported/bignum.rb
- spec/filters/unsupported/marshal.rb
- spec/filters/unsupported/symbol.rb
- spec/opal/core/kernel/instance_variables_spec.rb
- spec/opal/core/marshal/dump_spec.rb
- spec/opal/core/marshal/load_spec.rb
- spec/ruby_specs
- tasks/testing.rake
Things that has been changed to make `Marshal` working:
+ `Array#instance_variables` doesn't return indexes
+ `Module#instance_variables` doesn't return constants
+ `String` subclasses do not return `@literal` in ivars list.
Limitations:
+ `Marshal.dump(:symbol)` - no Symbols support
+ String encoding - dumping/loading a string with custom encoding always dumps/loads utf-16 encoded string
+ Everything about String mutating - extended strings, ivars on strings and so on.
+ `Bignum`'s can't be encoded/decoded
218 examples from rubyspec are passing (`Marshal#restore` is an alias to `Marshal#load`, so probably even 300), ~50 are failing.
> Basic implementation of Marshal.load and Marshal.dump.

- CHANGELOG.md
- opal/corelib/regexp.rb
- spec/filters/bugs/regexp.rb
Ruby specs for this
https://github.com/ruby/spec/pull/227
With that new rubyspec, the (as of yet) unimplemented compile method fails with these reused specs, go ahead and exclude that
> Fix Regexp.new edge case with trailing escaped backslashes

- CHANGELOG.md
- lib/opal/compiler.rb
- spec/filters/bugs/compiler_opal.rb
- spec/lib/compiler_spec.rb
- spec/opal/stdlib/source_map_spec.rb
- spec/support/match_helpers.rb
- spec/support/mspec_rspec_adapter.rb
- stdlib/source_map/vlq.rb
- tasks/testing.rake
The exception started slipping through the rescue in compiler.rb
Ultimately that needs to be fixed (along with validating whether SyntaxError or RuntimeError should be what's raised). For now, make the compiler specs runnable in Opal and filter what does not currently
pass (regex, `__FILE__` issues)
Add matchers to fill in for RSpec, stub out RSpec helper, fix not_to bridge
> Fix compiler error handling for bootstrap case / run compiler specs on Opal

- CHANGELOG.md
- opal/corelib/file.rb
- spec/ruby_specs
Converted the MRI C implementation to JS and pass the Rubyspecs.
> File::dirname and File::basename - RubySpec compliant

- CHANGELOG.md
- spec/filters/bugs/compiler_opal.rb
- stdlib/pathname.rb
Also passes new Rubyspecs for ::new. Underlying implementation of absolute and relative was breaking join.
Rubyspecs - https://github.com/ruby/spec/pull/235
> Fix Pathname.relative/absolute and join

- lib/opal/parser.rb
- lib/opal/parser/grammar.rb
- lib/opal/parser/grammar.y
- spec/filters/bugs/language.rb
- spec/ruby_specs
Add spec/ruby/language/send_spec.rb to the test suite (it contains spec for this bug).
Closes #1369
> Raise an error when both literal block and an object as block are passed to the method call.

- lib/opal/nodes/args/restarg.rb
From what I see locally `ruby/spec` test suite is now 10% faster :smile: 
Closes https://github.com/opal/opal/issues/1343.
> Optimize restarg according to #1096.

- .travis.yml
(can catch some things ruby specs do not test yet).
Also remove the minitest task since all it did was call the CRuby tests.
This way it's more clear in Travis what's going on.
> Enable CRuby tests again

- opal/corelib/enumerable.rb
The Ruby `break` keyword calls `Opal.new_brk`, which is very, very slow. In many cases, there is a much more performant way to do it. In the case of short-circuiting `Enumerable` methods, it's just a matter of returning.
After talking to @wied03 about the performance of `opal-rspec`, I ran a profile of 1k empty specs. It took over 8 seconds:
Well over half of that runtime was spent in `Opal.new_brk`. Considering that profiler run also includes the load time of RSpec into the VM, I figured it might actually be more. Updating the `Enumerable` methods not to use `break` gave that a 4x performance boost:
Improving `Enumerable` performance will have massive effects throughout the entire runtime. For example, compare the [individual build line run times of this …
> Remove breaks from Enumerable methods

- opal/corelib/helpers.rb
- opal/corelib/runtime.js
We optimized splat args in the compiler before, but several places in the runtime still used the same slice idiom, which led to reduced performance in several code paths. This commit cleans up all the others I found.
> Optimize arguments slicing in more places

- lib/opal/nodes/helpers.rb
- lib/opal/nodes/logic.rb
- spec/lib/compiler_spec.rb
- spec/opal/core/runtime/truthy_spec.rb
Previously using null or undefined in an if statement would result
in something like: TypeError: Cannot read property '$$is_boolean'
of undefined.
> Handle null and undefined in if statements

- opal/corelib/array.rb
- opal/corelib/helpers.rb
This allows to make certain assumptions and possibly provide a native
implementation instead of going through the complete call process.
An example is showed for improving `Array#dup` performance.
fixes #1459
> Allow methods to be marked as pristine from corelib

- CHANGELOG.md
- stdlib/opal-builder.rb
- tasks/building.rake
I made some progress toward a 100% JavaScript to compile Ruby code to JavaScript :smile: 
Remaining things to do:
> Resolves #1290, generate opal-builder.js

- opal/corelib/array.rb
- opal/corelib/enumerable.rb
One of the most common uses of `Enumerable#count` is as an alias for `length` or `size`. Without a block or argument, we can short-circuit this to `size`. I also switched out the passing of `arguments` to `Opal.yieldX` so the function could be optimized.
I broke some tests for what looks like the more obscure cases, so I'll need to check into that, but it seems to work for the more common cases.
All benchmarks are iterations/sec after a 100ms warmup. The array has 1000 elements. Higher results are better. I included `Array#size` to show the performance ceiling.
```
array.size
1779658
array.count
4931
array.count(1)
1958
array.count(&:odd?)
480
array.count { |i| i.odd? }
2042
```
```
array.size
1546681
array.count
1471198
array.count(1)
2873
array.count(&:odd?)
464
array.count { |i| i.odd? …
```
> Optimize Enumerable#count

- lib/opal/nodes/scope.rb
- lib/opal/nodes/super.rb
- spec/filters/bugs/switching_to_parser.rb
- spec/lib/compiler/call_spec.rb
Fixes all the call_specs and removed filters for range min/max since those pass now too. By all means do a code review since there might be better ways to do some of this.
Besides the scope.rb change:
* Removed semicolons from call_spec for less brittle specs and to focus more on real failures
* Take advantage of `extract_iter` inheritance from call.rb and utilize that properly for the zsuper case
* zsuper's `@arguments_without_block = []` else clause was not being used anymore since that was all removed, so clean that up
> super fixes for replace-opal-parser branch

- stdlib/native.rb
Currently in 0.9 when using alongside React.rb, component rendering will break and return this error
```js
TypeError: Cannot read property 'constructor' of null
```
This traces back to the Native Hash initialize method
```ruby
def initialize(defaults = undefined, &block)
%x{
if (defaults !== undefined && defaults.constructor === Object) {
```
In the current 0.8, this method checks
```ruby
def initialize(defaults = undefined, &block)
%x{
if (defaults != null) {
if (defaults.constructor === Object) {
```
I'm not sure exactly why it was changed, but changing it to
```ruby
def initialize(defaults = undefined, &block)
%x{
if (defaults !== undefined && defaults != null && defaults.constructor === Object) {
```
appears to fix it and allows me to go on with life.
> Fixes Native Hash initialize to work with React.rb

- stdlib/native.rb
Sending a PR to master with the same fix.
> Fix from 0.9-stable that changes Native Hash initialize check for null

- CHANGELOG.md
- bin/opal
- lib/opal/cli_options.rb
> Fix CLI -L option that was unusable

- opal/corelib/hash.rb
Rather than looking up the ancestor chain with Ruby, might as well utilize the browser's native prototype chain, which is a lot faster.
> Optimize Hash#merge! type check

- lib/opal/compiler.rb
- lib/opal/nodes/definitions.rb
- spec/lib/compiler_spec.rb
- spec/opal/core/language_spec.rb
Reincarnation of https://github.com/opal/opal/pull/1128 :smile: + fix for `alias :dynamic_symbol` + minor refactoring of `Compiler#returns`
Closes #1127
Closes #1128
> Allow passing dynamic symbols to undef/alias.

- opal/corelib/array.rb
If an array is empty, we know `any?` cannot possibly return true. Otherwise, fall back to the `Enumerable` implementation of the method.
This is an optimization made [within MRI](http://ruby-doc.org/core-2.3.1/Array.html#method-i-any-3F) as well. It's functionally correct without it, but this is quite a bit faster for empty arrays since [early method returns within blocks aren't cheap](https://github.com/opal/opal/blob/59e7a48f5b6d62b26a7f4b3c6d284aee751b2c3b/opal/corelib/runtime.js#L1239).
> Optimize Array#any? for an empty array

- docs/rspec.md
Following the docs and couldn't the In a Browser example working without creating a fake env `sprockets_env = Opal::RSpec::SprocketsEnvironment.new` first.
> update browser opal-rspec example

- tasks/testing.rake
Currently tests are sharing a global state `@env`.
Sorting specs files is important to make errors reproducible by everyone.
Ref #1536
> Sort specs files to be consistent

- spec/mspec-opal/runner.rb
- spec/opal/core/kernel/respond_to_spec.rb
- tasks/testing.rake
- tasks/testing/mspec_special_calls.rb
Closes #1536
The idea of this PR is to run every file in a separate environment, so dynamically defined methods will not conflict. This can be achieved using a default MSpec behavior. In fact, this PR doesn't introduce any new mechanism.
+ it uses `MSpec.register_files` to populate MSpec's configuration.
+ it uses `MSpec.files` to run every single file in it's own environment
+ `MSpec.files` dynamically loads every file, which is not allowed by Opal. To make it working added `requirable_spec_file` special call (available only in the MSpec test suite) that explicitly adds passed filepath to compiler's list of required files. By doing this we can automatically inject spec's code to the generated file and require it later (when MSpec needs it).
New `mspec_nodejs.rb` looks like:
``` ruby …
```
> MSpec intergation: run every spec file in a separate environment to avoid potential conflicts.

- stdlib/nodejs/file.rb
- test/nodejs/test_file.rb
Also adds tests for Node.js on File.new and File.mtime
> Resolves #1550, define the default open mode on the File constructor

- docs/compiled_ruby.md
This pull request is for updating compiled code in the document, because the compiled codes in document differ from  real outputs.
I guess it is not updated from old version.
I tried to compile the examples in `docs/compiled_ruby.md` with the latest gem version `0.10.2`.
> docs: Update compiled code with latest gem

- docs/compiled_ruby.md
I see the following contents in `docs/compiled_ruby.md`
in section *Strings & Symbols*
```
<<-EOS            # => "\nHello there.\n"
Hello there.
EOS
```
This code outputs
"Hello there.\n"
> docs: Fix wrong output

- bin/opal-repl
For example, `opal-repl` command exit by following code.
>> foo=
It should catch Exception instead of StandardError.
> Rescue all subtypes of Excepton when eval ruby code in REPL

- opal.gemspec
At least while https://github.com/whitequark/parser/issues/312 is open and unreleased.
> Freeze parser version at 2.3.1.2.

- spec/opal/stdlib/native/hash_spec.rb
- stdlib/native.rb
`native`'s `Hash#new` recursion for arrays didn't Rubify values directly within arrays, only for values of hashes within arrays. This means that the `null` in `{ "a": [null] }` would not be converted to `nil` — it would remain `null`.
Explaining data structures in prose is terrible. The spec changes in the diff are so much more expressive than my description here.
This was actually my bug from when I added this array recursion in the first place.
/cc @catmando
> Properly convert `{"a":[null]}` to {a: [nil]}

- CHANGELOG.md
- spec/opal/stdlib/json/parse_spec.rb
- stdlib/json.rb
JSON.parse and JSON.load raise ParserError when encountering an invalid JSON string.
When JavaScripts native JSON.parse fails, re-raise the SyntaxError as
JSON::ParserError. Class ancestors for ParserError match MRI
implementation.
Fixes #1545
> JSON#parse raises JSON::ParserError on invalid input

- opal/README.md
I found a link to `runtime.js` document broken.
> Fix a link to runtime.js document

- opal/corelib/method.rb
This replaces a function wrapper with a bound version of the same function, which AFAIK inherits optimizations from the original. 
I don't think the fact that the previous version leaked an `arguments` object had much effect on performance in this scenario. Calling `foo(&method(:bar))` only ever executed that function once, so optimization couldn't happen anyway. I think most of the performance difference here is from inheriting previous optimizations.
Benchmark:
``` ruby
Measurement.new('Method#to_proc', &method(:noop))
```
Results in iterations per second:
Safari 10: 3.3M up from 2.26M (46% faster)
Chrome 53: 1.36M up from 925K (47% faster)
Firefox 48: 1.6M up from 483K (231% faster)
> Optimize Method#to_proc

- opal/corelib/file.rb
Ruby MRI:
```ruby
puts File.dirna­me('c:\dev­\playgroun­d\test.ado­c') # "c:\\dev\\playground"
````
Opal:
````javascript
console.log($scope.get('File').$dirname('c:\dev­\playgroun­d\test.ado­c')) // "."
````
In Ruby.c the method isdirsep is checking both Unix separator / and DOS separator \: https://github.com/ruby/ruby/blob/trunk/file.c#L2912
In Opal the method isDirSep is only checking for Unix separator: https://github.com/opal/opal/blob/master/opal/corelib/file.rb#L82
As a result `"c:\dev­\playgroun­d\test.ado­c"` is considered as a filename and not a path. 😢
> Handle DOS path

- README.md
- docs/faq.md
'Rspec' should be a 'RSpec'.
ref: http://rspec.info/
> Fix typos in doc

- spec/lib/compiler_spec.rb
`autoload` expects the Symbol object as the first argument.
> Fix `autoload` usage in compiler spec

- CHANGELOG.md
h2 header of `0.10.3` is duplicated in CHANGELOG. And the removed header is not needed.
Note
------
The following fixes are under 0.10.3 header that is removed.
> ### Fixed
>
> - Newly compliant with the Ruby Spec Suite:
>     * `Module#class_variables`
>     * `Module#class_variable_get`
>     * `Module#class_variable_set`
>     * `Module#remove_class_variable`
>     * `Module#include?`
>     * `Numeric#step` (#1512)
>
> - Improvements for Range class (#1486)
>     * Moved private/tainted/untrusted specs to not supported
>     * Conforming `Range#to_s` and `Range#inspect`
>     * Starting `Range#bsearch` implementation
>     * Simple `Range#step` implementation
>     * Fixing `Range#min` for empty Ranges
>     * Fixing `Range#last(n)` `Range#first(n)` and one edge case of `Range#each`
> …
> Remove duplicate `0.10.3` header in CHANGELOG

- stdlib/nodejs/file.rb
- test/nodejs/test_file.rb
When running Opal in a Node.js environment the following code is not working as expected:
```ruby
def try_read
::File.read("missing") # The file "missing" is missing (obviously), so the code will throw an exception...
rescue IOError
puts "As a result this code will not be executed :'("
end
```
The reason is that Node.js errors (for instance `ENOENT` https://nodejs.org/api/errors.html) are not an instance of Ruby's `IOError`.
> Convert Node.js' IO errors to Ruby's IOError object

- stdlib/strscan.rb
currently, anchor is grabbing `pattern[1..-2]`, which works fine for most regexes, but pukes when you supply one with flags, defeating the entire purpose of it. Instead, we now grab the `source` directly. 
Also, currently the flags are being dropped, this fixes that as well
> correct anchor to get proper regex source and use supplied flags

- stdlib/native.rb
Since global variables aren't accounted for in yard, add some
extra context to the top level `Native` docs.
> Add "$$" context to Native docs

- spec/opal/core/date_spec.rb
- stdlib/date.rb
Current implementation of `Date.parse` doesn't support abbr-month-name with capital-letter.
```ruby
puts Date.parse("2013 jun 02").to_s # "2013-06-02"
puts Date.parse("2013 Jun 02").to_s # "2012-12-02"
```
This PR aims to solve this issue.
> Add abbr-month-name with capital-letter support

- opal/corelib/array.rb
- `Array#initialize` was reassigning function arguments — Ruby default positional args compiles to reassignment of JS function args. This leads to a deoptimization when also using the `arguments` object.
- `Array#-` called `Array#clone` if the other array is empty, which is an expensive operation. It's cheaper to use `JS.Array.prototype.slice`.
> Make a couple optimizations in Array

- opal/corelib/runtime.js
In an effort to reduce startup time (it's only about 60-80ms in Safari on my machine, which is pretty great, but it's nearly 300ms in Chrome), I noticed that `Opal.add_stubs` monopolized CPU time on loading the runtime.
This PR reduces the number of iterations within this function on startup by almost 4x in real-world apps. A Clearwater app was setting almost 11k stubs. With this patch, it was reduced to just over 2800. Since Opal sets up stubs for methods that are either defined or called within a file, it isn't necessary for all subscribers to receive all stubs. I couldn't find any adverse effects of this patch, so I figured I'd send it your way.
Admittedly, it doesn't have a huge effect on startup time, but it does shave off 20-40ms in Chrome. I'm still investigating ways to improve …
> Reduce stub method calls on startup

- opal/corelib/string/encoding.rb
Before: https://jsperf.com/opal-force-encoding-master-3392ee2a
After: https://jsperf.com/opal-force-encoding-master-52c0f3e0
> Returns earlier on force_encoding to improve performance

- lib/opal/path_reader.rb
Especially backslashes!
When running on Windows with Node.js, File::SEPARATOR is equals to `path.sep = '\\'`.
Reference: https://nodejs.org/api/path.html#path_path_sep
Fixes #1630
> Resolves #1630, Escapes meta characters in RegExp

- opal/corelib/number.rb
> Number#=== is called instead of Kernel#=== on switch/case with Numeric

- opal/corelib/number.rb
@meh Second try :wink: 
.benchmark.rb
```ruby
require 'benchmark'
n = 50000
Benchmark.bm do |x|
x.report { for i in 1..n; [1, 2, 3].grep(1); end }
end
```
```
bundle exec opal -- benchmark.rb
```
Before | After
------------ | -------------
`user     system      total        real` | `user     system      total        real`
`0.173000   0.173000   0.691999 (  0.173000)` | `0.112000   0.112000   0.448000 (  0.112000)`
`0.168000   0.168000   0.672000 (  0.168000)` | `0.113000   0.113000   0.452000 (  0.113000)`
`0.170000   0.170000   0.680000 (  0.170000)` | `0.113000   0.113000   0.452000 (  0.112000)`
`0.169000   0.169000   0.676000 (  0.168000)` | `0.113000   0.113000   0.452001 (  0.114000)`
`0.169000   0.169000   0.676000 (  0.169000)` | `0.113000   0.113000   0.452001 (  0.114000)` …
> Resolves #1639, define Number#===

- spec/opal/stdlib/native/hash_spec.rb
- stdlib/native.rb
Since JS objects created with a `null` prototype are essentially a pure bag of keys and values, they should behave the same as JS object literals when given to `Hash.new`.
> Let Hash.new take `Object.create(null)` JS objects

- opal/corelib/class.rb
- opal/corelib/runtime.js
This PR isn't necessarily intended to be merged as is, but it wouldn't be a terrible thing if it were (except for the commented-out code I left in there). The main thing is that I noticed a de-opt in both `Class#new` and the aliased-method wrapper. In both cases, I noticed the block was being assigned directly and that `method.apply` was being used. I happened to notice that that's literally what `Opal.send` does and it somehow avoids a de-opt, so I went ahead and rewrote them in terms of `Opal.send`. Sure enough, no longer deoptimized. I have no idea why.
Running a quick benchmark using the Chrome profiler (a Clearwater app rendering about 2,000 components 25x):
| | `new_body` | `Class#new` |
|-|----|----|
| before | 60.8ms | 77.4ms |
| after | 11.3ms | 7.3ms |
So we're looking at about …
> Optimize Class#new and aliased methods

- Rakefile
Follow-up of https://github.com/opal/opal/commit/9c168a5010210490c9a6fb6a72950ada359421f5
This should fix the build on Appveyor.
> cruby_tests has been renamed to test_cruby

- opal/corelib/runtime.js
The keys variable was defined in the loop but never used. This patch uses it. It also stores the smap in a variable to avoid redundant lookups.
> use keys variable in loop in Opal.hash_clone

- lib/opal/nodes/helpers.rb
- lib/opal/nodes/logic.rb
- opal/corelib/runtime.js
- spec/lib/compiler_spec.rb
Perf on nodejs looks roughly the same (possibly in favor of the helper), probably thanks to JIT.
The core is much more readable and shorter.
I think there are some more places that can be replaced, but I'll wait for an ok from @opal/core.
> Use truth helpers instead of inlining

- opal/corelib/io.rb
`process` object is defined in a Webpack environment but `process.stderr` and `process.stdout` are not.
> Check that process.stderr and process.stdout are defined

- opal/corelib/marshal/read_buffer.rb
- spec/opal/core/marshal/dump_spec.rb
Closes https://github.com/opal/opal/issues/1669
Object cache is not well documented in https://github.com/ruby/ruby/blob/trunk/doc/marshal.rdoc#object-references, however, its behavior can be reverse-engineered:
``` ruby
class A
def initialize
@a = Object.new
@b = Object.new
@c = Object.new
@d = $link
end
def inspect
"#<A:instance @a=#{@a} @b=#{@b} @c=#{@c} @d=#{@d}"
end
end
class Link
end
$link = Link.new
p Marshal.dump([A.new, $link])
```
MRI prints `"\x04\b[\ao:\x06A\t:\a@ao:\vObject\x00:\a@bo;\a\x00:\a@co;\a\x00:\a@do:\tLink\x00@\n"` after running this code. This binary data contains:
+ a list indicator `[`
+ a length of the list `\a` (2)
+ two items, the first is `A.new` that has `$link` inside, the second is an object link to 5th processed object.
We can replace the end to contain …
> Save a link to an object to a Marshal's object cache before processing its instance variables.

- lib/opal/rewriters/base.rb
Also removed old patch, our version of parser includes it.
Closes https://github.com/opal/opal/issues/1673
> Fix base AST rewriter to visit children of Opal-specific jscall, jsattr and jsattrasgn nodes.

- opal/corelib/marshal/write_buffer.rb
- spec/opal/core/marshal/dump_spec.rb
I modified `Marshal.dump` to correspond to a large integer value.
`Marshal.dump(value)` will be overflow when in -0x100000000 > `value` >= 0x100000000
MRI treats the value as `Bignum` in this case.
Opal
```
>> Marshal.dump(0x100000000)
=>"\u0004\bi\u0001\u0000"
```
MRI
```
irb> Marshal.dump(0x100000000)
=> "\x04\bl+\b\x00\x00\x00\x00\x01\x00"
```
> Bignum support for Marshal.dump

- .travis.yml
- lib/opal/cli_runners/applescript.rb
- lib/opal/cli_runners/nashorn.rb
- lib/opal/cli_runners/nodejs.rb
- lib/opal/cli_runners/server.rb
- lib/opal/compiler.rb
- lib/opal/deprecations.rb
- lib/opal/nodes/call.rb
- lib/opal/nodes/node_with_args.rb
- lib/opal/nodes/scope.rb
- lib/opal/nodes/super.rb
- lib/opal/rewriter.rb
- lib/opal/rewriters/binary_operator_assignment.rb
- lib/opal/rewriters/for_rewriter.rb
- lib/opal/rewriters/logical_operator_assignment.rb
- lib/opal/simple_server.rb
- spec/lib/paths_spec.rb
- spec/lib/rewriters/binary_operator_assignment_spec.rb
- spec/lib/rewriters/opal_engine_check_spec.rb
- spec/lib/spec_helper.rb
- tasks/testing.rake
Fixes #1690.
`-w` is a default flag for all tasks running specs on CI and locally.
There are still some warnings:
1. https://github.com/whitequark/parser/issues/360 - reported and looks trivial to fix. Edit: nope, it should be fixed in ragel and doesn't look trivial 😄 
2. rubyspecs suite has some tests for floats like `1e1020`. parser uses `Float('1e1020')` to parse them. Both `ruby -we 'p 1e1020'` and `ruby -we "p Float('1e1020')"` print this warning (this float is actually `Float::INFINITY`). It doesn't look like a ruby version -specific warning, probably it should be silenced in rubyspec. I'll try to fix it.
@lloeki I'm not sure that this PR fixes all warnings from #1690, some of them can be unused in our CI suite.
> Remove warnings

- opal/corelib/file.rb
- test/nodejs/test_dir.rb
- test/nodejs/test_file.rb
```ruby
File.expand_path('spec/share/chapter-01/index.adoc') # c:/dev/asciidoctor.js/spec/share/chapter-01/index.adoc
File.expand_path('spec\node\target\output.html') # c:/dev/asciidoctor.js/spec/node/target/output.html
File.expand_path('./spec/node/target') # c:/dev/asciidoctor.js/spec/node/target
```
Partially resolved: https://github.com/opal/opal/issues/1701
> Adds support for Windows paths on File.expand_path

- lib/opal/ast/builder.rb
- lib/opal/cli.rb
- lib/opal/compiler.rb
- lib/opal/nodes/literal.rb
- lib/opal/parser.rb
- opal/corelib/array.rb
- opal/corelib/marshal/read_buffer.rb
- opal/corelib/runtime.js
- opal/corelib/string/inheritance.rb
- spec/lib/compiler/call_spec.rb
- spec/lib/compiler_spec.rb
- spec/lib/rewriters/binary_operator_assignment_spec.rb
- spec/lib/rewriters/logical_operator_assignment_spec.rb
- spec/opal/core/marshal/dump_spec.rb
- spec/support/rewriters_helper.rb
- tasks/testing.rake
- test/opal/test_base64.rb
``` ruby
'λ'
```
Now compiles to:
``` js
"λ".$force_encoding("ASCII-8BIT")
```
When no magic comment specified all strings are treated as UTF-8 and have no re-encoding.
Also the parser now raises an error for invalid UTF-8 byte sequences like:
``` ruby
"\xFF"
```
or
``` ruby
"\xFF"
```
If you want to make an ascii-string with 255 char, use `encoding` comment and specify any encoding that supports it. You can always check it by running `String#valid_encoding?` method.
Also now we probably can correctly implement `String#bytes` and friends.
Two related modifications:
1. `Object#to_s` now converts its return value from String object to a plain string. [Demo of the bug](http://opalrb.com/try/?code:obj%20%3D%20Object.new%0A%0Adef%20obj.to_s%0A%20%20%22string%22.force_encoding(%27ASCII-8BIT%27)% …
> Use magic encoding comment to encode compiled strings.

- lib/opal/nodes/call.rb
- opal/corelib/string/encoding.rb
- spec/lib/compiler/call_spec.rb
- spec/opal/core/string_spec.rb
- `require_tree` argument was getting the wrong encoding because was being exported by `Pathname`
- Encoding::ASCII has been added as an alias of BINARY
- The whole encoding has been marked as dummy
> ascii encoding fixes

- lib/opal/nodes/args/kwarg.rb
- lib/opal/nodes/args/kwoptarg.rb
- lib/opal/rewriters/js_reserved_words.rb
- spec/lib/rewriters/js_reserved_words_spec.rb
- spec/opal/core/language/keyword_arguments_spec.rb
Before this it was using `deafult$` instead of `default` as kwarg key
> kwargs are not js identifiers

- opal/corelib/regexp.rb
Reference: https://ruby-doc.org/core-2.1.1/Regexp.html#method-i-options
> Resolves #1729, Define constant Regexp::EXTENDED

- opal/corelib/array/pack.rb
- spec/filters/bugs/pack_unpack.rb
- spec/filters/unsupported/taint.rb
- spec/ruby_specs
```
2.4.1 :001 > [49, 50, 51].pack('U*')
=> "123" 
```
```
bundle exec opal -e "require 'corelib/array/pack'; p [49, 50, 51].pack('U*')"  
"123"
```
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint
//cc @iliabylich :wink:
> Implement Array#pack('U')

- CHANGELOG.md
- lib/opal/cli.rb
- lib/opal/cli_options.rb
- lib/opal/cli_runners.rb
- spec/lib/cli_spec.rb
Now runners consist of just an object that can respond to #call and 
return the exit code.
Old runners are still called with the legacy API but rewriting them with
the new one is encouraged.
> Change the CLI runners API to just be callables

- opal/corelib/helpers.rb
Before:
```
$ opal -M -e 'p 42'
/private/var/folders/5r/6fz4187d1rj_67cvnjgcbw0w0000gn/T/opal-nodejs-runner-20180108-5821-szas81:2459
owner_class.$$proto['$'+method_name].$$pristine = true
^
TypeError: Cannot set property '$$pristine' of undefined
```
After:
```
$ opal -M -e 'p 42'
42
```
> Fix $$pristine when method missing is disabled.

- opal/corelib/array.rb
Selfish reasons for doing this, tbh — my script mentioned in #1734 can't parse JS functions correctly without this change because it thinks it's still inside a parenthetical expression — it doesn't know about strings. :-) Adding a closing parenthesis here fixes it.
> Close parentheses in error message

- CHANGELOG.md
- docs/compiled_ruby.md
- opal/corelib/runtime.js
The documentation should read better now
E.g.
```js
Opal.$$.Regexp.$$.IGNORECASE
```
Fixes #1554 cc @camertron @radanskoric
> Add a short $$ helper to navigate constants manually

- CHANGELOG.md
- opal/corelib/unsupported.rb
String are immutable in JavaScript and thus String#prepend cannot be implemented.
The method now throws a "not implemented" exception.
> Add String#prepend to corelib/unsupported

- stdlib/opal-builder.rb
Therefore `opal-builder.js` needs to require 'corelib/string/unpack'
See: https://github.com/whitequark/parser/blob/v2.4.0.2/lib/parser/lexer.rl#L186
> whitequark/parser requires String#unpack

- lib/opal/nodes/def.rb
By they way, `raise` actually doesn't make sense as `case` covers all cases:
```
$ grep 'in_scope' lib -rFn
lib/opal/nodes/scope.rb:62:      def in_scope(&block)
lib/opal/nodes/module.rb:18:        in_scope do
lib/opal/nodes/class.rb:19:        in_scope do
lib/opal/nodes/singleton_class.rb:14:        in_scope do
lib/opal/nodes/top.rb:18:        in_scope do
lib/opal/nodes/def.rb:38:        in_scope do
lib/opal/nodes/iter.rb:23:        in_scope do
```
> Unify Opal.def for :def nodes.

- CHANGELOG.md
- spec/opal/stdlib/native/date_spec.rb
- stdlib/date.rb
I expected Date to have a `to_n` method as it has an obvious JS equivalent, so I added it on @elia's suggestion. Time already has a `to_n` so this seems reasonable.
I grepped the codebase for `def to_n` and they're all in the native.rb file so that's where I put this for consistency.
> Add Date#to_n (in native.rb)

- stdlib/nodejs/file.rb
- remove b flag silently (this already matches how Node reads files)
- detect the encoding option using match?
- use sub instead of gsub to remove encoding option
- only sub if the encoding option is detected
- rename encoding flag to encoding option (per Ruby docs)
> correct and optimize File constructor in nodejs environment

- lib/opal/cli_runners/chrome.rb
Not all distributions use `google-chrome-stable`, Archlinux for example packages `chromium`, which is basically chrom without branding. So let's try other names too so it works out-of-the-box on more systems.
> Try other names for chrome executable on linux

- .rubocop.yml
- opal/corelib/kernel.rb
- opal/corelib/module.rb
- spec/filters/bugs/kernel.rb
- stdlib/e2mmap.rb
- stdlib/matrix.rb
- stdlib/matrix/eigenvalue_decomposition.rb
- stdlib/matrix/lup_decomposition.rb
- tasks/testing.rake
- test/opal/test_matrix.rb
Closes https://github.com/opal/opal/issues/1739
13 assertions of 252 from MRI's spec for Matrix are failing.
Unfortunately I can't find any specs for `Exception2MessageMapper` in MRI or RubySpec, but `Matrix` class heavily uses it and there's a plenty of tests for it in the `TestMatrix`
> Add Matrix and E2MM modules

- CHANGELOG.md
- lib/opal/nodes/constants.rb
- lib/opal/nodes/defined.rb
- lib/opal/nodes/top.rb
- opal/corelib/module.rb
- spec/lib/compiler_spec.rb
Conciseness should improve both readability and perf (less lookups on the `Opal` object).
> Use shorter helpers for constant lookups

- lib/opal/cli_runners/chrome.rb
On Fedora, the name of the Chromium binary is chromium-browser.
> check for chromium-browser binary in chrome cli runner

- spec/opal/stdlib/native/date_spec.rb
For more information - https://github.com/opal/opal/issues/1788#issuecomment-376011523
Closes https://github.com/opal/opal/issues/1788
`Date.prototype.toISOString` relies on the timezone, so sometimes the spec was failing.
`Date.prototype.toDateString` doesn't care about TZ, that's exactly what we need.
> Fix Date#to_n spec.

- opal/corelib/regexp.rb
- spec/opal/core/regexp/match_spec.rb
- use original regexp when pos is not defined
> optimize Regexp#match and Regexp#match? when pos is undefined

- CHANGELOG.md
- opal/corelib/regexp.rb
It's dangerous to blindly replace `.` (dot) with `[\s\S]` in the regexp source. For example, if a dot appears inside a character group (e.g., `[.]`), Opal will cause the regular expression to break.
The onus should be on the library author to use `[\s\S]` in place of `.` when writing multi-line regular expressions as this syntax is already portable between Ruby and JavaScript. Opal should not try to do surgery on the regular expression.
> don't substitute . in regexp source

- spec/opal/stdlib/logger/logger_spec.rb
- spec/ruby_specs
- stdlib/logger.rb
- add StringIO-based Logger implementation w/ default formatter
- enable ruby/library/logger/severity_spec
> resolves #1801 add logger impl to stdlib

- stdlib/nodejs/io.rb
- test/nodejs/test_io.rb
Reverts opal/opal#1824
@elia Or maybe force push HEAD~1 to the master? That's a bad idea if somebody is using Opal directly from the master branch, so I think reverting is better.
> Revert "Implement binread (mimic ASCII-8BIT encoding)"

- opal/corelib/string.rb
with @length generated code tries to assign nil to read only property length, `self.length`works correct
> fix corelib/string

- opal/corelib/unsupported.rb
Closes https://github.com/opal/opal/issues/1805
It may potentially break some tests, so I'd like to get results from the travis.
> Throw a NotImplementedError from the String#[]= method.

- opal/corelib/runtime.js
- spec/opal/core/class/inherited.rb
set const before calling inherited otherwise class.name leads to incorrect results and method_missing depending things misbehave, get called in wrong context
> const_set before inherited

- opal/corelib/runtime.js
- spec/opal/core/runtime/is_a_spec.rb
otherwise `Opal.is_a({}, Opal.Array)` will fail
this was previously automatically guarded by a `while (module) {`
> guard ancestors

- Gemfile
- exe/opal-repl
rubyracer uses a very old version of V8 - https://github.com/cowboyd/therubyracer/blob/master/therubyracer.gemspec#L20 - which doesn't have `Object.setPrototypeOf`
> Switch to mini_racer to support Object.setPrototypeOf in the repl mode.

- CHANGELOG.md
- opal/corelib/kernel.rb
- opal/corelib/runtime.js
- spec/filters/bugs/kernel.rb
- spec/opal/core/kernel/public_methods_spec.rb
`Kernel#public_methods` is a alias of `Kernel#methods` in opal (#909). But their behavior is not same in MRI. This PR fixed it.
Here is an example.
``` ruby
class Child
def foo
"foo"
end
end
c = Child.new
def c.bar
"bar"
end
p c.public_methods(false) #=> [:bar, :foo]
p c.methods(false)        #=> [:foo]
```
`methods(false)` returns only singular methods, but`public_methods(false)` returns singular methods and instance methods.
- [Object#public_methods](https://ruby-doc.org/core-2.5.1/Object.html#method-i-public_methods)
- [Object#methods](https://ruby-doc.org/core-2.5.1/Object.html#method-i-methods)
> Fixed Kernel#public_methods to return instance methods if argument is false

- opal/corelib/array.rb
- opal/corelib/helpers.rb
Fixes #1876 
The check on `$allocate` was done on a stub on the instance instead of the class
> Backport fixes for method_missing_enabled = false

- lib/opal/hike.rb
- lib/opal/path_reader.rb
- opal.gemspec
- spec/lib/path_reader_spec.rb
- tasks/building.rake
- tasks/testing.rake
The version used by Opal is 5 years old and won't reasonably get any 
updates, so it makes sense to make it part of the core codebase.
The first commit embeds the original code in a single file, the second one removes dead code and refactors a bit.
> Embed hike-1.2.3 into Opal

- lib/opal/compiler.rb
- lib/opal/errors.rb
- spec/lib/compiler_spec.rb
Adds the location of the error inside the opal file that's being compiled for a better user experience.
Example:
```
opal:elia/opal-backtrace-for-compilation-errors ⤑ echo '1                                                                              ~/C/opal
2
3
4
5
def {}' > tmp/prova.rb
opal:elia/opal-backtrace-for-compilation-errors ⤑ bin/opal tmp/prova.rb                                                                ~/C/opal
tmp/prova.rb:6:5: error: unexpected token tLCURLY
tmp/prova.rb:6: def {}
tmp/prova.rb:6:     ^ 
Traceback (most recent call last):
22: from bin/opal:4:in `<main>'
21: from bin/opal:4:in `load'
20: from /Users/elia/Code/opal/exe/opal:24:in `<top (required)>'
19: from /Users/elia/Code/opal/lib/opal/cli.rb:66:in `run'
18: from …
```
> Add opal backtrace for compilation errors

- stdlib/nodejs/dir.rb
- stdlib/nodejs/file.rb
- stdlib/nodejs/io.rb
- stdlib/nodejs/kernel.rb
- stdlib/nodejs/open-uri.rb
Static tools should now be able to resolve dependencies.
> Resolves #1883, use require directly instead of the require_node method

- examples/sinatra/Gemfile
- examples/sinatra/Gemfile.lock
- examples/sinatra/config.ru
I tried to run an example Sinatra app but I got a following error.
```sh
$ cd ./opal/examples/sinatra
$ bundle install
$ bundle exec rackup config.ru
DEPRECATION WARNING: `require 'opal/server` and `Opal::Server` are deprecated in favor of `require 'opal/sprockets/server'` and `Opal::Sprockets::Server` (now part of the opal-sprockets gem).
! Unable to load application: LoadError: cannot load such file -- opal/sprockets/server
```
I guess that the example code doesn't catch up to the latest version.
This PR fixes this issue (and I think it also fixes #1830).
> fix: fix broken sinatra example

- opal/corelib/method.rb
- spec/filters/bugs/method.rb
Fixes https://github.com/opal/opal/issues/762
After this:
```
$ bin/opal -Ae 'def foo(a,b,*c);end; p method(:foo).to_proc.parameters'
[["req", "a"], ["req", "b"], ["rest", "c"]]
```
> Pass parameters & arity info from method to proc

- .travis.yml
- Gemfile
- examples/rack/Gemfile.lock
- examples/sinatra/Gemfile.lock
- opal.gemspec
Parser has added support for Ruby 2.3.7, Ruby 2.4.5 and Ruby 2.5.3. Currently the version of Parser that's required by Opal support only up to Ruby 2.4.4, this should take care of that.
See: https://github.com/whitequark/parser/pull/528
Also do note that the latest Opal 0.11.4 still has `spec.add_dependency 'parser', '= 2.3.3.1'` even though the bump to a 2.5.x version was made 8 months ago, and 0.11.4 was released less than a month ago.
> Bump parser to 2.5.3 for Ruby 2.3.8, 2.4.5 and 2.5.3 support

- opal/corelib/marshal.rb
- opal/corelib/marshal/write_buffer.rb
Replace the custom (hackish) class with a simple (hackish) helper function.
This has the advantage of having one less Opal-specific class and avoids the
call to `super` when doing `String#+`.
> Remove Marshal::BinaryString

- bin/setup
- lib/opal/nodes/base.rb
- lib/opal/nodes/class.rb
- lib/opal/nodes/module.rb
- lib/opal/nodes/scope.rb
- lib/opal/nodes/singleton_class.rb
- lib/opal/nodes/super.rb
- opal/corelib/array.rb
- opal/corelib/boolean.rb
- opal/corelib/class.rb
- opal/corelib/enumerator.rb
- opal/corelib/error.rb
- opal/corelib/hash.rb
- opal/corelib/helpers.rb
- opal/corelib/kernel.rb
- opal/corelib/module.rb
- opal/corelib/nil.rb
- opal/corelib/number.rb
- opal/corelib/proc.rb
- opal/corelib/range.rb
- opal/corelib/regexp.rb
- opal/corelib/runtime.js
- opal/corelib/string.rb
- spec/lib/compiler_spec.rb
- spec/opal/core/language_spec.rb
- stdlib/nodejs/stacktrace.rb
Fixes https://github.com/opal/opal/issues/1846
Basically creates class objects for bridged classes instead of using the native constructor.
_I'll refine the commits once the PR is working properly and the solution is confirmed_
> Allocate a class object for bridged classes

- lib/opal/rewriters/logical_operator_assignment.rb
- spec/filters/bugs/language.rb
- spec/lib/rewriters/logical_operator_assignment_spec.rb
This is a special case where the assignment happens if either the constant has
a falsey value or the constant is not yet defined.
Fixes #672
> Fix ||= on constants

- opal/corelib/string.rb
New Ruby spec: https://github.com/ruby/spec/pull/653
Resolves #1902
> chomp must return an empty String when arg == self

- opal/corelib/comparable.rb
- spec/filters/bugs/comparable.rb
When `<=>` raises an exception, `Comparable#==` now lets it go
through.
Also, methods of `Comparable` now raises ArgumentError with a message
more similar to MRI when `<=>` does not return Integer.
```ruby
a = Object.new
a.extend Comparable
def a.<=>(other)
nil
end
a < 1
#=> comparison of Object with Number failed (Opal)
#=> comparison of Object with 1 failed (MRI and Opal with this PR)
```
> Fix methods of `Comparable` when `<=>` does not return Numeric

- spec/opal/stdlib/native/native_alias_spec.rb
- stdlib/native.rb
A typo in the error message generation was raising the same error class we
were expecting, so this error went unnoticed for some time.
> Fix Class#native_alias error message

- opal/corelib/runtime.js
Just a tiny cleanup to add missing semi-colon to terminate statement and remove unnecessary semi-colon.
> Terminate statement with semi-colon and remove unecessary semi-colon

- opal/corelib/string.rb
- spec/filters/bugs/encoding.rb
While working on #1949 I found an issue in the `ascii_only?` implementation.
This implementation is a little less wrong but still failing on:
```rb
"hello".force_encoding("UTF-16LE").ascii_only? # should be false
```
The main issue is that the default encoding in JavaScript is `UTF_16LE` and in Ruby this encoding is considered "non-ASCII-compatible".
Unfortunately Opal can't tell the difference between:
- `"hello".force_encoding("UTF-16LE")`
- `"hello"`
So we cannot return false in the first case and true in the second case... send help!
> Make ascii_only a little less wrong

- UNRELEASED.md
- opal/corelib/struct.rb
- spec/opal/core/struct/dup_spec.rb
Opal raises TypeError when it accesses to duplicated Struct instance.
```ruby
C = Struct.new(:a)
a = C.new(1)
d = a.dup
p a
p d
```
```bash
$ bin/opal test.rb
#<struct C a=1>
/tmp/opal-nodejs-runner-20190713-10833-yax7b8:21715
if(!self.$$data.hasOwnProperty(name)) {
^
TypeError: Cannot read property 'hasOwnProperty' of undefined
at constructor.$Struct_$$$17 (/tmp/opal-nodejs-runner-20190713-10833-yax7b8:21715:25)
at $$26 (/tmp/opal-nodejs-runner-20190713-10833-yax7b8:21871:54)
at Object.Opal.yield1 (/tmp/opal-nodejs-runner-20190713-10833-yax7b8:1452:14)
at Array.$$each (/tmp/opal-nodejs-runner-20190713-10833-yax7b8:12590:26)
at Opal.send (/tmp/opal-nodejs-runner-20190713-10833-yax7b8:1671:19)
at constructor.$$each_pair (/tmp/opal-nodejs-runner-20190713-10833-yax7b8:21864:7)
at …
```
> Fix Struct#dup by copying `$$data` with initialize_copy

- UNRELEASED.md
- lib/opal/cli_runners/nashorn.rb
See also:
- https://github.com/graalvm/graaljs/blob/master/docs/user/NashornMigrationGuide.md#launcher-name-js
- https://medium.com/graalvm/oracle-graalvm-announces-support-for-nashorn-migration-c04810d75c1f
- https://www.graalvm.org/docs/reference-manual/languages/js/
Fixes #1971
> Allow to change Nashorn path if using GraalVM

- lib/opal/cli_runners/applescript.rb
- lib/opal/cli_runners/nashorn.rb
- lib/opal/cli_runners/nodejs.rb
At this moment the current JRuby version is 9.2.8.0, so should be safe
to assume we're good now.
> Remove workaround targeted at JRuby 1.7

- .rubocop.yml
- UNRELEASED.md
- lib/opal/compiler.rb
- lib/opal/magic_comments.rb
- spec/lib/compiler_spec.rb
Will allow access to magic-comments nicely converting them to a hash.
> Add Opal::Compiler#magic_comment_flags

- Gemfile
- UNRELEASED.md
- opal.gemspec
While updating to rails 6:
```
Bundler could not find compatible versions for gem "parser":
In Gemfile:
my_project_a was resolved to 0.9.1, which depends on
opal-rails (~> 1.0) was resolved to 1.0.1, which depends on
opal (~> 1.0.0) was resolved to 1.0.0, which depends on
parser (= 2.5.3.0)
my_project_b was resolved to 0.13.1, which depends on
rubocop (~> 0.74, < 0.75) was resolved to 0.74.0, which depends on
parser (>= 2.6)
```
> Used parser version is incompatible with rubocop

- tasks/benchmarking.rake
This instruction was probably originally in a Rakefile and so it referenced `__dir__` correctly. After moving it to tasks/, the `__dir__` reference changed. This commit corrects the path.
> benchmarking.rake - bench:ips - correct a path to benchmarks

- UNRELEASED.md
- benchmark-ips/class_shovel_vs_singleton_class.rb
- lib/opal/compiler.rb
- lib/opal/nodes/iter.rb
- lib/opal/nodes/literal.rb
- lib/opal/nodes/top.rb
- opal/corelib/runtime.js
- opal/corelib/string.rb
- opal/corelib/string/encoding.rb
- spec/lib/compiler_spec.rb
- spec/opal/core/runtime/string_spec.rb
_Continuing work from #1959_
Strict-mode is now a compiler option that can be enabled via magic comments and will default to `true` in a future version.
Code to set the encoding of a String has been moved to the runtime and used in the compiler as a helper. String literals will now raise FrozenError when trying to set the encoding on them.
> Add per-file "use strict" support

- opal/corelib/runtime.js
Thanks to @Mogztter for [catching](https://github.com/opal/opal/pull/2023#commitcomment-35884301) it 👍
> Typo, was supposed to be "use strict";

- opal/corelib/runtime.js
- spec/opal/core/runtime/main_methods_spec.rb
MRI defines it on the singleton object and makes it a proxy for
Object.define_method. This implementation does not support wrapped
requires.
Fixes #2028
> Allow calling define_method from the top object

- Gemfile
- UNRELEASED.md
- opal.gemspec
> Bump parser to 2.6 for rubocop-support

- opal/corelib/number.rb
Fixing a small mistake which triggered my closure compiler.
Was:
```
>> 8099.round(-1)
=> NaN
>>
``` 
Is:
```
>> 8099.round(-1)
=> 8100
>>
```
> Fix Number#round for Integers

- README.md
The link mistakenly linked to a development branch.
> *tiny fix* README.md: coveralls - switch branch to master

- UNRELEASED.md
- lib/opal/compiler.rb
- lib/opal/magic_comments.rb
- lib/opal/nodes/logic.rb
- lib/opal/nodes/masgn.rb
- lib/opal/nodes/top.rb
- opal/corelib/enumerator.rb
- opal/corelib/proc.rb
- opal/corelib/runtime.js
- opal/corelib/time.rb
- spec/lib/compiler_spec.rb
- spec/lib/source_map/file_spec.rb
- Use magic-comments to require helpers, skip them otherwise (break, slice)
- Reduce the size of the constant getters Opal property name
I attempted to make `nil` into an optional helper, but it's so ubiquitous that I eventually gave up.
> Reduce size of compiled code skipping unused helpers

- lib/opal/builder.rb
- lib/opal/path_reader.rb
When a file is missing and hasn't been stubbed the builder will try to read it anyway instead of relying on the "missing_require_severity" configuration value.
> Fix PathReader when a file is missing

- UNRELEASED.md
- opal/corelib/array.rb
- spec/filters/bugs/array.rb
Match CRuby behavior when exceptions are raised in the block and about
when the array is updated.
Fixes #2067
> Fix Array keep_if, delete_if, reject!, select!

- lib/opal/parser/patch.rb
- spec/opal/compiler/unicode_spec.rb
_backport of #2073_
JavaScript works with UTF-16/UCS-2 and the strings we're passing to
the lexer ar not UTF-8, so the lexer tries to unpack them as 8-bit
chars, messing up the source ranges in which to look for pieces of
code and ultimately shifting all source lookups after having
encountered a unicode string.
E.g.:
```rb
"123️⃣45".unpack('C*').index('5'.unpack('C*').first) # => 10
"123️⃣45".unpack('U*').index('5'.unpack('U*').first) # => 6
```
> Fix parsing unicode on v1.0

- lib/opal/parser/patch.rb
- spec/opal/compiler/unicode_spec.rb
JavaScript works with UTF-16/UCS-2 and the strings we're passing to
the lexer ar not UTF-8, so the lexer tries to unpack them as 8-bit
chars, messing up the source ranges in which to look for pieces of
code and ultimately shifting all source lookups after having
encountered a unicode string.
E.g.:
```rb
"123️⃣45".unpack('C*').index('5'.unpack('C*').first) # => 10
"123️⃣45".unpack('U*').index('5'.unpack('U*').first) # => 6
```
Ref #2066
> Fix parsing unicode chars from Opal

- opal/corelib/kernel.rb
- opal/corelib/number.rb
- opal/corelib/runtime.js
- spec/opal/core/runtime/is_a_spec.rb
After this PR numbers with a decimal part won't be recognized by either `Integer.===` nor `Opal.is_a()`.
> Better integer recognition

- lib/opal/nodes/args/arity_check.rb
- lib/opal/nodes/super.rb
- opal/corelib/array.rb
- opal/corelib/array/pack.rb
- opal/corelib/enumerable.rb
- opal/corelib/enumerator.rb
- opal/corelib/helpers.rb
- opal/corelib/kernel.rb
- opal/corelib/kernel/format.rb
- opal/corelib/math.rb
- opal/corelib/module.rb
- opal/corelib/regexp.rb
- opal/corelib/runtime.js
- opal/corelib/string.rb
Move the most used Opal helpers to the runtime for better performance and to treat them as core (there was some situations in which the helpers were loaded after they were needed).
> Move some Opal helpers to the Runtime

- .overcommit.yml
- bin/setup
Fixed `bin/setup` which fails when overcommit gem is not installed globally.
> Make overcommit avaliable without globally installed one

- opal/corelib/runtime.js
Otherwise I get the following warning message:
```
warning: ignore case doesn't match for "\\/"
```
From line: https://github.com/opal/opal/blob/3c8d93ea8b3ed12b4c49c51cc96d092570c9f64c/stdlib/pathname.rb#L113
> Make sure that ignoreCase is either true or false (not undefined)

- lib/opal/builder_processors.rb
Ensure to probably match multiple extensions so that it doesn't match `.rbenv`
This is a contribution from the [Interscript project](https://github.com/interscript) of [Ribose](https://github.com/riboseinc).
> Fix BuilderProcessors::Processor.handles for rbenv

- lib/opal/cli.rb
- lib/opal/cli_options.rb
- spec/lib/cli_spec.rb
The short rationale behind it is that for now it's impossible to
require opal libraries like opal-browser (close to impossible - it
needs Gem paths) or opal-erubi (impossible, because it needs to
modify the compiler context to support .erubi files).
The longer rationale is that opal-rspec depends on Opal::CLI. We
can't test opal-webassembly due to that.
> Add --rbrequire (-q) option to opal cmdline tool

- .github/workflows/build.yml
- opal/corelib/runtime.js
- opal/corelib/string/encoding.rb
- spec/filters/bugs/encoding.rb
- spec/filters/bugs/kernel.rb
- spec/filters/bugs/string.rb
- spec/opal/core/string_spec.rb
- test/nodejs/test_file.rb
- test/nodejs/test_file_encoding.rb
```js
Buffer.byteLength('foo') // 3
Buffer.byteLength('écrire') // 7
'foo'.$bytesize() // should be 3 not 6
```
I've been able to enable 22 specs :tada: 
Most notably the `String#bytesize` method is now working as expected.
On the other hand, I had to disable 2 specs, one on `String#intern` and another one on `String#to_sym`.
But if you take a closer look, they were working by luck because the value of the `encoding` attribute on String primitive was UTF-16LE.
In fact, the method `String#to_sym` was always returning a UTF-16LE Symbol even when the String was not a UTF-16LE encoded String.
The method `force_encoding` should only update the `encoding` attribute but it should not modify how the string is encoded. As a result, the methods `bytesize` and `each_byte` should not rely on the …
> JavaScript engines are using UTF-16 internally but String are UTF-8 encoded by default

- opal/corelib/string.rb
- spec/opal/core/string/gsub_spec.rb
```
expect("test".gsub(/$/, '2')).to eq "test2"
```
Before this commit it was "2test".
> Fix a zero-length regexp match bug

- Gemfile
- lib/opal/ast/builder.rb
- lib/opal/parser/with_ruby_lexer.rb
- opal.gemspec
- spec/support/rewriters_helper.rb
This is rather an experimental branch to try implementing some Ruby 3.0 features with Opal.
> Change parser to 3.0

- lib/opal/rewriter.rb
- lib/opal/rewriters/numblocks.rb
- spec/opal/core/language/numblocks_spec.rb
This pull request depends on #2148.
This pull request implements a Ruby 2.7 syntax feature of numblocks by transforming an expression of this kind:
```
proc { _1 + _2 }
```
Into an expression of this kind:
```
proc { |_1, _2| _1 + _2 }
```
> Parser 3.0: numblocks support

- CHANGELOG.md
- UNRELEASED.md
- opal/corelib/string/encoding.rb
- spec/filters/bugs/encoding.rb
- spec/filters/bugs/string.rb
> Implement String#getbyte

- opal/corelib/basic_object.rb
MRI defines it on Kernel (as we also do) and not on basic object.
Fixes #2164
> Remove BasicObject#class

- opal/corelib/runtime.js
This is an ancient browser, I know, but it's the basis of many smartphone default browsers.
> Restore compatibility with Chrome 38

- lib/opal/parser/with_c_lexer.rb
The rationale behind this is that we don't have a matching c_lexer for
parser 3.0.0.0 and this warning can be misleading. It isn't code removal,
as we may want to reenable this warning once c_lexer becomes compatible.
> Comment out the "Failed to load WithCLexer, using pure Ruby lexer" warning

- UNRELEASED.md
- opal/corelib/number.rb
- spec/filters/unsupported/float.rb
- spec/filters/unsupported/integer.rb
- spec/filters/unsupported/time.rb
- spec/opal/core/number/to_i_spec.rb
This pull request fixes the behavior of `Number#to_i` to that of `Math.trunc()` of JavaScript.
Before the fix, `Number#to_i` with a huge number in exponential notation returns a small number due to `parseInt()` specification of JavaScript. `parseInt()` converts numbers to strings and then parses it. `parseInt()` doesn't support exponential notation.
If `parseInt()` encounters a character that is not a numeral in the specified radix, it ignores it and all succeeding characters and returns the integer value parsed up to that point.
```ruby
1504642339053716000000.to_s #=> "1.504642339053716e+21"
1504642339053716000000.to_i #=> 1
```
- `Float#<=>`, `Integer#<=>`
-  It compare `Infinity` and `Float::MAX.to_i*2`. `Float::MAX.to_i*2` will be Infinity in Opal
- `Time#yday`
- `with_timezone` …
> Fix Number#to_i with huge number

- UNRELEASED.md
- lib/opal/nodes/args/parameters.rb
- lib/opal/rewriter.rb
- lib/opal/rewriters/forward_args.rb
- spec/filters/bugs/language.rb
- spec/opal/core/language/forward_args_spec.rb
Support 2.7 + 3.0 argument forwarding.
Now instead of:
```
def method_missing(meth, *args, **kwargs, &block)
send(:"do_#{ meth }", *args, **kwargs, &block)
end
```
We will be able to write:
```
def method_missing(meth, ...)
send(:"do_#{ meth }", ...)
end
```
WIP again due to tests not present yet.
> Parser 3.0: Forward arguments support: def a(...); puts(...); end

- lib/opal/nodes/class.rb
- lib/opal/nodes/module.rb
And fix module returning undefined instead of nil at the same time.
Fixes https://github.com/opal/opal/issues/2192
> Let module and class nodes share more code

- opal/corelib/string.rb
- spec/filters/bugs/string.rb
Fix #2197 and pass these test cases.
```
"String#start_with? sets Regexp.last_match if it returns true" # TypeError: no implicit conversion of Regexp into String
"String#start_with? supports regexps with ^ and $ modifiers" # TypeError: no implicit conversion of Regexp into String
"String#start_with? supports regexps" # TypeError: no implicit conversion of Regexp into String
```
> Implement String#start_with with a regexp argument

- lib/opal/rewriters/opal_engine_check.rb
- spec/lib/rewriters/opal_engine_check_spec.rb
The rationale for that is that if/else blocks already share the closure in JS (we don't output `let` variables at this time yet), so nothing is expected to break. Another rationale is that old code produced more code than needed, for example it created an empty
else block even if no else block was present, now the worst case scenario is adding an empty `nil`.
This commit fixes #1965.
> Output less code for opal_engine_check

- spec/lib/rewriters/forward_args_spec.rb
- spec/lib/rewriters/numblocks_spec.rb
I couldn't find time to add those before... I will also now amend the remaining Parser 3.0 series issues to also include some rewriter tests.
> Parser 3.0: Add missing tests for forward_args and numblocks rewriters

- lib/opal/nodes/literal.rb
- opal/corelib/array.rb
- opal/corelib/range.rb
- spec/filters/bugs/language.rb
- spec/filters/bugs/range.rb
- spec/lib/compiler_spec.rb
- spec/opal/core/language/infinite_range_spec.rb
This commit adds support for beginless and endless ranges as in `(..1)` and `(1..)`.
I tried to test it to the best of my abilities, but Ruby specs are quite outdated as of now. So I mark it as a work in progress until those tests are updated.
> Parser 3.0: Support beginless and endless ranges

- spec/opal/core/language/memoization_spec.rb
I found this while running one of my apps against #1653.
Memoization with a begin/end block and an early return seems to be causing something to go wrong. I haven't found what it is, but I was able to reproduce it in a failing spec.
This spec passes on MRI (and on Opal 0.10), but fails on Opal with a NoMethodError. I don't know what part of this fails yet and haven't had time yet to investigate (I doubt it's actually the memoization part, but that was my use case), but I wanted to get it in here because it might break other people's code, as well. I figured you guys are more familiar with the recent compiler changes than I am so something might jump out at you. If not, I can investigate a bit more.
> Failing spec for begin/end with early return that passes on MRI

- opal/corelib/string.rb
- spec/filters/bugs/kernel.rb
- spec/filters/bugs/marshal.rb
- spec/filters/bugs/string.rb
- spec/opal/core/string/subclassing_spec.rb
Allow :encoding option to String costructor
Make sure subclasses call a constructor, with a certain limitation:
```
```
> Rework the String constructor; fixes #2185

- lib/opal/cli_runners/nodejs.rb
Add the content of the `NODE_OPTS` environment variable to the NodeJS' arguments in the node runner. This is notably useful to enable remote debugging while testing:
```
NODE_OPTS=--inspect-brk=0.0.0.0:9993 opal -Itest -Ilib -Ivendored-minitest \
-soptparse -sio/console -stimeout -srubygems -stempfile -smonitor \
-Rnodejs tmp/minitest_node_nodejs.rb
```
The string in `NODE_OPTS` is parsed using `Shellwords` (available in Ruby ≥ 1.8 according to [this SO answer](https://stackoverflow.com/a/6068282/2363712))
> Parse the NODE_OPTS environment variable in the Node runner

- opal/corelib/runtime.js
- spec/opal/core/runtime/bridged_classes_spec.rb
While trying to do #2114 I found this bug that
```ruby
class TestClass < BasicObject.new
end
```
This fails with `Uncaught TypeError: can't convert undefined to object` but it should raise error `TypeError: superclass must be a Class (BasicObject given)` like Ruby does.
Note that `Class.new(BasicObject.new)` works correctly.
In Ruby specs there is test for `Class.new` but not for `class Class < superclass` so they were passing, but I added such test aswell ruby/spec#792
> Fix `class Class < superclass` for invalid superclass

- opal/corelib/runtime.js
- spec/filters/bugs/language.rb
- spec/filters/bugs/module.rb
The former behavior was to create a subclass of String (as
`"::".$$class` is a String), which was incorrect. The same is also
related to modules.
This should fix #1475.
> Fix `class ::String`.

- UNRELEASED.md
- lib/opal/nodes/literal.rb
Currently, the following ruby code is compiled to invalid syntax as a
JavaScript code by Opal.
```ruby
x = /re
/
```
```sh
$ opal test.rb
/tmp/opal-nodejs-runner-20170109-25185-cupfor:20157
return (x = /re
^
SyntaxError: Invalid regular expression: missing /
at Object.exports.runInThisContext (vm.js:78:16)
at Module._compile (module.js:543:28)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.runMain (module.js:605:10)
at run (bootstrap_node.js:420:7)
at startup (bootstrap_node.js:139:9)
at bootstrap_node.js:535:3
$ opal -cO test.rb
/* Generated by Opal 0.11.0.dev */
(function(Opal) {
var self = Opal.top, $scope = Opal, $scopes = [Opal], nil = Opal.nil, $breaker = …
```
> Fixed multiple line Regexp literal to not generate invalid syntax as JavaScript

- opal/corelib/struct.rb
- stdlib/js.rb
- stdlib/nodejs/env.rb
In addition, modify the Struct initializer a little. In my experience,
I have never encountered using this to name a constant, yet this is
the default path. Let's try to create a shortpath.
The main reason for this, though, is that I really struggled with
the browser debugger trying to note all caught exceptions.
Co-authored-by: Elia Schito <elia@schito.me>
> Backport some methods from opal-rspec

- .github/workflows/build.yml
- tasks/testing.rake
- tasks/testing/optimization_status.rb
Co-authored-by: Brady Wied <wied03@users.noreply.github.com>
This fixes #1255
What happens on deoptimization:
- https://github.com/opal/opal/runs/3328310772?check_suite_focus=true
With pull request we check against the branch we apply the pull request for (master most probably).
Otherwise, we check against the previous commit.
Deoptimization failures are not fatal. But they can serve us some idea what went wrong.
> CI: Permissively check for introduced V8 deoptimizations

- lib/opal/builder_processors.rb
- lib/opal/cache.rb
- lib/opal/compiler.rb
- lib/opal/source_map/file.rb
- lib/opal/source_map/map.rb
First, maybe how to use it:
```ruby
OPAL_CACHE=1 bundle exec rake mspec_opal_nodejs
```
I made it an ENV variable for now, not Opal::Config, mainly because there's a plethora of ways to call Opal and almost none of them support those options. This thing only works with Opal::Builder, so it doesn't work with opal-sprockets (but it would be trivial to add if it would be wanted, after all, Sprockets has its own cache - working better or worse).
As we all know, Opal compiles things slowly. So let's take probably the biggest Opal application out there, that is, `bundle exec rake mspec_ruby_nodejs`. So on my computer it takes 1 minute and 20 second (both with cache disabled and with cache full miss). But after cache is populated, it takes 23 seconds, almost a minute less.
Now, HOW does it work, …
> Opal::Cache, an optional compiler cache

- lib/opal/cli_runners/source-map-support-browser.js
- lib/opal/cli_runners/source-map-support-node.js
- lib/opal/cli_runners/source-map-support.js
Before:
```
[user@localhost opal]# bin/opal <<< 'test'
from -:1:1:in `undefined'
from /tmp/opal-system-runner-20210814-752381-bplkgc:25233:3:in `null'
from <js:internal/modules/cjs/loader.js>:1068:30:in `Module._compile'
from <js:internal/modules/cjs/loader.js>:1097:10:in `Module._extensions..js'
from <js:internal/modules/cjs/loader.js>:933:32:in `Module.load'
from <js:internal/modules/cjs/loader.js>:774:14:in `Module._load'
from <js:internal/modules/run_main.js>:72:12:in `executeUserEntryPoint'
```
After:
```
[user@localhost opal]# bin/opal <<< 'test'
-:1:1:in `undefined': undefined method `test' for main (NoMethodError)
from /tmp/opal-system-runner-20210814-753127-xwfdfg:25233:3:in `null'
from <js:internal/modules/cjs/loader.js>:1068:30:in `Module._compile'
from …
```
> Output Exception#full_message on uncaught exceptions

- .jshintrc
- lib/opal/cli_runners.rb
- lib/opal/cli_runners/gjs.rb
- spec/mspec-opal/formatters.rb
- spec/mspec-opal/runner.rb
- stdlib/gjs.rb
- stdlib/gjs/io.rb
- stdlib/gjs/kernel.rb
- stdlib/opal-platform.rb
- stdlib/opal/platform.rb
- tasks/testing.rake
First, what is GJS:
- it's GNOME's JavaScript runtime, available as /usr/bin/gjs in your Linux distribution
- it's based on Mozilla SpiderMonkey
- as it can interface libraries like GLib, Gtk, it can be used to create graphical applications, example: https://github.com/tchx84/flatseal
- it may have a feature parity with Node.js (but API may be a little bit rough, as it is quite... close to the metal)
- it can be used to for example create GNOME Shell plugins
- it's probably not too much cross-platform :D
What this commit does:
- it adds a `gjs` CLI runner
- it adds a ColoredDottedFormatter, by abstracting NodeJSFormatter
- it implements a basic `gjs` opal/platform (stdout, stderr, ARGV, exit)
- it allows to run our tests on `gjs`:
> GJS Runner

- lib/opal/nodes/call.rb
- lib/opal/nodes/iter.rb
- lib/opal/nodes/lambda.rb
- lib/opal/nodes/logic.rb
- lib/opal/nodes/scope.rb
- spec/filters/bugs/kernel.rb
The lambdas are now behaving exactly as they do in Ruby, they work just
like the def in terms of the return logic.
> Support return from lambda (fixes opal#260)

- lib/opal/cache/file_cache.rb
> Compiler cache: Don't error out in multithreaded conditions

- lib/opal/cli.rb
- lib/opal/cli_options.rb
- lib/opal/compiler.rb
- lib/opal/nodes/top.rb
Simply wraps the compiler result as self executing es6 module, mainly intended for Opal::Builder to create a importable opal code bundle
```javascript
// ... lots of opal code ...
// ... final wrap:
/* Generated by Opal 1.2.0 */
export default (function(Opal) {
var self = Opal.top, $nesting = [], nil = Opal.nil, $$$ = Opal.$$$, $$ = Opal.$$;
Opal.add_stubs(['$require']);
self.$require("opal");
return self.$require("opal-builder");
})(Opal);
```
for a example entry file:
```ruby
require 'opal'
require 'opal-builder'
```
Resulting file can be imported like this:
```javascript
import "resulting_file.js";
```
and after that Opal will be available
> Add support for ECMAScript modules with an --esm option

- lib/opal/nodes/args.rb
def fun(_, _) or def fun(_ignore, _ignore)
This is a cherry-pick from #2266
> Allow for multiple underscored args with the same name in strict mode:

- lib/opal/repl.rb
- opal/corelib/boolean.rb
- opal/corelib/class.rb
- opal/corelib/kernel.rb
- opal/corelib/module.rb
- spec/filters/bugs/array.rb
- stdlib/bigdecimal.rb
- stdlib/opal/replutils.rb
Just having some fun with REPL:
```ruby
[user@localhost opal]# bin/opal-repl
>> error
<anonymous>:1434:35:in `constructor.method_missing_stub': undefined method `error' for main (NoMethodError)
from <anonymous>:9:53:in `undefined'
from <anonymous>:10:3:in `undefined'
from <anonymous>:41:11:in `undefined'
>> syntax^^^error
(irb):1:8: error: unexpected token tCARET
(irb):1: syntax^^^error
(irb):1:        ^      
>> if true
..   5
.. end
=> 5
>> `{}`
=> [object Object] => {}
>> ls 123
Comparable#methods: between?  clamp
Numeric#methods: __coerced__  clone  conj  conjugate  div  dup  i  imag  imaginary  polar  pretty_print  pretty_print_cycle  real  real?  rect  rectangular  step  to_c
Number#methods: %  &  *  **  +  +@  -  -@  /  <  <<  <=  <=>  ==  ===  >  >=  >>  []  ^  __id__  abs  abs2 …
```
> Make REPL actually very useful

- spec/filters/bugs/enumerator.rb
- spec/filters/bugs/matrix.rb
- spec/filters/unsupported/freeze.rb
- spec/filters/unsupported/privacy.rb
- spec/ruby_specs
Before:
12043 examples, 0 failures (time taken: 18.075000047683716) (3388 bugs)
After:
12523 examples, 0 failures (time taken: 18.14400005340576) (3555 bugs)
> MSpec: Also test Matrix and Enumerator::{Lazy,Yielder,Generator}

- lib/opal/nodes/literal.rb
- spec/lib/compiler_spec.rb
This includes strings like "\e#{nil}" where "\e" was previously
inspected, which doesn't make sense in JavaScript.
Fixes #2281
> Escape str components in dstrs correctly

- lib/opal/nodes/args/extract_kwrestarg.rb
- lib/opal/nodes/args/extract_restarg.rb
- lib/opal/nodes/def.rb
- lib/opal/nodes/scope.rb
- lib/opal/nodes/super.rb
- lib/opal/rewriters/js_reserved_words.rb
- opal/corelib/array.rb
- spec/filters/bugs/language.rb
`super` keyword's implicit argument is not compliant to MRI.
```ruby
class Parent
def foo(*a)
p a
end
end
class Child < Parent
def foo(a, b = 12, c: 34)
a = 'reassigned'
super
end
end
Child.new.foo(1)
```
This PR resolves this problem.
Fixes #408
> Fix super without explicit arguments

- lib/opal/nodes/call.rb
- opal/corelib/binding.rb
- opal/corelib/proc.rb
- spec/filters/bugs/kernel.rb
The mistake in the previous implementation was that `Proc#binding` was equivalent to `Kernel#binding`. `Proc#binding` returns a binding where a Proc was defined, which is how Ruby works internally to handle scopes. In our case implementing this would cause a performance problem (each block would need to be amended with its binding - which if not performance killing itself, it also involves JS `eval` which isn't what JITs like). So, this is a limited implementation that at least allows you to access block's self via either `my_proc.binding.receiver` or `my_proc.binding.eval('self')` (the second is apparently compatible with earlier Rubies, I saw this code in the wild; we make a shortpath for `'self'` and don't need a parser in this particular case).
This fixes #2340
> Implement Proc#binding correctly

- opal/corelib/regexp.rb
- opal/corelib/string.rb
- spec/opal/core/string/gsub_spec.rb
Allow `String#scan` to be called with a private kwarg `no_matchdata`,
which ensures that `$~` isn't set. Then, ensure that matchdata methods
on searching for named captures use this.
This fixes #2352
> Do not modify `$~` when calling `String#scan` from internal methods

- opal/corelib/runtime.js
- spec/opal/core/language_spec.rb
This commit fixes a regression introduced by 9d3a43d. In runtime,
const_get_name had a check like: `if(cref.$$const[name])` which
broke if the const was `0`.
This fixes #2351
> Stop interpreting falsey values as a missing constant in `Module#const_get`

- .github/workflows/build.yml
This aims to fix the CI for Ruby <3.0.
> Don't lock Bundler version

- opal/corelib/string.rb
- spec/filters/bugs/string.rb
Implement `chomp:` keyword argument for `String#each_line` and `String#lines`.
> Implement `chomp` option for `String#each_line` and `#lines`

- stdlib/nodejs/file.rb
- test/nodejs/test_file.rb
> resolves #2348 preserve UNC path prefix on File#join (Node.js impl)

- bin/opal-mspec
- opal/corelib/file.rb
- opal/corelib/io.rb
- spec/opal/core/kernel/puts_spec.rb
- tasks/testing.rake
An empty `puts` was not writing a newline, now the behavior is 1:1 with CRuby except for recursion management
> Fix io puts

- .rubocop.yml
- lib/opal.rb
- lib/opal/cli.rb
- lib/opal/cli_runners/nodejs.rb
- lib/opal/cli_runners/source-map-support-browser.js
- lib/opal/cli_runners/source-map-support-node.js
- lib/opal/cli_runners/source-map-support.js
- lib/opal/cli_runners/system_runner.rb
- lib/opal/requires.rb
- opal/corelib/error.rb
- opal/corelib/error/errno.rb
- opal/corelib/helpers.rb
- opal/corelib/main.rb
- opal/corelib/runtime.js
- opal/opal.rb
- opal/opal/base.rb
- spec/filters/bugs/exception.rb
- spec/filters/bugs/module.rb
- spec/ruby_specs
- stdlib/nodejs/file.rb
- stdlib/optparse.rb
- stdlib/optparse/ac.rb
- stdlib/optparse/date.rb
- stdlib/optparse/kwargs.rb
- stdlib/optparse/shellwords.rb
- stdlib/optparse/time.rb
- stdlib/optparse/uri.rb
- stdlib/optparse/version.rb
- stdlib/shellwords.rb
- tasks/testing.rake
This works:
```ruby
[user@localhost opal]# bin/opal -s readline -rnodejs -rcorelib/string/unpack -Ilib -popal/cli_runners/compiler exe/opal -- -Oce 'p 5'
warning: Skipping the 'o' Regexp flag as it's not widely supported by JavaScript vendors. -- ./optparse.rb:
warning: Skipping the 'o' Regexp flag as it's not widely supported by JavaScript vendors. -- ./optparse.rb:
warning: Skipping the 'o' Regexp flag as it's not widely supported by JavaScript vendors. -- ./optparse.rb:
warning: Skipping the 'o' Regexp flag as it's not widely supported by JavaScript vendors. -- ./optparse.rb:
warning: Skipping the 'o' Regexp flag as it's not widely supported by JavaScript vendors. -- ./optparse.rb:
warning: Skipping the 'o' Regexp flag as it's not widely supported by JavaScript vendors. -- …
```
> Opal-in-Opal workshop

- lib/opal/nodes/if.rb
- lib/opal/nodes/x_string.rb
- spec/opal/core/language/xstring_spec.rb
Correct a regression that I tried to fix in Opal-Browser with this:
https://github.com/opal/opal-browser/commit/5856297c22c81fcd801432f89218375a30538350
> Fix multiline x-string in a case assignment

- opal/corelib/regexp.rb
- spec/opal/core/regexp/assertions_spec.rb
Opal replaces `\A` and `\z` in regexp literal but it doesn't replace in `Regexp.new`.
https://github.com/opal/opal/blob/178d9cd117444dfd4db6d4f6700b36838a8097d4/lib/opal/nodes/literal.rb#L191
This PR changes to replace `\A` to `^` and `\z` to `$` by `Regexp.new`
> Fix Regexp.new, replace \A to ^ and \z to $

- stdlib/uri.rb
- tasks/testing.rake
- test/opal/test_uri.rb
Adding stdlib module URI, with the implementation of `decode_www_form`.
I didn't manage out to find out how to test (though was an rspec test, but it was running CRuby `uri` instead). Also, implementation omits 2 arguments, because the features may not be implemented in JS (are string encodings a thing in JS?).
Help would be appreciated :)
> added URI.decode_www_form

- opal/corelib/hash.rb
- spec/filters/bugs/hash.rb
Given the following ruby:
```ruby
o = { a: 1, b: 2, c: 3 }
h = o.dup
h.each { |k,v| h.delete(k) }
i = o.dup
i.each_key { |k| i.delete(k) }
puts "o: #{o}\nh: #{h}\ni: #{i}"
```
and executed with matz ruby results in the following expected output:
```
o: {:a=>1, :b=>2, :c=>3}
h: {}
i: {}
```
However, using opal master the following exceptions are thrown (need to comment out the .each ain above code to get the second exception):
```
<internal:corelib/hash.rb>:429:1:in `each': Cannot read properties of undefined (reading '$$is_string') (Exception)
from <internal:corelib/runtime.js>:1900:5:in `Opal.send2'
from <internal:corelib/runtime.js>:1888:5:in `each'
from test.rb:3:2:in `undefined'
from <internal:corelib/runtime.js>:2760:7:in `<main>'
from test.rb:1:1:in `null'
from …
```
> Fix exception during Hash#each and Hash#each_key if keys get deleted during loop

- lib/opal/cache.rb
- lib/opal/compiler.rb
- lib/opal/nodes/top.rb
- lib/opal/parser/default_config.rb
- lib/opal/rewriter.rb
- lib/opal/rewriters/base.rb
- lib/opal/rewriters/rubyspec/filters_rewriter.rb
- spec/lib/cli_spec.rb
- spec/lib/rewriters/base_spec.rb
- spec/lib/rewriters/binary_operator_assignment_spec.rb
- spec/lib/rewriters/block_to_iter_spec.rb
- spec/lib/rewriters/dot_js_syntax_spec.rb
- spec/lib/rewriters/explicit_writer_return_spec.rb
- spec/lib/rewriters/for_rewriter_spec.rb
- spec/lib/rewriters/forward_args_spec.rb
- spec/lib/rewriters/js_reserved_words_spec.rb
- spec/lib/rewriters/logical_operator_assignment_spec.rb
- spec/lib/rewriters/numblocks_spec.rb
- spec/lib/rewriters/opal_engine_check_spec.rb
- spec/lib/rewriters/rubyspec/filters_rewriter_spec.rb
- spec/support/rewriters_helper.rb
Rewriters refactor:
* The :top node is created before rewriting now.
* Allow for a rewriter to mark content as dynamic, bypassing cache
* mspec filters rewriter to mark spec files as dynamic, fixing #2343,
but also in turn requiring specs to be recompiled
Fix and clean up the rewriter specs
> Rewriters refactor

- opal/corelib/number.rb
- spec/filters/bugs/float.rb
This PR implements `Number#prev_float` and `Number#next_float`, which correspond to MRI's `Float#prev_float` and `Float#next_float` respectively.
> Implement Number#prev_float/next_float

- docs/releasing.md
This is so that we clearly denote when we stray off to -dev.
> releasing.md: add a step to prepare for next release

- .eslintrc.js
- opal/corelib/module.rb
- opal/corelib/runtime.js
- spec/opal/core/language/super_spec.rb
- tasks/performance.rake
- tasks/performance/optimization_status.rb
I ended up using `Proxy` and `Reflect` as they're supported everywhere except for explorer and seem to solve the issue pretty well.
Wasn't able to write a test that broke on this, I manually tested by adding paggio to the Gemfile and running:
```
bin/opal --gem paggio -rpaggio -e 'puts Paggio.html! { div.data(test: "test") {div.data(test: "test")} }'
```
---
This reverts commit 787c6065ff6045c57aeb3c98e887c920fb1270c7,
restoring commit 3eacd508eb55daa34198330bf6820579428d845d.
Ref https://github.com/opal/opal/pull/2377
Fixes https://github.com/opal/opal/pull/2379
> Restore "Fix defining multiple methods with the same block"

- lib/opal/ast/matcher.rb
- lib/opal/nodes/if.rb
<s>Basically an experiment to improve opalopal compiler performance and something more perhaps...</s>
This improves deeply nested `case` structures, like in... lexer.
Compared to a tree of else ifs, `switch` is more like a goto, so more
likely to be more performant.
This makes our `ifs` (or `&&`, `||`) to be compiled to either `if`,
ternary, `&&`, `||` or `switch`, making use of all the JS control flow
features.
> Try to compile case statements as switch

- opal/corelib/string.rb
- spec/opal/core/string/to_proc_spec.rb
This fixes #2417
Co-authored-by: Lionel Chauvin <megabigbug@yahoo.fr>
> Correct String#to_proc and method_missing compatibility

- .github/workflows/build.yml
- opal/corelib/time.rb
- spec/spec_helper.rb
- tasks/testing.rake
Fixes #2405
This is more general way than #2406.
> Make `Time.new` not depend on `Date.prototype.getTimezoneOffset()`

- .github/workflows/build.yml
The ryzen runner is currently down, although going back to the GH runner could have more variance, it's worth a try.
> Run performance tests on GitHub actions until ryzen is back

- lib/opal/builder.rb
- lib/opal/cli.rb
- lib/opal/cli_runners/chrome.rb
- lib/opal/cli_runners/gjs.rb
- lib/opal/cli_runners/system_runner.rb
- lib/opal/compiler.rb
- lib/opal/nodes/top.rb
- opal/corelib/runtime.js
* This also fixes a bug which caused CLI options `-r` to not be tracked by loaded_features
* This fixes a bug which caused CLI-generated ESM files to have a double default export
> Add CLI support for ESM, at least for Chrome, NodeJS, QuickJS and GJS

- opal/corelib/string.rb
- opal/corelib/string/encoding.rb
So String#length and String#size definition should be moved from string/encoding.rb (which is not loaded by opal/mini.rb) to string.rb
> String#length should be available when using opal/mini.rb

- lib/opal/cli_runners/chrome.rb
- lib/opal/cli_runners/chrome_cdp_interface.rb
- stdlib/headless_chrome.rb
- stdlib/opal-platform.rb
* We now load a headless chrome platform ONLY if Chrome CLIRunner is being used
* We inhibit a default exit from CDP interface if Kernel#exit hasn't been called (and opal-platform has been loaded)
* We modify Kernel#exit to run a special alert message to communicate with Chrome CDP interface (we would have sent an exception, but it doesn't bubble in the async mess - perhaps it will once we migrate to PromiseV2)
Thanks to Brandon Gastelo for spotting this bug.
Ref: opal-rspec#89
> Chrome CLI Runner to facilitate an async exit.

- lib/opal/builder.rb
- lib/opal/builder_scheduler.rb
- lib/opal/builder_scheduler/prefork.rb
- lib/opal/builder_scheduler/sequential.rb
- lib/opal/cli_runners/mini_racer.rb
- lib/opal/source_map/map.rb
- spec/lib/builder_spec.rb
Well, yes, unfortunately this uses fork, but the architecture is provided so that we can also provide other kinds of multicore builders, like for instance this attempt to use Ractor, or a win32 specific builder (using some win32 equivalent of fork or process spawning - at this time unfortunately I don't have enough win32 experience to say something intelligent).
https://github.com/opal/opal/commit/611a2af66c4ac341e249028bda16021c99d950cc
(Both use a similar approach).
Unfortunately, Ractor is not really suitable for now. In short, I gave up when I found out I would need to patch Ragel:
https://github.com/adrian-thurston/ragel/blob/ragel-6/ragel/rubycodegen.cpp#L100-L104
Such a patch, while possible, (and while it should be done) would require a lot of logistics. Thing is, Ractors are …
> Opal::Builder::Prefork for blazingly fast multicore compilation times

- lib/opal/nodes/scope.rb
delete is expensive, seems like there is no need to delete $$p, setting it to null seems enough
> Improve method block performance 

- lib/opal/nodes/args/ensure_kwargs_are_kwargs.rb
- lib/opal/nodes/args/extract_kwarg.rb
- lib/opal/nodes/args/extract_kwargs.rb
- lib/opal/nodes/args/extract_kwoptarg.rb
- lib/opal/nodes/args/extract_kwrestarg.rb
- lib/opal/nodes/args/extract_optarg.rb
- lib/opal/nodes/args/extract_post_arg.rb
- lib/opal/nodes/args/extract_post_optarg.rb
- lib/opal/nodes/args/extract_restarg.rb
- lib/opal/nodes/args/initialize_iterarg.rb
- lib/opal/nodes/args/initialize_shadowarg.rb
- lib/opal/nodes/args/prepare_post_args.rb
- opal/corelib/runtime.js
Some experiments on uninlining things. I'm curious about the performance benefits from that.
> Uninline non-typical argument handling

- opal/corelib/basic_object.rb
- opal/corelib/runtime.js
- tasks/performance.rake
This pull request includes non-controversial logic changes to runtime.js
> Logic optimization of runtime.js

- lib/opal/builder_scheduler/prefork.rb
If the reactor has finished with error, make the workers exit silently
> Silence prefork

- lib/opal/cache/file_cache.rb
This error shouldn't happen and is likely a bug in Zlib. This is a temporary measure, also for older Rubies, so that tests won't break randomly.
This started happening since we merged Prefork
> Retry if file cache write operation exits with Zlib::BufError

- lib/opal/source_map/file.rb
> Ensure UTF8 encoding of sourcesContent of SourceMaps

- lib/opal/builder.rb
Fix
opal/lib/opal/builder.rb:133:in `map': undefined method `source_map' for nil:NilClass (NoMethodError)
::Opal::SourceMap::Index.new(processed.map(&:source_map), join: "\n")
^^^^
from C:/Users/jan/workspace/opal/lib/opal/builder.rb:133:in `source_map'
from C:/Users/jan/workspace/opal/lib/opal/cli_runners/chrome.rb:67:in `prepare_files_in'
from C:/Users/jan/workspace/opal/lib/opal/cli_runners/chrome.rb:40:in `block (2 levels) in run'
from C:/Users/jan/workspace/opal/lib/opal/cli_runners/chrome.rb:110:in `block in with_chrome_server'
from C:/Users/jan/workspace/opal/lib/opal/cli_runners/chrome.rb:133:in `run_chrome_server'
from C:/Users/jan/workspace/opal/lib/opal/cli_runners/chrome.rb:110:in `with_chrome_server'
from C:/Users/jan/workspace/opal/lib/opal/cli_runners/chrome.rb:39:in `block …
> Fix "undefined method source_map for nil"

- opal/corelib/module.rb
- spec/opal/core/module_spec.rb
This PR fixes running the working branch of Opal-RSpec
> Fix a problem with assigning Module to a constant after freezing

- opal.gemspec
This is being done by forcing the versions of rack and sinatra, so that we don't pull rack 3.0.0 (which moves rackup to a separate gem) mistakenly.
We would like to upgrade this later on, but for now Sinatra does not support rack 3.0
> Fix ruby-head runner

- lib/opal/builder.rb
- lib/opal/builder_scheduler.rb
- spec/lib/builder_spec.rb
Due to us introducing BuilderScheduler, we got a regression for Tilt users where dependency resolution broke.
> Fix builder.dup

- spec/mspec-opal/runner.rb
> bench&runner: Deno: MSpec: use a NodeJS formatter

- opal/corelib/basic_object.rb
- opal/corelib/boolean.rb
- opal/corelib/helpers.rb
- opal/corelib/kernel.rb
- opal/corelib/module.rb
- opal/corelib/runtime.js
- opal/corelib/string.rb
- stdlib/native.rb
`'$'+name` is an expensive call, by caching such calls, we save about 2% in performance.
> Replace all occurences of `'$'+name` with a cached helper

- exe/opal
- lib/opal/cli.rb
- lib/opal/cli_runners/compiler.rb
- Avoid relying on the `OriginalARGV` global var for communication between parts of the project
- Use `File.read` when possible to allow macOS read fresh data from the FS
> Fix CLI file reading for macOS

- tasks/testing.rake
May add `spec/filters/platform/#{platform}/*.rb` files
Will be required by safari runner and #2507
> Platform specific spec filters

- .github/workflows/build.yml
- lib/opal/cli_runners.rb
- lib/opal/cli_runners/safari.rb
- spec/filters/platform/safari/exception.rb
- spec/filters/platform/safari/float.rb
- spec/filters/platform/safari/kernel.rb
- spec/filters/platform/safari/literal_regexp.rb
- spec/mspec-opal/runner.rb
- stdlib/opal-platform.rb
- stdlib/opal/platform.rb
depends on #2512, #2511, #2508, #2506
> Add safari runner, run specs by default on safari, macos

- lib/opal/cli_runners/compiler.rb
A couple of QoL improvements like CTRL-C support and a configuration change that will make Listen not ignore files if they're in a directory named `tmp`.
> Fix `--watch` ignoring some directories (e.g. `tmp`)

- spec/lib/rake_dist_spec.rb
- tasks/building.rake
The small fix from #2489 broke CDN, especially `binding.irb`.
> Fix rake dist (CDN)

- exe/opal
- lib/opal/cli.rb
- spec/lib/cli_spec.rb
- Stop relying on ARGF for switching from file to stdin
- Ensure ARGV is maintained if eval strings are provided
- Ingest the full ARGV and extract the file/stdin/evals internally
> Fix the handling of ARGV for the opal executable

- lib/opal/builder_scheduler/prefork.rb
- lib/opal/cli.rb
- spec/lib/cli_spec.rb
- spec/lib/rake_dist_spec.rb
- spec/lib/spec_helper.rb
Was lacking a spec and was broken during a recent refactoring.
> Fix the `--debug-source-map`

- docs/compiler.md
This PR adds a missing link reference definition and removed an unused one in [docs/compiler](https://opalrb.com/docs/guides/v1.7.1/compiler).
> Fix links in docs/compiler.md

- opal/corelib/runtime.js
- spec/filters/bugs/integer.rb
- spec/filters/bugs/kernel.rb
- spec/filters/bugs/language.rb
Makes `1.singleton_class` or `class << 1; end` raise TypeError instead of Exception.
> Disallow to define a singleton class for Number

- lib/opal/builder_scheduler/prefork.rb
While setting up the Chrome runner for opal-rspec, I came across this error message with the builder:
```
rake aborted!
Encoding::UndefinedConversionError: "\xFD" from ASCII-8BIT to UTF-8
/usr/local/bundle/gems/opal-1.7.2/lib/opal/builder_scheduler/prefork.rb:170:in `write'
/usr/local/bundle/gems/opal-1.7.2/lib/opal/builder_scheduler/prefork.rb:170:in `send_message'
/usr/local/bundle/gems/opal-1.7.2/lib/opal/builder_scheduler/prefork.rb:195:in `send'
/usr/local/bundle/gems/opal-1.7.2/lib/opal/builder_scheduler/prefork.rb:270:in `block (2 levels) in prefork_reactor'
/usr/local/bundle/gems/opal-1.7.2/lib/opal/builder_scheduler/prefork.rb:262:in `each'
/usr/local/bundle/gems/opal-1.7.2/lib/opal/builder_scheduler/prefork.rb:262:in `block in prefork_reactor' …
```
> Enable binmode for IO pipes

- lib/opal/cli_runners/chrome_cdp_interface.rb
- lib/opal/cli_runners/firefox_cdp_interface.rb
These changes should fix the issue with connecting to the chrome runner.
This is the error message:
```
<js:/home/runner/work/opal/opal/lib/opal/cli_runners/node_modules/chrome-remote-interface/lib/chrome.js>:48:23:in `defaultTarget': No inspectable targets (Exception)
from <js:/home/runner/work/opal/opal/lib/opal/cli_runners/node_modules/chrome-remote-interface/lib/chrome.js>:193:28:in `_fetchDebuggerURL'
from node:internal/process/task_queues:95:5:in `processTicksAndRejections'
from <js:/home/runner/work/opal/opal/lib/opal/cli_runners/node_modules/chrome-remote-interface/lib/chrome.js>:140:25:in `_start'
```
I based my changes on this comment from the repo: https://github.com/cyrus-and/chrome-remote-interface/issues/445#issuecomment-761773141
Testing locally, this seems to fix the main …
> Fix Chrome CDP interface connection

- lib/opal/cache/file_cache.rb
which previously returned truthy regardless of the dir being writeable or not, resulting in `dir_writable?(Dir.home, '.cache', 'opal')` being always true, even for non-login user (with $HOME set to /nonexistent)
> Fix for Opal::Cache::FileCache.dir_writable?

- opal/corelib/kernel.rb
- spec/filters/bugs/kernel.rb
Support keyword argument `exception` of `Kernel#.Float`.
RDoc: https://ruby-doc.org/3.2.1/Kernel.html#method-i-Float
> Fix Kernel#.Float with `exception:` option

- opal/corelib/kernel.rb
- spec/filters/bugs/kernel.rb
Support keyword argument `exception` of `Kernel#.Integer`.
RDoc: https://ruby-doc.org/3.2.1/Kernel.html#method-i-Integer
> Fix Kernel#.Integer with `exception:` option

- lib/opal/builder_scheduler/prefork.rb
Due to a rubocop upgrade, there was a warning that made our CI red.
> Rubocop fix

- lib/opal/nodes/literal.rb
- spec/filters/bugs/kernel.rb
There are many syntax errors in RubySpec when ran in reverse, while there shouldn't be (they should be catchable errors) - at least since Node 17.
This fixes #2523
> Regexp: Compile more nodes as $regexp.

- lib/opal/nodes/if.rb
- spec/opal/core/language/case_spec.rb
This manifested itself by parser (if compiled with Opal) dropping a minus sign on integers if there is encoding set (eg. by adding some UTF-8 characters to input).
This fixes #2539
> Fix switch with Object-wrapped values

- opal/corelib/array.rb
This PR improves performance of `Array#intersect?` and `Array#intersection`.
It returns true immediately when first common element is found instead of calculating the whole of intersection.
This is what CRuby (and probably most other implementations) do.
These two intersection method calls give identical results, but former is significantly slow on current master.
```ruby
large_array = (1..10000).to_a
large_array.intersection(large_array, [1]) # slow
large_array.intersection([1], large_array) # fast
```
It is now optimized with this PR.
> Improve performance of Array#intersect? and intersection

- opal/corelib/error.rb
- opal/corelib/runtime.js
- spec/opal/core/runtime/bridged_classes_spec.rb
This commit introduces a function `descends_from_bridged_class(klass)` to check if a class or any of its ancestors is a bridged class. During the allocation of a new class, the `descends_from_bridged_class()` function is now used to determine if the new class is a descendant of a bridged class, and if so, it ensures the original JavaScript constructor is correctly called. This enables more accurate and robust handling of class hierarchies involving bridged classes.
This problem has manifested in Firefox which didn't capture stacktraces for RuntimeError, but did so for StandardError.
This fixes #2540
> Bridging: call original constructor for subclasses of level larger than 1

- lib/opal/builder_scheduler/prefork.rb
Rubocop now does the reverse...
No need to add anything to CHANGELOG.
Reverts opal/opal#2549
> Revert "Rubocop fix"

- opal/corelib/runtime.js
- spec/opal/core/module_spec.rb
How does including/prepending a module work in Opal in short - we create a new JavaScript "class" so to speak, called an `iclass`. We copy the methods from a module to that `iclass` and then we inject that `iclass` into the prototype chain.
Unfortunately, before this commit, if a method was removed from a module, an iclass wouldn't get updated.
This was needed for Flexmock to work under Opal. I believe this will also allow us to make RSpec-Mocks to pass a lot more tests in Opal-RSpec.
I am particularly excited about this fix :D
This PR has been sponsored by Ribose Inc. ref: plurimath/plurimath#159
> iclass: Propagate removal of method from including/prepending modules.

- opal/corelib/regexp.rb
This matches MRI behavior more closely and lets me run one of the libraries that depends on it dropping a Ruby exception.
This PR has been sponsored by Ribose Inc. ref: plurimath/plurimath#159
> Regexp.escape: Cast to String or drop exception.

- benchmark-ips/bm_block_vs_yield.rb
- docs/bridging.md
- docs/getting_started.md
- lib/opal/nodes/call_special.rb
- lib/opal/nodes/if.rb
- lib/opal/rewriters/for_rewriter.rb
- opal/corelib/array.rb
- opal/corelib/hash.rb
- opal/corelib/proc.rb
- opal/corelib/range.rb
- opal/corelib/runtime.js
- spec/filters/bugs/range.rb
- spec/filters/bugs/ruby-32.rb
I will expand the description later on.
> ChatGPT4 experiment for Opal coding

- opal/corelib/runtime.js
This is so that we don't need to capture the stacktrace each time we want to use Ruby semantics of closures.
This should make Asciidoctor work ~15% faster.
Authored by: @merceroncode
> Closure: Generate a JS object, not an Error

- README.md
The "Nebulab" sponsor logo image is broken, use [this](https://github.com/solidusio/solidus/blob/main/README.md?plain=1#L46C13-L46C106) instead.
**Before**
**After**
Check it [here](https://github.com/opal/opal/blob/8c15a3cc24d4b1b7d241723e7abf5636778555fa/README.md#sponsored-contributions)
> Fix "Nebulab" sponsor logo in readme

- lib/opal/simple_server.rb
Lowercase all response headers beause in `rack` 3.0 _response header keys can no longer include uppercase characters._
```
> $ bundle exec rackup
Bundler is using a binstub that was created for a different gem (rackup).
You should run `bundle binstub rack` to work around a system/bundle conflict.
[2023-09-10 15:44:27] INFO  WEBrick 1.8.1
[2023-09-10 15:44:27] INFO  ruby 3.2.2 (2023-03-30) [arm64-darwin22]
[2023-09-10 15:44:27] INFO  WEBrick::HTTPServer#start: pid=16933 port=9292
Rack::Lint::LintError: uppercase character in header name: Content-Type (Rack::Lint::LintError)
/Users/wilson/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/lint.rb:653:in `block in check_headers'
/Users/wilson/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rack-3.0.8/lib/rack/lint.rb:63 …
```
> Lowercase response headers for rack 3.0 compatibility

- README.md
* Removed the duplicated word `will` from the last sentence of `Running tests` section, which's inside `README.md` file.
**Note:** The `README.md` noted above is the one inside Repo Root Folder, On the `master` Branch, which can be view by [clicking here](https://github.com/opal/opal/blob/master/README.md).
*Picture1: A screenshot to provide some context*
> Fix Typo in `Running tests` Section of `README.md` File

- opal/corelib/runtime.js
Fixes #2583, introduced in #2481
Would it be possible for this fix to be back-ported, for a 1.7.4 release?
>  Use a Map instead of a POJO for the jsid_cache

- lib/opal/cli_runners/chrome.rb
This fixes an issue with an upcoming patch to Opal-RSpec. In particular, embedding JSON in a `<script>` tag is not foolproof, as it may contain a string literal containing `</script>` ending the script tag prematurely.
> Chrome runner fix: support code that contains `</script>`

- opal/corelib/runtime.js
I just found a typo and fixed it.
Without this PR, below script gives a different result from CRuby, which seems to be a rare case.
```ruby
class Foo
attr_reader :n
def initialize(n)
@n = n
end
def hash
@n % 10
end
def eql?(other)
@n == other.n
end
end
obj1 = Foo.new(1)
obj2 = Foo.new(11)
obj3 = Foo.new(11)
hash = {}
hash[obj1] = 'obj1'
hash[obj2] = 'obj2'
hash[obj3] = 'obj3'
p hash[obj3]
```
- Result
- CRuby: `"obj3"`
- Opal (master): `"obj2"`
> Fix typo in `Opal.hash_put`

- .eslintrc.js
- opal/corelib/array.rb
- opal/corelib/complex.rb
- opal/corelib/enumerator/arithmetic_sequence.rb
- opal/corelib/hash.rb
- opal/corelib/number.rb
- opal/corelib/range.rb
- opal/corelib/rational.rb
- opal/corelib/runtime.js
- opal/corelib/string.rb
- opal/corelib/struct.rb
- opal/corelib/time.rb
This is a followup to opal/opal#2576. The idea is to ensure that `#hash` return integers, as Ruby does. We use a very lightweight hashing algorithm we have created for this purpose, called `Opal32` which should most of the time return unique values.
> `#hash` now returns integers

- stdlib/promise/v2.rb
- test/opal/promisev2/test_always.rb
Makes PromiseV2 more compatible with PromiseV1
> Pass value in PromiseV2#always just like PromiseV1#always does it

- lib/opal/nodes/closure.rb
- lib/opal/nodes/defined.rb
- lib/opal/nodes/rescue.rb
- opal/corelib/error.rb
- opal/corelib/runtime.js
- spec/filters/bugs/exception.rb
- spec/filters/bugs/language.rb
- spec/filters/bugs/proc.rb
- spec/opal/language/predefined_spec.rb
- spec/opal/language/yield_spec.rb
Orphaned `Proc` objects will throw `LocalJumpError` on return or break.
See https://ruby-doc.org/3.2.2/Proc.html#class-Proc-label-Orphaned+Proc
Some related bugs are fixed too.
> Unexpected return/break should raise LocalJumpError

- lib/opal/nodes/literal.rb
- spec/lib/compiler_spec.rb
`self < foo` will not necessarily return boolean (e.g. `Module#<` may return nil), so we cannot skip `$truthy`.
> Do not skip `$truthy` when lhs is self

- opal/corelib/array.rb
in a few places
Also initialize doesnt need to splice if length is 0, faster
> Improve `Array.push()` performance when pushing many items

- opal/corelib/runtime.js
Reuse the same options object in the $prop helper, this should help performance by reducing object allocation.
> Optimize the `$prop` helper

- opal/corelib/runtime.js
Avoid `Array.prototype.indexOf`, which does linear search.
This improves performance of `Module#instance_methods` and `Object#methods` much.
```console
$ # on master
$ time bin/opal -e '2000.times { String.instance_methods }'
real    0m3.197s
user    0m2.642s
sys     0m0.217s
$ time bin/opal -e '2000.times { "".methods }'
real    0m3.217s
user    0m2.639s
sys     0m0.247s
$ # on this branch
$ time bin/opal -e '2000.times { String.instance_methods }'
real    0m1.367s
user    0m0.995s
sys     0m0.175s
$ time bin/opal -e '2000.times { "".methods }'
real    0m1.371s
user    0m1.039s
sys     0m0.126s
> Optimize `Opal.instance_methods`

- opal/corelib/kernel.rb
- opal/corelib/module.rb
- opal/corelib/proc.rb
- opal/corelib/runtime.js
In particular, this has been found whenever codebase uses freeze a lot, for instance opal compiled by opal.
In addition, this fixes a possible performance problem of codebases that use `instance_variables` method.
> Fix a performance regression introduced by freezing support.

- opal/corelib/string.rb
- spec/opal/core/string_spec.rb
Before this patch, we have noticed that NBSP characters are stripped by those methods which is not what MRI does.
Those methods now fully follow MRI's behavior.
This fixes #2611
This PR has been sponsored by Ribose Inc.
> `String#{r,l,}strip`: Make them work like in MRI

- .eslintrc.await.js
- .eslintrc.js
- lib/opal/version.rb
- opal/corelib/constants.rb
- tasks/linting.rake
This (`next`) is a development branch of 2.0 to which we should direct our pull requests.
As of now, we are in development of Opal 1.8 (`master`), which is meant to be a deprecation-warning release. A rule of thumb is, if you want to break compatibility, you should whenever possible push one pull request to `master` and one to `next` - `master` warns about impending consequences, `next` breaks compatibility.
Another rule of thumb is, that we should provide a way to stay compatible with both versions.
If Opal 2.0 is not ready[define readiness] by the time Opal 1.8 is released, we will start Opal 1.9 development. If it is, we will merge this branch into `master` and focus on preparing the 2.0 release.
This branch is special, as it SHOULD NOT be force-pushed, it will contain occasional …
> [NEXT] Opal 2.0 development branch

- spec/opal/stdlib/native/hash_spec.rb
- stdlib/native.rb
Before we have merged a Hash->Map patchset, `Hash#to_n` used to return a JS object, then it returned Map. `#to_n` is an API of the `native` library, so it is called by the unwrapping part. Let's suppose a sample JS library, that is often called like this inside JS:
```js
combomizer.enhance("feature", { fast: true })
```
This sample is very similar to how Ruby kwargs work, or at least used to, or still work this way in Opal. Such a code was represented in Opal this way:
```ruby
combomizer = Native(`js_combomizer`)
combomizer.enhance("feature", fast: true)
```
Or... without kwargs, the second line becomes:
```ruby
combomizer.enhance("feature", {fast: true})
```
After the Hash->Map patchset, this code has changed its behavior, now passing hash as a Map, which is breaking compatibility …
> Compat regression fix: `Hash#to_n` should return a JS object

- opal/corelib/string/encoding.rb
We had a wrong logic assuming, that low surrogate comes before the high surrogate, while the reverse is true. This caused an errorneus output of `String#chars` function etc. while iterating over character that is over the BMP, that is, has a Unicode codepoint over 0xffff.
This PR has been sponsored by Ribose Inc.
> String#chars: Fix iteration over out-of-BMP characters

- opal/corelib/array.rb
- opal/corelib/hash.rb
I have a use case where Hash#key? computing hashes for a not too large Hash/Array combo takes ~ 3 seconds, for the combination if things going on 10 seconds are wasted.
Using a Map instead of Object.create(null) for $hash_ids seems to reduce that to a 11ms for Hash#key? and the combination ~100ms or so.
Have not tried other use cases or anything else, let see result of the actions ...
> Speed up {Array,Hash}#hash and a couple of Hash operations

- lib/opal/nodes/literal.rb
- opal/corelib/kernel.rb
- opal/corelib/runtime.js
- spec/opal/core/language/string_spec.rb
No longer use `+` for string concatenation and introduce `Opal.interpolate` to handle object stringification.
- Call `Object#to_s` directly, instead of depending on `Object.prototype.toString`.
- Closes #2618
- Fall back to the default `Object#to_s` implementation if `Object#to_s` does not return a string.
- Closes #1068
> Improve string interpolation

- opal/corelib/kernel.rb
- opal/corelib/runtime.js
This patch improves $each_ivar, with positive effects on Up! benchmark results for the env.to_s benchmark:
from 8328.87 req/s to 13105.05 req/s, thats ~50% up. Probably has positive effects on other apps too.
> Improve instance variable performance

- stdlib/nodejs.rb
- stdlib/nodejs/kernel.rb
- stdlib/nodejs/process.rb
Working, it may happen though, that the parent process exits before the child was able to read its javascript file. 
Happens with SystemRunner and its tempfile, which gets deleted when the parent exits. It will fork and then print:
`Error: Cannot find module '/tmp/opal-system-runner20240202-905467-v7fj7d.js'`
In ruby, such situation will still work, because fork relies on the image in memory. In node, the original javascript file is still required when forking.
That of course is not a issue at all, if the parent process keeps running anyway.
This updates the node requires in nodejs/kernel.rb to use the modern form.
> Initial `fork()` support for Node.js

- opal/corelib/object_space.rb
- opal/corelib/string/encoding.rb
- stdlib/deno/file.rb
- stdlib/nodejs/file.rb
I found some cases where JavaScript code was accidentally embeded as a normal string with `%{}`, not `%x{}`.
> Fix several `%{}` which were intended to be `%x{}`

- docs/compiled_ruby.md
- docs/index.md
- docs/js_interface.md
And make it more visible, so that new users could find this information more easily.
Thanks to @AndyObtiva for suggestion.
> Split documentation of Native into a separate document

- docs/directory_mode.md
- lib/opal/builder.rb
- lib/opal/builder/directory.rb
- lib/opal/builder_processors.rb
- lib/opal/cli.rb
- lib/opal/cli_options.rb
- lib/opal/cli_runners/compiler.rb
- lib/opal/cli_runners/mini_racer.rb
- lib/opal/cli_runners/server.rb
- lib/opal/cli_runners/system_runner.rb
- lib/opal/compiler.rb
- lib/opal/config.rb
- lib/opal/nodes/top.rb
- lib/opal/simple_server.rb
- lib/opal/version.rb
- spec/lib/builder_spec.rb
- spec/lib/simple_server_spec.rb
As of now, it only works for the compiler runner and system runner (ie. Node) but nothing prevents us to make it work for other runners in the future as well.
This aims to produce an output that is more easily digestible by modern JS bundlers and that may work better for import maps. This is also a starting point for full ESM support.
This is partially extracted from #2502 (and I intend to split #2502 into some more separate branches, to make it more digestible).
> Implement --directory CLI option

- opal.gemspec
fixing: /usr/local/lib/ruby/gems/3.3.0/bundler/gems/opal-fcb2c903b56f/lib/opal/source_map/map.rb:3: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec.
> Add base64 to gemspec, fixing Warning

- exe/opal-build
`String#untaint` was deprecated in Ruby 2.x and removed in 3.2
> Remove `String#untaint` from exe/opal-build

- opal/corelib/hash.rb
- opal/corelib/runtime.js
- spec/opal/core/hash_spec.rb
For case, where a new Hash is created from self without modifying self there is no need to use the $hash_each helper, self.forEach is sufficient. This avoids creating a extra Array, which is not needed, and thus should benefit memory usage and performance.
Also for #compact and #compact!:
If #compact(!) is called on a Map passed from JS with `null` values, i would expect #compact(!) to remove those too.
So this PR adds a `null` check.
> Hash optimize internal each usage and improve js interoperability

- lib/opal/cli.rb
- lib/opal/cli_options.rb
- lib/opal/nodes/top.rb
- lib/opal/repl.rb
- stdlib/opal-parser.rb
- stdlib/opal-replutils.rb
Taken from my platform work.
Use case: Conditional dynamic import() of platform specific modules directly after runtime.js and before corelib ruby parts.
Lets see what specs say ...
> Enable async Opal startup and REPL, use correct REPL runner

- examples/exe/create_apps.sh
- examples/exe/simple.rb
- lib/opal/cli.rb
- lib/opal/cli_options.rb
- lib/opal/exe_compiler.rb
Ill expand on the example and docs after my platform work.
Also apps of type osa currently crash most probably, because osascript requires some platform work. Well, depends on what you do. The simple example should work.
> Let opal build standalone applications via the --compile-to-exe option

- .rubocop.yml
- lib/opal/nodes/if.rb
After introducing a threadsafe fix, opalopal users got a regression. Let's require `thread` for those users from now on.
> nodes/if: Require Thread shim

- eslint.config.mjs
Just leverage existing presets instead of explicitly listing constants.
> Use ESLint ECMA script defaults

- lib/opal/rewriters/opal_engine_check.rb
- spec/lib/rewriters/opal_engine_check_spec.rb
While this does not fix every engine check in existence, it drops fragments intended for a different engine.
> opal_engine_check: handle expressions like `if RUBY_ENGINE == "jruby"`

- opal/corelib/unsupported.rb
This is so that certain software will not fail when this method is not present.
> corelib/unsupported: add Module#deprecate_constant

- lib/opal/nodes/class.rb
- lib/opal/nodes/module.rb
- opal/corelib/trace_point.rb
- opal/runtime/class.rb
- opal/runtime/module.rb
- tasks/testing.rake
- test/nodejs/test_tracepoint_end.rb
This PR wraps the class/module definition in a new $class_def/$module_def helpers. This allowed us to save a couple of lines of generated code and allowed us to introduce TracePoint :end support. Those events should fire when a class/module definition reaches its `end`, similarly to :class, which fires events when class/module definition begins.
This PR is sponsored by Ribose Inc.
> compiler: class/module nodes rework; tracepoint :end support
