opal/opal

CHANGELOG.md, opal/corelib/module.rb, spec/filters/bugs/module.rb, spec/rubyspecs
=> Module#const_get accepts a scoped constant name

CHANGELOG.md, opal/corelib/string.rb, spec/filters/bugs/string.rb
=> String#succ and String#next implementation fully compliant with rubyspec

lib/opal/compiler.rb, lib/opal/sprockets/processor.rb, lib/opal/sprockets/server.rb, lib/opal/sprockets/source_map_header_patch.rb, lib/opal/sprockets/source_map_server.rb, spec/lib/sprockets/processor_spec.rb, spec/lib/sprockets/server_spec.rb
rel: https://github.com/opal/opal-rails/pull/43
=> Back to sprockets ✨

CONTRIBUTING.md
Re: https://github.com/opal/opal/pull/779#issuecomment-87287434
=> Updated CONTRIBUTING.md to help people get started

CONTRIBUTING.md
Re: https://github.com/opal/opal/pull/783#issuecomment-88117012
=> Added info on using "opal-repl" and "opal -e"

CHANGELOG.md, lib/opal/version.rb, opal/corelib/variables.rb
=> Bump version to 0.7.2 to correct RUBY_ENGINE_VERSION

opal/corelib/string.rb, spec/filters/bugs/string.rb, spec/filters/unsupported/regular_expressions.rb, spec/filters/unsupported/tainted.rb, spec/rubyspecs
=> Fix String#scan, make #gsub, #rindex, #rpartition multiline by default

opal/corelib/regexp.rb
Once this PR is merged:
1. Close issue https://github.com/opal/opal/issues/641
2. Close PR https://github.com/opal/opal/pull/642 without merging
=> Make Regexp#=== set global match data vars

lib/opal/nodes/iter.rb
=> Fix #844 - compiling block arguments creates global variables

README.md
```
<fkchang> jeremyevans: it seems that https://gitter.im/opal/opal get's a lot
more chat love than irc these days, I'd bring your tilt discussion
there                                                         [15:43]
<jeremyevans> fkchang: Thanks                                           [15:48]
<jeremyevans> Maybe the README could use an update                      [15:49]
```
=> Update README to mention gitter per this interaction on IRC

opal/corelib/array.rb, spec/filters/bugs/array.rb
=> Fix issue #871

opal/corelib/array.rb
Cleaning up implementation based on feedback on #917
=> Refactoring Array#permutation's implementation to use js over rb

lib/opal/parser/lexer.rb, spec/lib/parser/not_spec.rb
This fixes https://github.com/opal/opal/issues/882.
=> Fixed regex for matching identifiers

CODE_OF_CONDUCT.md
This is the URL fix and the ethnicity addition, bundled together since I don't think either of these changes are remotely controversial.
@adambeynon @sarciszewski @jaen @webmaven thoughts if you have any, please
@adambeynon merge when ready please
=> Coc tweaks - URL and ethnicity

opal/corelib/time.rb, spec/filters/unsupported/time.rb
Re https://github.com/opal/opal/issues/963
=> Time#hash returns a String

opal/corelib/basic_object.rb, spec/filters/unsupported/basicobject.rb
=> Implement BasicObject#!=

lib/opal/nodes/if.rb, lib/opal/parser/grammar.rb, lib/opal/parser/grammar.y, opal/corelib/basic_object.rb, spec/lib/parser/not_spec.rb
Fix #970 (for realz this time?)
=> Compile `!=` expression to a single method call instead of `==` + `!`

opal/corelib/boolean.rb, spec/filters/unsupported/kernel.rb
=> Add Boolean#eql?

examples/rack/config.ru
=> some explanations added, using the index too

opal/corelib/enumerator.rb
=> Fix #1034 (Enumerator#with_index does not return value)

lib/opal/builder_processors.rb, lib/opal/nodes/def.rb, lib/opal/nodes/definitions.rb, lib/opal/sprockets/processor.rb, opal/corelib/array.rb, opal/corelib/boolean.rb, opal/corelib/class.rb, opal/corelib/error.rb, opal/corelib/helpers.rb, opal/corelib/kernel.rb, opal/corelib/module.rb, opal/corelib/numeric.rb, opal/corelib/proc.rb, opal/corelib/regexp.rb, opal/corelib/runtime.js, opal/corelib/string.rb, opal/corelib/time.rb
It's basically done par a not false-positive in the specs.
I want some eyes on it since it's a pretty big change, if I've done everything right it will allow proper `Numeric` semantics.
/cc @opal/owners 
fixes #313
=> Refactor bridging and method definition.

opal/corelib/module.rb, spec/opal/core/language/class_spec.rb
https://github.com/opal/opal/issues/1077
=> Fix class descendant issue

README.md
WIP, waiting for feedback from @shevegen re #1043
=> Improve the usage section of the readme

.travis.yml
`SUITE=stdlib rake jshint` requires it
=> Add UglifyJS installation to travis build.

spec/rubyspecs
Promised rubyspecs for https://github.com/opal/opal/pull/1104
=> Update to latest rubyspecs and include PP ruby spec for 7bd7884

README.md, docs/configuring_gems.md, docs/opal_parser.md, opal/corelib/unsupported.rb
please check for typos and better wording (even after it's merged!)
cc @orionz @vais @Ajedi32 @dancinglightning @peter-leonov
fixes #230
=> Add documentation for opal-parser (including Opal.eval)

lib/opal/nodes/logic.rb
Fixes https://github.com/opal/opal/issues/1090 with a compiler fix and update to latest rubyspecs
=> Make return value from local_var &&/and something consistent

spec/opal/stdlib/native/hash_spec.rb, stdlib/native.rb
=> Make JS object->Hash conversion traverse arrays

lib/opal/parser/grammar.rb, lib/opal/parser/grammar.y, opal/corelib/kernel.rb, spec/lib/parser/not_spec.rb
=> Make !~ be a real method defined in kernel

lib/opal/nodes/call.rb, spec/opal/core/runtime/method_missing_spec.rb
fixes #1137
fixes #1121
closes #1136 - @wied03 noticed the PR just after I fixed the issue locally, sorry! 😓
=> Allow method_missing to receive operators

lib/mspec/opal/runner.rb, opal/corelib/time.rb, spec/filters/bugs/time.rb
=> Fix Time#yday

CHANGELOG.md, opal/corelib/basic_object.rb, opal/corelib/runtime.js, opal/corelib/struct.rb
Should allow defining class methods properly in blocks
Rubyspecs PR - https://github.com/ruby/rubyspec/pull/150
=> Handle instance_eval/exec on class/modules

spec/filters/bugs/language.rb, spec/filters/bugs/struct.rb, spec/filters/unsupported/privacy.rb
Exclude new struct tests
Covers:
* https://github.com/opal/opal/pull/1159
* https://github.com/opal/opal/pull/1158
* https://github.com/opal/opal/pull/1153
=> Latest rubyspecs

lib/opal/compiler.rb, lib/opal/nodes/definitions.rb, spec/filters/bugs/language.rb, spec/lib/compiler_spec.rb, spec/lib/parser/undef_spec.rb
Rubyspecs for this are in https://github.com/ruby/rubyspec/pull/145
=> Allow undef to take in multiple methods at the same time

CONTRIBUTING.md, tasks/testing.rake
Revise CONTRIBUTING.md to make it more in line with how the test suite works now and fix a couple bugs in the test suite.
=> Revise CONTRIBUTING

CONTRIBUTING.md
In response to @vais (https://github.com/opal/opal/pull/1180#issuecomment-155060845) :)
=> doc: On the number of commits per PR

stdlib/js.rb
=> fix JS.new to work with DOM objects

README.md
Deleted one of repeated 'but' .
=> delete repeat "but"

spec/opal/stdlib/native/new_spec.rb, stdlib/native.rb
=> fix Native to work with Array

opal/corelib/runtime.js
=> Split the internal runtime bridge() helper

opal/corelib/module.rb, opal/corelib/runtime.js, spec/opal/core/module/fixtures/classes.rb, spec/opal/core/module/method_lookup_spec.rb
=> Fix method lookup on a Module when the same method was defined on a Class.

spec/opal/stdlib/native/array_spec.rb, spec/opal/stdlib/native/hash_spec.rb, spec/opal/stdlib/native/struct_spec.rb, stdlib/native.rb
=> Fix Array#to_n, Hash#to_n, Struct#to_n when the object contains native objects.

lib/opal/paths.rb
Terribly sorry about having it lost in previuous PR
=> removed debug point 'binding.pry'

.gitignore, .travis.yml, README.md, opal.gemspec, spec/lib/spec_helper.rb
=> Add coverage tracking with Coveralls

.travis.yml, lib/opal/cli_runners/applescript.rb, lib/opal/cli_runners/nashorn.rb, lib/opal/cli_runners/nodejs.rb, lib/opal/cli_runners/phantomjs.rb, lib/opal/cli_runners/server.rb
For some reason a number of not so old rubies were in the allowed failures.
=> Don't leave anyone behind (err… except for Ruby 1.8)

opal/corelib/runtime.js
=> Always populate all stub_subscribers with all method stubs.

stdlib/nodejs/dir.rb
=> Fix nodejs implementation of Dir.pwd and Dir.[].

README.md
=> Fixed mspec to redirect to updated link

CHANGELOG.md, stdlib/pathname.rb
As @elia said this is not very efficient... but this is working! Feel free to add inline comments to improve the implementation
=> Resolves #1301, Implement Pathname.join and Pathname.+

stdlib/nodejs/file.rb
=> Resolves #1302, Remove encoding flag before calling Node.js openSync method

lib/opal/parser/lexer.rb, spec/lib/parser/string_spec.rb
=> Fix issue #1320 (Unable to create string literal using `%&string&`)

CHANGELOG.md, lib/opal/compiler.rb, lib/opal/nodes/base.rb, lib/opal/nodes/rescue.rb, lib/opal/nodes/scope.rb, spec/filters/bugs/language.rb
=> Add support for begin;rescue;else;end.

CHANGELOG.md, opal/corelib/enumerator.rb, spec/filters/bugs/enumerator.rb, spec/opal/core/enumerator/with_index_spec.rb
=> Fix Enumerator#with_index to return the result of the previously called method.

HACKING.md
* `git submodule` needs to be updated before `bundle install`
* Rake task `mspec_rubyspec_node` doesn't exist
=> Update hacking procedure

CHANGELOG.md, opal/corelib/file.rb, spec/rubyspecs
=> Resolves #1219, Implement File.extname method

CHANGELOG.md, opal/corelib/error.rb
Rubyspecs - https://github.com/ruby/spec/pull/202
=> Name is optional on MRI, fix this

lib/opal/parser/lexer.rb, spec/lib/parser/call_spec.rb
=> Fix parsing of method call starting after "\" on the next line.

stdlib/nodejs/file.rb
`File::Stat` object has a *lot* of methods but for now I've just implemented `file?`.
Resolves #1404
=> Resolves #1404, Implement File.stat

stdlib/nodejs/file.rb
=> Resolves #1402, File.exist? now support IO object as parameter

stdlib/pathname.rb
- split
- dirname
- basename
- directory?
- extname
- comparaison
=> Implement missing Pathname methods

opal/corelib/number.rb
A function containing a try/catch construct cannot be optimized. This commit extracts the work to a function that can be optimized. The actual `<=>` operator just wraps it and potentially rescues the exception.
I made a [jsperf](http://jsperf.com/deoptimizations-with-try-catch-finally) for a talk I gave a couple weeks ago that demonstrates the kind of performance benefit this sort of extraction has.
=> Optimize number spaceship

opal/corelib/module.rb, spec/opal/core/method/arity_spec.rb, spec/opal/core/method/parameters_spec.rb
Closes https://github.com/opal/opal/issues/1424.
cc @wied03 @elia
=> Fix Method#arity and Method#parameters for methods generated using attr_reader/attr_writer.

lib/opal/parser/lexer.rb, lib/opal/regexp_anchors.rb, spec/opal/core/language/ternary_operator_spec.rb
=> Fix parsing of 'query_method?? true : false'.

lib/opal/nodes/logic.rb, opal/corelib/number.rb, spec/ruby_specs
Closes https://github.com/opal/opal/issues/1311
=> Add ruby/core/integer/times_spec to the test suite.

CHANGELOG.md, lib/opal/compiler.rb, lib/opal/fragment.rb, lib/opal/nodes/base.rb, lib/opal/source_map.rb, spec/opal/core/source_map_spec.rb
I realize this doesn't have class names, etc. in yet but it's a start (I hope better than nothing).
=> Add method names to source maps

stdlib/nodejs/file.rb
=> Remove Node non I/O File methods now that File corelib has a rubyspec

CHANGELOG.md, opal/corelib/file.rb, spec/filters/bugs/pathname.rb, stdlib/pathname.rb
Rubyspecs - https://github.com/ruby/spec/pull/241
=> Implement Pathname#relative_path_from

stdlib/nodejs/file.rb
=> Use unsupported_features_severity config to display or not warning messages about unsupported features

CHANGELOG.md, stdlib/nodejs/io.rb, test/nodejs/test_file.rb
Resolves #1346 & resolves #1221
=> Implement IO.each_line & IO.read method for Node.js

stdlib/nodejs/dir.rb, stdlib/pathname.rb, tasks/testing.rake, test/nodejs/test_dir.rb, test/nodejs/test_file.rb
=> Resolves #1407, Implement Pathname.entries (Node.js)

lib/opal/compiler.rb, lib/opal/nodes/call.rb, lib/opal/nodes/call_special.rb, lib/opal/nodes/iter.rb, lib/opal/nodes/logic.rb, lib/opal/nodes/super.rb, lib/opal/rewriters/base.rb, lib/opal/rewriters/break_finder.rb, spec/filters/bugs/language.rb
Extracted `Compiler#has_break!/#has_break?` to a separate class + minor refactoring.
=> Minor break fixes.

lib/opal/cli.rb, spec/lib/cli_spec.rb
Fixes #1521 and trying to end thread on #1510
=> Throw error when lib_only and no libraries

lib/opal/compiler.rb, lib/opal/rewriter.rb, lib/opal/rewriters/explicit_writer_return.rb, spec/filters/bugs/language.rb, spec/filters/bugs/range.rb
Partially closes #1520
Completely closes #1518
=> Fix returning value of method writers. Fix value of begin-rescue-else-ensure-end

CHANGELOG.md, opal/corelib/module.rb, opal/corelib/runtime.js, spec/filters/bugs/module.rb
=> Fixed inheritance from Module class.

CHANGELOG.md, opal/corelib/error.rb, opal/corelib/runtime.js, spec/opal/core/runtime/rescue_spec.rb
=> Add JS::Error class that can handle any JS errors in rescue.

docs/unsupported_features.md
`Module#method_added` and `Module#method_removed` are supported now.
=> Remove method_added and method_removed from Unsupported Features

docs/unsupported_features.md
Related to https://github.com/opal/opal.github.io/issues/21 and https://github.com/opal/opal/issues/896
=> add Numbers into Unsupported Features

appveyor.yml
@elia You will still have to create the project on [appveyor.com](https://www.appveyor.com) and configure the webhook on GitHub (the URL looks like `https://ci.appveyor.com/api/github/webhook?id={{ ID }}`)
=> Enable Appveyor build

appveyor.yml
References: 
* https://www.appveyor.com/docs/installed-software/#ruby
* https://www.appveyor.com/docs/lang/ruby/#build-matrix
=> Use Ruby 2.3.1 on Appveyor build

lib/opal/cli_runners/phantom.js
Should resolve #1488
It's working with Phantomjs 2.1.1 on Windows
=> Resolves #1488, reading /dev/stdin is not working everywhere

appveyor.yml, tasks/testing.rake
=> Moooore tests on AppVeyor

opal.gemspec
Latest parser release: https://github.com/whitequark/parser/releases/tag/v2.3.3.1
=> Bump up parser gem's version to 2.3.3.1

stdlib/nodejs/file.rb, test/nodejs/test_file.rb
Resolve one issue in https://github.com/opal/opal/issues/1619
=> Explicit return

lib/opal/paths.rb, stdlib/nodejs/file.rb, tasks/testing.rake, test/nodejs/fixtures/hello.rb, test/nodejs/test_file.rb, test/nodejs/test_opal_builder.rb
Based on #1620 (otherwise the test will fail)
=> Resolves #1619, adds a test to compile Ruby code with opal-builder.js

opal/corelib/array.rb, opal/corelib/hash.rb, opal/corelib/runtime.js, spec/mspec-opal/formatters.rb, stdlib/nodejs/stacktrace.rb
https://gist.github.com/435d1b7e7d840035d53b91d6583cdee3
before:
```
2017-02-bwl21:master ⤑ opal -I. main.rb                                                                                                                                                    ~/C/o/_/2017-02-bwl21
36.244 ruby
0.071 convert ruby to js
0.362 javascript
result is equal: true
```
after:
```
2017-02-bwl21:master ⤑ opal -I. main.rb                                                                                                                                                    ~/C/o/_/2017-02-bwl21
11.121 ruby
0.081 convert ruby to js
0.361 javascript
result is equal: true
```
cc @bwl21
=> optimize hash

CHANGELOG.md, opal/corelib/hash.rb, opal/corelib/runtime.js, spec/filters/unsupported/hash.rb
depends on https://github.com/ruby/spec/pull/424
=> Add Hash#compare_by_identity

opal/corelib/array.rb
=> Further Array#any? optimization

stdlib/nodejs/io.rb
=> Resolves #1663, alias IO.write/.read to File.write/.read

lib/opal/rewriters/hashes/key_duplicates_rewriter.rb, opal.gemspec, opal/corelib/file.rb, opal/corelib/kernel.rb, opal/corelib/runtime.js, spec/filters/bugs/file.rb, stdlib/nodejs/stacktrace.rb
=> File.expand_path with actual pwd

lib/opal/builder.rb, opal/corelib/file.rb, opal/corelib/kernel.rb, spec/opal/javascript_api_spec.rb, stdlib/nodejs/file.rb, stdlib/opal-builder.rb, test/nodejs/test_dir.rb, test/nodejs/test_file.rb
And make sure it always passes a number down to Opal.exit().
Fixes #1706 
cc @Mogztter
=> Make Kernel#exit support false as status

lib/opal/nodes/call_special.rb, spec/opal/stdlib/js_spec.rb
=> Complex .JS.method calls are now propertly handled

lib/opal/rewriters/base.rb, spec/lib/compiler_spec.rb
@iliabylich picking up where we left on gitter, feel free to comment and add commits direclty to the branch
=> dummy location for rewriters

CHANGELOG.md, stdlib/nodejs/file.rb, test/nodejs/test_file.rb
=> Implement File#symlink? for Node.js

CHANGELOG.md, stdlib/nodejs/dir.rb, test/nodejs/test_dir.rb
=> Implement Dir#glob for Node.js

opal/corelib/array.rb, spec/opal/core/array/dup_spec.rb
=> Adds specs on Array.dup optimization

opal/corelib/string/unpack.rb
- 'C*' returns the buffer
- 'c*', 'a*', 'A*' reads all
=> Optimize String#unpack

.codeclimate.yml, .rubocop.yml, .travis.yml, appveyor.yml, tasks/linting.rake
testing codeclimate w/ rubocop
=> codeclimate rubocop

CHANGELOG.md, spec/opal/stdlib/native/alias_native_spec.rb, spec/opal/stdlib/native/deprecated_include_spec.rb, spec/opal/stdlib/native/native_reader_spec.rb, spec/opal/stdlib/native/native_writer_spec.rb, stdlib/buffer.rb, stdlib/buffer/array.rb, stdlib/buffer/view.rb, stdlib/console.rb, stdlib/native.rb
=> Deprecate include Native, use Native::Wrapper

CHANGELOG.md, lib/opal/builder.rb, lib/opal/cli.rb, lib/opal/cli_options.rb, lib/opal/config.rb, opal/corelib/runtime.js, spec/lib/builder_spec.rb, spec/lib/config_spec.rb, spec/lib/dependency_resolver_spec.rb, spec/lib/spec_helper.rb, tasks/benchmarking.rake, tasks/building.rake
This is potentially a breaking change for people that were relying on the bug but I think it's worth fixing it.
=> Raise LoadError directly from the runtime

opal.gemspec
Closes https://github.com/opal/opal/issues/1790
=> Bump parser to 2.5.0.5.

lib/opal/nodes/arglist.rb, spec/filters/bugs/encoding.rb, spec/filters/bugs/language.rb
Closes https://github.com/opal/opal/issues/1797
=> Wrap array in the arglist into one more array.

opal/corelib/kernel.rb, spec/opal/javascript_api_spec.rb
Context: https://github.com/opal/opal/pull/1803#issuecomment-382160334
=> Returns the exit code

lib/opal/nodes/x_string.rb, spec/lib/compiler_spec.rb
```
%x{
}
```
this now crashes the compiler
=> Support empty x-strings

lib/opal/builder.rb, spec/lib/builder_spec.rb
=> Use relative module names in Builder#build

spec/lib/builder_spec.rb, stdlib/nodejs/file.rb, test/nodejs/test_file.rb
This test should fail on Appveyor (Windows)
=> Add a test on module name with front slash

lib/opal/nodes/logic.rb, spec/opal/core/language/while_spec.rb, vendored-minitest/minitest.rb
=> Add a continue to break the current iteration when using redo

stdlib/nodejs/io.rb, test/nodejs/test_io.rb
Credits to: https://github.com/mathiasbynens/jsesc
=> Implement binread (mimic ASCII-8BIT encoding)

opal/corelib/string.rb, spec/opal/core/string/to_sym_spec.rb
Closes https://github.com/opal/opal/issues/1834
=> Return string literal from the String#to_sym method.

opal/corelib/runtime.js, opal/corelib/string.rb
Builds on https://github.com/opal/opal/commit/6ce0619e0e1acdb2ba8ca406263bd8a2a329a91f
Fixes #1659 
reaching 1.06x vs the inlined block
cc @mojavelinux @Mogztter
=> improve String#to_proc perf

opal/corelib/array.rb
Resolves https://github.com/opal/opal/issues/1783
=> #1783 use Opal#truthy in Array#select

opal/corelib/file.rb, spec/filters/bugs/file.rb, spec/ruby_specs, stdlib/nodejs/dir.rb, stdlib/nodejs/file.rb, stdlib/nodejs/pathname.rb, test/nodejs/test_file.rb
=> Implement File#absolute_path

LICENSE, README.md, opal/corelib/constants.rb
=> 🎉🎉🎉 Happy New Year!

opal/corelib/time.rb, spec/opal/core/time_spec.rb
=> gmt_offset (alias utc_offset) should return 0 if the date is utc

opal/corelib/string/encoding.rb, spec/filters/bugs/encoding.rb
Probably a naive implementation but I was able to enable quite a few specs :wink:  
Resolves #1943
//cc @mojavelinux
=> Implement String#each_codepoint and String#codepoints

opal/corelib/string/encoding.rb
=> Inline codePointAt in the yield

opal/corelib/error.rb, tasks/testing.rake, test/nodejs/test_error.rb
=> Preserve Exception.stack

lib/opal/cli_runners.rb, lib/opal/cli_runners/compiler.rb, spec/lib/cli_runners_spec.rb
Just some recfactoring to give the compiler runner its proper place.
=> Move the compiler runner to its own file

opal/opal/mini.rb
=> Add opal/io to opal/mini

.travis.yml
JRuby 9.2.9.0 was released last week with memory and startup time improvements. Might as well update!
=> Update to JRuby 9.2.9.0.

lib/opal/rewriters/for_rewriter.rb, spec/lib/rewriters/for_rewriter_spec.rb
Fixes #2033
Thanks @iliabylich
=> Fix nested for-loops

lib/opal/cli_runners/chrome.js, lib/opal/cli_runners/chrome.rb
=> Chrome runner fixes (backport to 1.0)

.overcommit.yml, .travis.yml, appveyor.yml, bin/git-submodule-fast-install, bin/setup, opal.gemspec
Submodules checkout was tacking up to 80s, plus other optimizations (see commit messages).
=> Make CI builds faster

.jshintrc, opal/corelib/runtime.js, spec/lib/builder_spec.rb
Fixes #2042 
Another PR to add some specs for the REPL is on its way.
_Happy Christmas!_
=> Support globalThis

opal/corelib/runtime.js
=> Make the tin can a ton.

spec/ruby_specs, stdlib/securerandom.rb
As the title says, with enabled specs.
=> SecureRandom#hex(n)

opal/corelib/io.rb
=> Implement print and puts in js

opal/corelib/runtime.js, spec/opal/core/hash/internals_spec.rb
Fixes https://github.com/opal/opal/issues/2104
=> Ensure string keys are converted to values in Hash#delete

spec/opal/stdlib/pp_spec.rb, stdlib/pp.rb
Closes #2122 
@hmdne @davispuh I put together both your solutions from #2122 and I think this shorter version will be equally effective with less changes, thanks for fixing this!
=> Fix Object#pretty_inspect

opal/corelib/string/encoding.rb, spec/filters/bugs/string.rb, spec/opal/core/string/each_byte_spec.rb
=> Compliant UTF8 to bytes implementation

docs/sinatra.md
Tested on opal 1.0/1.1 and opal-sprockets 0.4.9/0.5.0
=> Update Sinatra documentation

opal/corelib/runtime.js, opal/corelib/string/encoding.rb, spec/filters/unsupported/string.rb
_Just an additional commit over #2181 and #2183 by @rubys_
=> Fix finding encoding aliases

README.md
**Reference issue**: #2201
- Replaced the image with the SVG ['nebulab_black.svg'](https://nebulab.com/assets/img/logo-nebulab_black.svg) on line 237
- Added alt text for images without them (lines 6, 31, 224, 233)
- <details><summary>Removed 1px SVGs found on 234 to 242</summary>On navigating to the resource links, there were SVGs that were only 1px. I figured that the code was left-over from a previously used format - but I'll add them in again if needed!</details>
I hope that all is in order, and thank you for helping me contribute to this project!
=> [Doc] Fixed broken 'Become a Sponsor' image

README.md
Fixes https://github.com/opal/opal/issues/2226
=> Add a "Versioning" section to the README

lib/opal/nodes/args/arity_check.rb, lib/opal/nodes/args/parameters.rb, lib/opal/rewriters/arguments.rb
Preliminary kwnilarg (**nil) support. No checks are performed yet.
=> Parser 3.0: kwnilargs (**nil) support

opal/corelib/runtime.js, spec/opal/core/runtime/constants_spec.rb
=> Module inclusion bug fix with spec

.gitignore, spec/filters/bugs/basicobject.rb, spec/filters/bugs/exception.rb, spec/filters/bugs/hash.rb, spec/filters/bugs/kernel.rb, spec/filters/bugs/language.rb, spec/filters/bugs/module.rb, spec/filters/bugs/pathname.rb, spec/filters/bugs/proc.rb, spec/filters/bugs/range.rb, spec/filters/bugs/set.rb, spec/filters/bugs/string.rb, spec/filters/bugs/struct.rb, spec/filters/bugs/time.rb, spec/filters/unsupported/freeze.rb, spec/filters/unsupported/refinements.rb, vendored-minitest/minitest/assertions.rb
Nothing big I think, just a chore.
=> Update all spec submodules to the current masters

lib/opal/repl.rb, opal/corelib/random.rb, opal/corelib/random/formatter.rb, opal/opal.rb, spec/filters/bugs/random.rb, spec/ruby_specs, stdlib/securerandom.rb
This fixes #2170, but also bring us closer to MRI otherwise.
=> A proper SecureRandom support + Random::Formatter module

lib/opal/nodes/variables.rb, lib/opal/rewriters/logical_operator_assignment.rb, opal/corelib/module.rb, opal/corelib/runtime.js, spec/lib/rewriters/logical_operator_assignment_spec.rb, spec/opal/core/module_spec.rb
=> Rework class variables to support inheritance correctly

lib/opal/compiler.rb, lib/opal/nodes/while.rb, spec/filters/bugs/language.rb
In turn refactor the while node.
This fixes #575
=> Implement begin .. end while

.rubocop.yml, lib/opal/source_map/file.rb, spec/lib/source_map/file_spec.rb, spec/lib/source_map/index_spec.rb
=> Source map: lines should start from 1, not 0

opal/corelib/boolean.rb, opal/corelib/runtime.js, spec/filters/bugs/language.rb, spec/opal/core/boolean_spec.rb
This fixes #2230 
Unfortunately, the implementation of the getter property setting has not been implemented successfully.
It is not a best practice and we would appreciate it if you could fix it.
=> Bug: TrueClass === false; FalseClass === true #2230

opal/corelib/number.rb
=> ensure 0.digits == [0]

opal/corelib/runtime.js, spec/opal/core/hash_spec.rb
=> Correctly delete hash members when dealing with Object strings.

lib/opal/cli.rb, lib/opal/cli_options.rb, lib/opal/cli_runners/compiler.rb, lib/opal/compiler.rb, lib/opal/fragment.rb, lib/opal/nodes/base.rb, lib/opal/nodes/definitions.rb, lib/opal/nodes/helpers.rb, lib/opal/rewriters/binary_operator_assignment.rb, lib/opal/rewriters/block_to_iter.rb, lib/opal/rewriters/for_rewriter.rb, lib/opal/source_map/file.rb, spec/lib/source_map/file_spec.rb, spec/lib/source_map/index_spec.rb
In this PR I will attempt to improve the source map support in Opal
=> Source map workshop

lib/opal/cli_runners/chrome.rb, lib/opal/repl.rb
Small corrections for Opal 1.3.1
=> Chrome runner touches

opal/corelib/io.rb, spec/opal/core/io/read_spec.rb
Under certain circumstances gets was getting one more character.
I added extensive tests to find the issue.
Thanks to Gregory Cohen for reporting the issue.
=> Fix IO#gets

opal/corelib/basic_object.rb, spec/filters/bugs/basicobject.rb
=> Raise an error if not a string is passed to __send__

opal/corelib/module.rb, opal/corelib/runtime.js, spec/opal/core/language/super_spec.rb
=> Fix defining multiple methods with the same block 

opal/corelib/basic_object.rb, opal/corelib/boolean.rb, opal/corelib/kernel.rb, opal/corelib/marshal/write_buffer.rb, opal/corelib/runtime.js, opal/corelib/string.rb
I noticed we were first comparing to nil, then !boolean || true. Unless
I'm missing something, all we need to do is make sure it's not false or
nil.
This is a rebase of #1097, I created a new PR because I can't force push to the old one.
=> Optimize truthiness/falsiness checks

lib/opal/parser/patch.rb
=> Fix opalopal <<~END support.

UNRELEASED.md, lib/opal/version.rb, opal/corelib/constants.rb
- The first commit is what we currently have
- The second commit is changelog for #2293 
- The third commit is changelog for #2347
=> Opal v1.4 alpha release work

lib/opal/nodes/super.rb, spec/opal/core/language/super_spec.rb
=> Fix zsuper with args named with js reserved word

opal/corelib/array.rb, opal/corelib/runtime.js
This patchset will focus on runtime optimization.
=> Runtime optimization

lib/opal/nodes/literal.rb, opal/corelib/math.rb, opal/corelib/math/polyfills.rb
* Moved IE11-times polyfills to a separate file.
* Condensed generation of JS-equivalent functions to an
each/define_method.
=> Move `Math` IE11-supporting polyfills to a separate file

opal/corelib/time.rb, spec/filters/bugs/marshal.rb, spec/filters/bugs/time.rb
Co-authored-by: Elia Schito <elia@schito.me>
=> Introduce timezone support for Time

opal/corelib/string.rb, spec/filters/bugs/string.rb
This is how modern Ruby works... maybe not a big change but perhaps we can gain some performance.
=> String methods always return Strings even when overloaded

opal/corelib/hash.rb
same as #2403 just for Hash#each_value
=> Fix exception during `Hash#each_value` if keys get deleted during loop

lib/opal/compiler.rb, lib/opal/nodes/if.rb, spec/opal/core/language/if_spec.rb
=> Fix an edge case of if in the most complex form not returning

lib/opal/cli_runners/chrome.rb
=> Fix space in path preventing chrome runner to start chrome

lib/opal/nodes/definitions.rb
=> Fix await_encountered error for complex begin in top node

opal/corelib/runtime.js
in runtime: alias, method_missing and top_define_method
=> Improve block performance for even more cases

lib/opal/cli.rb, opal/corelib/error/errno.rb, spec/lib/cli_spec.rb
=> Make opal CLI tool work again with pipes

lib/opal/cache/file_cache.rb
=> Limit the number of retries when getting zlib errors

lib/opal/cli_runners.rb, lib/opal/cli_runners/deno.rb, stdlib/deno/base.rb, stdlib/deno/file.rb, stdlib/opal-platform.rb, stdlib/opal/platform.rb
=> bench&runners: Preliminary support for Deno

lib/opal/cli_runners/chrome_cdp_interface.rb, stdlib/headless_browser.rb, stdlib/opal/platform.rb
=> bench&runners: Make headless Chrome platform a generic headless browser platform

lib/opal/cli_runners.rb, tasks/performance.rake, tasks/testing.rake
Part 4/? of https://github.com/opal/opal/pull/2461
=> bench&runners: Testing: Get runners dynamically, disable unavailable runners

lib/opal/nodes/args/prepare_post_args.rb, lib/opal/nodes/def.rb, lib/opal/nodes/iter.rb, lib/opal/nodes/logic.rb, lib/opal/nodes/masgn.rb, opal/corelib/enumerator.rb, opal/corelib/hash.rb, opal/corelib/method.rb, opal/corelib/proc.rb, opal/corelib/runtime.js, opal/corelib/time.rb
Some various optimizations regarding argument passing - performance-wise and bundle-size-wise
=> Optimize argument passing

opal/corelib/runtime.js
This makes the exception stack work correctly also for errors raised in runtime, but they will also gracefully degrade when things aren't loaded yet.
This fixes #1371
=> Remove throws from runtime

.github/workflows/build.yml, spec/filters/platform/firefox/exception.rb, spec/filters/platform/firefox/kernel.rb
depending on #2506 for a clean run
=> Run Firefox specs by default

lib/opal/compiler.rb, opal/corelib/string/encoding.rb, stdlib/opal-parser.rb
Kinda working in Chrome Browsers
=> SourceMap support for Kernel#eval

stdlib/cgi.rb
Could not find specs for it in spec/ruby
=> Add CGI::Util#(un)escapeURIComponent

.eslintrc.js, docs/bridging.md, docs/compiled_ruby.md, lib/opal/nodes/args/extract_kwoptarg.rb, lib/opal/nodes/call.rb, lib/opal/nodes/hash.rb, opal/corelib/array.rb, opal/corelib/enumerable.rb, opal/corelib/hash.rb, opal/corelib/nil.rb, opal/corelib/runtime.js, opal/corelib/string.rb, opal/corelib/struct.rb, spec/filters/bugs/array.rb, spec/filters/bugs/enumerable.rb, spec/filters/bugs/hash.rb, spec/filters/bugs/openstruct.rb, spec/filters/bugs/struct.rb, spec/filters/unsupported/hash.rb, spec/opal/core/hash/internals_spec.rb, spec/opal/core/runtime_spec.rb, spec/opal/stdlib/native/hash_spec.rb, stdlib/json.rb, stdlib/native.rb, stdlib/opal-parser.rb, stdlib/ostruct.rb
Building on #2567 and Fixing #2514
=> Hash < `Map` V3 and support for Object kwargs

opal/corelib/string.rb, spec/opal/core/object_id_spec.rb, stdlib/pathname.rb
=> Fix `String#object_id`, `String#__id__`, `String#hash`

spec/filters/bugs/cgi.rb, spec/ruby_specs, stdlib/cgi.rb, stdlib/cgi/util.rb
This pull request is sponsored by Ribose Inc.
=> CGI::Util: implement a couple additional methods

opal/corelib/range.rb, spec/filters/bugs/range.rb
These four methods are very similar, but bit different.This PR makes these methods more compatible with CRuby.
=> Improve `Range#include?`/`member?`/`cover?`/`===`

.github/workflows/build.yml, opal.gemspec
This PR adds some improvements on CI.
Closes #2625
=> Improve CI

tasks/testing.rake
=> Avoid infinite loop in test

docs/releasing.md, lib/opal/compiler.rb, lib/opal/nodes/literal.rb, spec/lib/compiler_spec.rb, spec/lib/fixtures/build_order/file5.rb.erb, spec/lib/rewriters/hashes/key_duplicates_rewriter_spec.rb, spec/lib/spec_helper.rb, spec/support/source_map_helper.rb, stdlib/bigdecimal.rb, stdlib/optparse.rb
Those were noisy while running the specs.
=> Cleanup some warnings and deprecations

opal/corelib/class.rb, opal/corelib/enumerable.rb, opal/corelib/enumerator.rb, opal/corelib/enumerator/arithmetic_sequence.rb, opal/corelib/enumerator/chain.rb, opal/corelib/enumerator/generator.rb, opal/corelib/enumerator/lazy.rb, opal/corelib/enumerator/yielder.rb, opal/corelib/error.rb, opal/corelib/error/errno.rb, opal/corelib/hash.rb, opal/corelib/helpers.rb, opal/corelib/math.rb, opal/corelib/module.rb, opal/corelib/nil.rb, opal/corelib/numeric.rb, opal/corelib/proc.rb, opal/corelib/random.rb, opal/corelib/random/formatter.rb, opal/corelib/random/math_random.js.rb, opal/corelib/random/mersenne_twister.rb, opal/corelib/random/seedrandom.js.rb, opal/corelib/range.rb, opal/corelib/regexp.rb, opal/corelib/set.rb, opal/corelib/time.rb, opal/corelib/unsupported.rb, opal/corelib/variables.rb
As of now, there are a couple of places we can't use-strictify, like String or Marshal.
=> Use strict in much more places in corelib.

.github/workflows/build.yml, benchmark/run.rb, lib/opal/cli_runners.rb, lib/opal/cli_runners/bun.rb, spec/filters/platform/bun/exception.rb, spec/filters/platform/bun/float.rb, spec/filters/platform/bun/kernel.rb, spec/filters/platform/bun/literal_regexp.rb, stdlib/bun/base.rb, stdlib/bun/file.rb, stdlib/deno/base.rb, stdlib/nodejs/file.rb, stdlib/opal-platform.rb, tasks/performance.rake
no warranty, just a start
do `npm i bun -g` to try
=> Run on Bun

opal/corelib/array.rb, spec/opal/core/array/include_spec.rb
This fixes #2659
Thanks to @magnusrk-ch for finding this issue.
=> Fix Array#include? to respect nil return value

stdlib/quickjs/file.rb
This PR originated from https://github.com/asciidoctor/asciidoctor.js/pull/1735 to add Quickjs File.read support to Opal
=> Add File.read support to QuickJS

lib/opal/nodes/call/js_property.rb, lib/opal/nodes/iter.rb, spec/opal/stdlib/opal_raw_spec.rb
=> Fix .JS. call with block and self

spec/opal/stdlib/native/hash_spec.rb, stdlib/native.rb
=> Native/Hash - Fix Hash from native object contains unexpected values

.github/workflows/build.yml, Gemfile, lib/opal/builder.rb, lib/opal/builder/scheduler.rb, lib/opal/cli_runners/system_runner.rb, lib/opal/nodes/if.rb, spec/lib/builder_spec.rb
=> Support JRuby

.github/workflows/build.yml, Gemfile, lib/opal/builder.rb, lib/opal/cli.rb, lib/opal/repl.rb
depends on #2686
lets see what CI reports ...
=> Support TruffleRuby

.github/workflows/build.yml, .rubocop.yml, lib/opal/builder/scheduler.rb, lib/opal/builder/scheduler/prefork.rb, lib/opal/builder/scheduler/threaded.rb, spec/lib/builder_spec.rb, tasks/building.rake
One thing to note: default thread stack size for TruffleRuby leads to stack overflow exception when compiling parser, must be raised to around 2MB 
This PR depends on #2687 
lets see what CI reports ...
=> Implement Threaded Scheduler for JRuby and TruffleRuby

.github/workflows/build.yml, spec/filters/platform/deno/array.rb, spec/filters/platform/deno/binding.rb, spec/filters/platform/deno/exception.rb, spec/filters/platform/deno/file.rb, spec/filters/platform/deno/kernel.rb, spec/filters/platform/deno/marshal.rb, spec/filters/platform/deno/string.rb, spec/filters/platform/deno/time.rb, spec/opal/core/string_spec.rb
while filtering all the Deno problems for the moment.
=> Enable Deno Github actions runs

opal/corelib/io.rb, opal/corelib/runtime.js, spec/opal/core/runtime/bridged_classes_spec.rb
=> Make Opal.bridge work with JavaScript subclasses even subclasses of already bridged JavaScript classes

.github/workflows/build.yml, lib/opal/nodes/literal.rb, opal/corelib/array/pack.rb, opal/corelib/io.rb, opal/corelib/io/buffer.rb, opal/corelib/marshal/read_buffer.rb, opal/corelib/marshal/write_buffer.rb, opal/corelib/number.rb, opal/corelib/runtime.js, opal/corelib/string.rb, spec/lib/compiler_spec.rb, spec/opal/core/runtime/string_spec.rb
... for creating Strings
Consistently use $str withing String whenever encoding is set
Enable Deno specs again
=> Towards Mutable Strings, Step 1 of X: Introduce global $str helper 

opal/corelib/runtime.js, spec/opal/core/module/include_spec.rb
=> Fix `Module#include` after `#prepend`

Gemfile
=> Add Ruby LSP to the gemfile

spec/filters/bugs/bigdecimal.rb, stdlib/bigdecimal.rb
Backported from https://github.com/plurimath/opal/pull/1
=> BigDecimal: added power and fix methods

opal/corelib/time.rb
the unit arg is used by other specs.
=> Add unit arg to Time.at

stdlib/opal-replutils.rb
bin/opal -e 'binding.irb' -ropal-replutils -rnodejs -ropal-parser
Before:
```
>> 123
<Promise ...>
```
After:
```
>> 123
=> 123
```
=> Fix binding.irb returning promise instead of value
